from pathlib import Path
import json,hashlib,re
D=Path(__file__).parent
rows=[]
def add(id,title,page,side,kind,anchor,deps,scope):
 domain='physics' if page in ['EMG-S01','EMG-S02'] else 'mathematics'
 rows.append(dict(id=id,title=title,page=page if side=='A' else page+'-examples',pair=page,side=side,domain=domain,kind=kind,deps=deps,proof_module='proofs.md#'+anchor,scope=scope,status='completed research argument; not production or independently audited',physical_scope=scope if domain=='physics' else None))
add('def-emg-xs-geometric-electrovac','Geometric electrovac equations and flux normalization','EMG-MS01','A','definition','X0',['lem-emg-lorentz-hodge-calculus','lem-emg-maxwell-current-forms'],'smooth -+++ oriented Lorentz model; Λ0; Ric=2 Maxwell quadratic; geometric field and flux conventions')
add('def-emg-xs-rn-data','Dyonic RN metric and field domains','EMG-MS01','A','definition','X1',['def-emg-xs-geometric-electrovac'],'real M,qe,qm; r>0; f!=0 static chart; full sphere; local potentials in magnetic sector')
add('thm-emg-xs-rn-verification','Full dyonic RN field-equation verification','EMG-MS01','A','theorem','X1',['def-emg-xs-rn-data','GR-Q1','lem-emg-maxwell-observer-stress'],'arbitrary real M and flux lengths; scalar radial Ricci and exact Maxwell closure')
add('prop-emg-xs-rn-curvature','RN curvature invariants and regularity obstruction','EMG-MS01','A','proposition','X1',['thm-emg-xs-rn-verification','GR-Q1'],'K48M²/r6−96MQ²/r7+56Q4/r8; Ric²4Q4/r8; C2 nondegenerate extensions only')
add('def-emg-xs-kn-data','KN metric and potential on exact BL domain','EMG-MS01','A','definition','X3',['def-emg-xs-geometric-electrovac'],'Sigma>0,Delta!=0,pole-free angle chart; real parameters')
add('lem-emg-xs-kn-rational-calculus','Exact rational KN component derivation','EMG-MS01','A','lemma','X3',['def-emg-xs-kn-data','GR-G1-G4'],'complete Γ/Ricci finite formulas; QQ rational arithmetic; determinant/inverse/field/Maxwell/stress checks')
add('thm-emg-xs-kn-verification','Fully verified electric KN electrovacuum','EMG-MS01','A','theorem','X3',['lem-emg-xs-kn-rational-calculus','lem-emg-maxwell-observer-stress'],'all field/metric equations; compact intermediate Ricci entries and executed all-component zero residuals')
add('prop-emg-xs-kn-invariants','KN Maxwell and Ricci invariants','EMG-MS01','A','proposition','X3',['thm-emg-xs-kn-verification'],'R0; Ric²4q4/Sigma4; Maxwell scalar explicit; charged ring C2 obstruction in X4')
add('lem-emg-xs-duality','Classical electrovac dual rotation','EMG-MS01','A','lemma','X5',['def-emg-xs-geometric-electrovac','lem-emg-lorentz-hodge-calculus','lem-emg-maxwell-observer-stress'],'constant angle rotation; star²−1; full E,B stress algebra')
add('prop-emg-xs-kn-dyonic-flux','Dyonic KN and conserved electric/magnetic flux','EMG-MS01','A','proposition','X5',['thm-emg-xs-kn-verification','lem-emg-xs-duality','lem-emg-gauss-finite-chain'],'q_e=q cosβ,q_m=q sinβ; full sphere annuli; asymptotic electric flux limit')
add('ex-emg-xs-zero-rotation','Zero-rotation and zero-charge metric substitutions','EMG-MS01','B','example','X3',['thm-emg-xs-kn-verification','thm-emg-xs-rn-verification'],'a0 RN, q0 vacuum rotating limit, a=q0 Schwarzschild; no uniqueness theorem')
add('ex-emg-xs-rn-charge-sign','Opposite charges give equal RN metric','EMG-MS01','B','example','X1',['thm-emg-xs-rn-verification'],'sign of qe changes field/flux but Q² and metric same')
add('cex-emg-xs-scalar-trace','Zero scalar curvature need not mean vacuum Ricci','EMG-MS01','B','counterexample','X1',['thm-emg-xs-rn-verification'],'charged RN R0 but nonzero Ricci and Ric²')
add('def-emg-xs-ingoing-rn','Selected ingoing RN extension and time orientation','EMG-MS02','A','definition','X2',['thm-emg-xs-rn-verification'],'Rv×rpositive×S², l/n future orientation; no maximality assertion')
add('thm-emg-xs-rn-crossing','Regular RN crossings and local bifurcation extension','EMG-MS02','A','theorem','X2',['def-emg-xs-ingoing-rn','ROOT-IFT'],'simple positive outer root and auxiliary ell*>0 length give dimensionless UV bifurcation sphere; K=(r−rH)/ell* exp(2kappa h); extremal uses smooth ingoing chart only')
add('prop-emg-xs-rn-horizon-data','RN roots, Killing horizons and surface gravity','EMG-MS02','A','proposition','X2',['def-emg-xs-ingoing-rn'],'positiveM; exact discriminant/root/nullness; kappa; zero at extremality')
add('thm-emg-xs-rn-escape','Outer RN escape boundary in selected model','EMG-MS02','A','theorem','X2',['def-emg-xs-ingoing-rn','lem-emg-xs-null-barrier'],'explicit future causal escape r→infinity; no unspecified conformal boundary theorem')
add('thm-emg-xs-kn-extension','Regular ingoing KN metric/field and sphere axes','EMG-MS02','A','theorem','X4',['thm-emg-xs-kn-verification'],'smooth horizon crossing Sigma>0; full sphere smooth beta form; explicit timelike orientation')
add('prop-emg-xs-kn-horizon-data','KN Killing generators, kappa, area and potential','EMG-MS02','A','proposition','X4',['thm-emg-xs-kn-extension','GR-G6'],'M>0,M²≥a²+q²>0; rootspositive; Ωa/RH, κDelta′/(2RH), area4πRH, potentialqrH/RH')
add('lem-emg-xs-null-barrier','Smooth causal-cone collar barrier with screen directions','EMG-MS02','A','lemma','X4a',['GR-G2','thm-emg-xs-kn-extension'],'timelike tau collar; finite sphere cover; normalized causal cones compact; uniform radial Lipschitz bound')
add('thm-emg-xs-kn-escape','Outer KN escape boundary on the selected ingoing model','EMG-MS02','A','theorem','X4a',['lem-emg-xs-null-barrier','prop-emg-xs-kn-horizon-data'],'complete chosen Rv×rpositive×S²; exact future null exterior paths plus no outward crossing')
add('prop-emg-xs-kn-ergoregion','Specified time Killing ergosurfaces and geodesic constants','EMG-MS02','A','proposition','X4',['thm-emg-xs-kn-extension','GR-G6'],'ergoregion defined by selected stationary field; distinct from horizon; test affine geodesic scalars')
add('prop-emg-xs-charged-ring-obstruction','Charged KN ring regularity obstruction','EMG-MS02','A','proposition','X4',['prop-emg-xs-kn-invariants','thm-emg-xs-kn-extension'],'q!=0; Ric² divergence as Sigma→0; no regular ring source, no q0 Weyl proof')
add('prop-emg-xs-rn-local-gauges','Dyonic RN gauges and global exactness obstruction','EMG-MS02','A','proposition','X5',['thm-emg-xs-rn-verification','lem-emg-sphere-flux-holonomy','ROOT-STOKES'],'north/south patches; nonzero magnetic flux forbids global real one-form potential')
add('ex-emg-xs-extremal-horizon','Extremal RN smooth horizon with zero kappa','EMG-MS02','B','example','X2',['prop-emg-xs-rn-horizon-data','thm-emg-xs-rn-crossing'],'exponential simple-root coordinates fail; ingoing chart remains nondegenerate')
add('cex-emg-xs-ergo-is-not-horizon','Equatorial rotating ergosurface differs from horizon','EMG-MS02','B','counterexample','X9',['prop-emg-xs-kn-ergoregion','prop-emg-xs-kn-horizon-data'],'a!=0 subextremal; strict outer radius inequality except axes')
add('ex-emg-xs-superextremal-rn','Superextremal RN absence of radial horizon','EMG-MS02','B','example','X2',['thm-emg-xs-rn-verification','prop-emg-xs-rn-horizon-data'],'Mpositive,Q²>M²; fpositive,rpositive; mathematical model not collapse/censorship theorem')
add('ex-emg-xs-topological-charge','Nonbounding sphere carries source-free charge flux','EMG-MS02','B','example','X5',['prop-emg-xs-rn-local-gauges','prop-emg-xs-kn-dyonic-flux'],'closed field and dual on punctured domain; no regular center source inferred')
add('def-emg-xs-harmonic-mp','Positive harmonic conformastatic electrovac data','EMG-MS03','A','definition','X6',['def-emg-xs-geometric-electrovac'],'Hsmoothpositive on open D⊂R3,ΔH0; sigma±1; coordinate metric and potential')
add('thm-emg-xs-mp-verification','Full harmonic MP Einstein–Maxwell verification','EMG-MS03','A','theorem','X6',['def-emg-xs-harmonic-mp','lem-emg-conformastatic-curvature'],'shared arbitrary-H pure mathematical curvature lemma; exact density Maxwell and tetrad stress')
add('prop-emg-xs-mp-multicenter','Finite positive multicenter MP exterior and fluxes','EMG-MS03','A','proposition','X6',['thm-emg-xs-mp-verification','ROOT-STOKES'],'H1+ΣmA/|x−xA|; distinct excluded centers; regular exterior and sphere fluxes, not individual horizon stability')
add('prop-emg-xs-mp-extremal-rn','Single-center MP is extremal RN exterior','EMG-MS03','A','proposition','X6',['thm-emg-xs-mp-verification','thm-emg-xs-rn-verification'],'Rrho+m; q=sigma m; explicit radial diffeomorphism and potential')
add('def-emg-xs-br-products','Constant-radius BR product models','EMG-MS03','A','definition','X7',['def-emg-xs-geometric-electrovac'],'Lpositive, f=z² positivepatch or f1+z² globalz; coordinates scaled explicitly')
add('thm-emg-xs-br-verification','Product electrovacuum equations from full factor Ricci','EMG-MS03','A','theorem','X7',['def-emg-xs-br-products','GR-Q1'],'explicit 2D Christoffel/Ricci, sphere Ricci, closeddual and Maxwell stress; no completeness assertion')
add('thm-emg-xs-rn-near-horizon','Extremal RN to BR in C-infinity local scaling','EMG-MS03','A','theorem','X7',['thm-emg-xs-br-verification','thm-emg-xs-rn-verification'],'rL+lambdaR,tT/lambda; compact Rpositive domains; all derivative convergence; no global limit')
add('def-emg-xs-null-wave','Smooth null electrovac wave ansatz','EMG-MS03','A','definition','X8',['def-emg-xs-geometric-electrovac'],'length coordinates u,v,x,y; p,q smooth; transverse harmonic h; explicit timelike N')
add('thm-emg-xs-null-wave-verification','Exact electrovac pp-wave family','EMG-MS03','A','theorem','X8',['def-emg-xs-null-wave'],'complete exhaustive Γ/Ricci/Maxwell calculation; H−(p²+q²)(x²+y²)+h')
add('prop-emg-xs-null-invariants','Null wave curvature and zero quadratic invariants','EMG-MS03','A','proposition','X8',['thm-emg-xs-null-wave-verification'],'Ruiuj−Hij/2; all raised-u contractions vanish; not all scalar diagnostic completeness')
add('ex-emg-xs-two-center','Two-center exact exterior with same-sign fluxes','EMG-MS03','B','example','X6',['prop-emg-xs-mp-multicenter'],'distinct x1,x2;m1,m2positive; static exterior solution; no global horizon/stability claim')
add('cex-emg-xs-nonharmonic-vacuum','Nonharmonic H fails electrovac equations','EMG-MS03','B','counterexample','X6',['thm-emg-xs-mp-verification','lem-emg-conformastatic-curvature'],'density Maxwell residualsigmaΔH and metric Ricci residual; matter needed')
add('cex-emg-xs-constant-radius','BR has no non-null areal-radius coordinate','EMG-MS03','B','counterexample','X7',['thm-emg-xs-br-verification'],'r=L constant; spherical classification requiring nonzero dr excludes this genuine electrovac branch')
add('cex-emg-xs-vanishing-scalars','Zero quadratic invariants need not mean flatness','EMG-MS03','B','counterexample','X8',['prop-emg-xs-null-invariants'],'pconstantnonzero,q0,h0 yields nonzero Ricci/field but F²,R,Ric²,K zero')
add('def-emg-xs-si-parameters','SI and geometric solution parameter identifications','EMG-S01','A','definition','X0',['def-emg-geometry-units','def-emg-xs-geometric-electrovac'],'M=Gm/c²,a=J/(mc),q_e=√(G/(4πε0c4))Q; flux/area/kappa units; roles explicit')
add('pthm-emg-xs-rn-model','Dyonic RN as adopted Einstein–Maxwell model','EMG-S01','A','physics-theorem','X1',['post-emg-covariant-maxwell','post-emg-einstein-maxwell-action','thm-emg-xs-rn-verification','def-emg-xs-si-parameters'],'Λ0 electrovac on explicit rpositive domains; source excluded; physical constants positive')
add('pthm-emg-xs-rn-horizons','RN horizon and escape deductions for specified model','EMG-S01','A','physics-theorem','X2',['pthm-emg-xs-rn-model','thm-emg-xs-rn-crossing','thm-emg-xs-rn-escape'],'chosen ingoing manifold; specified escape; extremal/nonextremal conditions inherited')
add('pthm-emg-xs-kn-model','Verified rotating electric KN physical model','EMG-S01','A','physics-theorem','X3',['post-emg-covariant-maxwell','post-emg-einstein-maxwell-action','thm-emg-xs-kn-verification','def-emg-xs-si-parameters'],'Λ0 geometric/SI rescaling exact; model parameters, no observed black-hole claim')
add('pthm-emg-xs-kn-horizons','Rotating model horizons and selected causal escape','EMG-S01','A','physics-theorem','X4a',['pthm-emg-xs-kn-model','thm-emg-xs-kn-extension','prop-emg-xs-kn-horizon-data','thm-emg-xs-kn-escape'],'outer horizon underM²≥a²+q²>0; area,rotation,surfacegravity; no universal formation/uniqueness')
add('pthm-emg-xs-dyonic-model','Dyonic rotating model and gauge obstruction','EMG-S01','A','physics-theorem','X5',['pthm-emg-xs-kn-model','prop-emg-xs-kn-dyonic-flux','prop-emg-xs-rn-local-gauges'],'classical flux parameters; local potentials; no imposed quantum charge quantization')
add('pthm-emg-xs-static-redshift','Stationary RN observer frequency ratio','EMG-S01','A','physics-theorem','X9',['pthm-emg-xs-rn-model','GR-G6','GR-OPTICS'],'fpositive stationary emitterreceiver connected by adopted geometric-optics null ray; no measurement')
add('texp-emg-xs-photon-radius','RN circular null orbit example','EMG-S01','B','thought-experiment','X9',['pthm-emg-xs-rn-model','GR-G6'],'test null geodesic in equatorial fpositive exterior; complete effective-potential computation; no charged orbit or full stability')
add('texp-emg-xs-rotating-ergoregion','Stationary worldline fails timelike condition in ergoregion','EMG-S01','B','thought-experiment','X9',['pthm-emg-xs-kn-model','prop-emg-xs-kn-ergoregion'],'worldline along selected asymptotic time Killing vector; model causal deduction only')
add('pthm-emg-xs-mp-model','Harmonic static multicenter electrovac model','EMG-S02','A','physics-theorem','X6',['post-emg-covariant-maxwell','post-emg-einstein-maxwell-action','thm-emg-xs-mp-verification','def-emg-xs-si-parameters'],'smooth harmonic positive H exterior; physical flux and excluded poles; no regular matter source inferred')
add('pthm-emg-xs-mp-extremal','Single-center extremal charged model correspondence','EMG-S02','A','physics-theorem','X6',['pthm-emg-xs-mp-model','prop-emg-xs-mp-extremal-rn','pthm-emg-xs-rn-horizons'],'exact exterior coordinate correspondence and inheritedRNextension; |Q|/mass extremal SI relation')
add('pthm-emg-xs-br-model','Constant-radius charged product model','EMG-S02','A','physics-theorem','X7',['post-emg-covariant-maxwell','post-emg-einstein-maxwell-action','thm-emg-xs-br-verification','def-emg-xs-si-parameters'],'Λ0 product domain, q_e=L; not asymptotically flat universal black-hole spacetime')
add('pthm-emg-xs-br-limit','Local near-horizon product limit of extremal RN model','EMG-S02','A','physics-theorem','X7',['pthm-emg-xs-rn-model','pthm-emg-xs-br-model','thm-emg-xs-rn-near-horizon'],'explicit coordinate scaling; λdimensionless; compactpositiveR; geometric model limit, no observation')
add('pthm-emg-xs-null-wave-model','Exact coupled electromagnetic plane wave model','EMG-S02','A','physics-theorem','X8',['post-emg-covariant-maxwell','post-emg-einstein-maxwell-action','thm-emg-xs-null-wave-verification','def-emg-xs-si-parameters'],'smooth null field/modelmetric, Λ0; no finite ADM/asymptoticflat claim')
add('texp-emg-xs-null-curvature','Nonzero electromagnetic curvature with zero quadratic scalars','EMG-S02','B','thought-experiment','X8',['pthm-emg-xs-null-wave-model','prop-emg-xs-null-invariants'],'constant nonzero plane-wave profile; conditional counterexample to scalar diagnostic')
add('texp-emg-xs-two-center-model','Two-center ideal static charged configuration','EMG-S02','B','thought-experiment','X6',['pthm-emg-xs-mp-model','prop-emg-xs-mp-multicenter'],'positive harmonic two-center exterior; regular domain excludes centers; no stability or empirical existence claim')
(D/'inventory.json').write_text(json.dumps({'version':1,'items':rows,'pages':[{'pair':p,'domain':'physics' if p in ['EMG-S01','EMG-S02'] else 'mathematics','A_count':sum(x['pair']==p and x['side']=='A' for x in rows),'B_count':sum(x['pair']==p and x['side']=='B' for x in rows)} for p in ['EMG-MS01','EMG-MS02','EMG-MS03','EMG-S01','EMG-S02']]},indent=2)+'\n')
ROOT=Path.cwd(); suppliers=[]
def source(key,path,extent,statement,hypotheses,use,status):
 p=ROOT/path;suppliers.append(dict(key=key,path=path,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),reading_extent=extent,statement=statement,hypotheses=hypotheses,use=use,status=status))
source('GR-G1-G4','physics/research/first-principles-2026-10-03/relativity/scaffold/gr-local-proofs.md','G0–G4 and G6 fully read; G5 also read in source output','nondegenerate connection; signed curvature; metric density and finite chain flux; Killing identity','smooth oriented time-oriented -+++ geometry; CC for manifold bundle interfaces','X0 tensor computation, X2/X4 extensions, X4a frames, X9 geodesic scalars','completed local mathematical arguments; no production receipt inferred')
source('GR-Q1','physics/research/first-principles-2026-10-03/relativity/scaffold/gr-solution-proofs.md','entire Q1–Q5 file read','scalar f radial Ricci and full Kretschmann; explicit Schwarzschild/Kruskal charts and hypotheses','nonzero-f spherical chart; Schwarzschild positive mass for its global model; smooth extension context','X1 RN arbitrary-f algebra; X2 bifurcation construction analogue; X7 sphere Ricci','completed local arguments, not independent audit')
source('EM-C1-C2','physics/research/first-principles-2026-10-03/classical-electromagnetism/scaffold/completed-expansion-arguments.md','C1/C2 complete; no whole-file reading claim','F0i−E/c,Fij epsilonB,A_lower−phi/c; Maxwell sign; Hodge components','flat SR conventions and smooth field; curved conversion separately GA1/2','X0 convention matching; SI α normalization','completed framework source argument read')
source('GA','physics/research/extended-frameworks-2026-10-03/einstein-maxwell-models/workers/geometry-actions/proof-modules.md','GA0–GA8 complete as current displayed carrier','Lorentz star, local gauge/global sectors, finite flux, action/stress and exchange','smooth metric/forms; finite chains; compact variations; sourcefree subset in our uses','X0/X5 formula and flux suppliers; physical action-based model wrappers','concurrent completed local modules; hashes need final integrator refresh')
source('MP-CURVATURE','physics/research/extended-frameworks-2026-10-03/einstein-maxwell-models/workers/matter-limits/mathematical-proofs.md','ML07 entire arbitrary-H Christoffel/Ricci/trace proof, including nine spatial products','Ric00=q/H6−ΔH/H5,Ricij=−deltaΔH/H+(delta q−2HiHj)/H²','Hpositive C3,timeindependent; smooth in ouruse; mathematical only','X6 harmonicMP canonical lemma lem-emg-conformastatic-curvature','completed shared local mathematical proof; not published/audited')
source('ROOT-STOKES','items/thm-stokes-theorem-for-smooth-singular-chains.md','entire statement,facts,proof','finite smooth-chain Stokes','smooth forms,finite smooth singular chains and explicit simplex extension definition','X5 charge/gauge sphereannuli, X6 centerflux calculations','published audited carrier read')
source('KN-REVIEW','physics/research/extended-frameworks-2026-10-03/einstein-maxwell-models/workers/solutions/raw/adamo-newman.pdf','text lines190–1023 and1060–1345 of local extraction: sections2.1/2.2/2.3 complete,3.1 partly,3.2 complete,3.3 through ergosphere partly; notwholepaper','RN/KN construction and actual Newman-Penrose justification; chart/horizon formulas','sourceuses+---,natural units; cited NP/Goldberg–Sachs prerequisites not imported','authoritative comparison only; all local tensor equations recomputed; omitted screen direction horizon shortcut not consumed','retrieved official arXiv1410.6626v2,30pages; literature reading not proof-chain certification')
source('ROOT-IFT','items/lem-choice-free-smooth-inverse-function-theorem-in-euclidean-space.md','entire statement/facts/proof read','smooth local inverse with nonzero derivative','smooth map on open Euclidean set; invertible derivative; choicefree local proof','X2 invert K(r), horizon-chart inverse','published carrier read')
# Precise external aliases used by inventory.
aliases={'GR-G2':'GR-G1-G4','GR-G6':'GR-G1-G4','GR-OPTICS':'GR-Q1','lem-emg-conformastatic-curvature':'MP-CURVATURE'}
for key in ['lem-emg-lorentz-hodge-calculus','lem-emg-maxwell-current-forms','lem-emg-maxwell-observer-stress','lem-emg-gauss-finite-chain','lem-emg-sphere-flux-holonomy','def-emg-geometry-units','post-emg-covariant-maxwell','post-emg-einstein-maxwell-action']:aliases[key]='GA'
for alias,key in aliases.items():
 original=next(x for x in suppliers if x['key']==key);suppliers.append(dict(original,key=alias,alias_of=key))
(D/'supplier-map.json').write_text(json.dumps(suppliers,indent=2)+'\n')
raw=[dict(path=str(p.relative_to(D)),bytes=p.stat().st_size,sha256=hashlib.sha256(p.read_bytes()).hexdigest()) for p in (D/'raw').iterdir() if p.is_file()]
(D/'source-provenance.json').write_text(json.dumps({'date':'2026-10-04','retrieval_url':'https://arxiv.org/pdf/1410.6626','title':'Tim Adamo and E.T.Newman, The Kerr-Newman metric: A Review','version':'arXiv1410.6626v2,14Nov2016; Scholarpedia9(10):31791','pages':30,'raw_ignored':True,'artifacts':raw,'extraction':'system python3 pymupdf; contains null OCR characters; rg-a used; formula ambiguities checked against independently computed tensors','reading_extent':next(x['reading_extent'] for x in suppliers if x['key']=='KN-REVIEW'),'limitations':['not whole-paper reading','no external no-hair/classification proof consumed','source+--- converted via own -+++ calculation','source field normalization not imported; F=dA and SI flux fixed locally','source horizon shortcut omits screen components; own X4a cone lemma supplies full argument'],'failed_retrievals':[]},indent=2)+'\n')
ids={x['id']:x for x in rows};assert len(ids)==len(rows)
external={x['key'] for x in suppliers}|{'ROOT-IFT'}
prose=(D/'proofs.md').read_text()
for x in rows:
 assert '<a id="'+x['proof_module'].split('#')[1]+'"></a>' in prose
 for dep in x['deps']:
  assert dep in ids or dep in external,dep
  if dep in ids:
   assert ids[dep]['side']=='A','B leaf violation'
   assert x['domain']=='physics' or ids[dep]['domain']=='mathematics','domain boundary'
done=set()
def visit(id,active):
 assert id not in active,'cycle'
 if id in done:return
 for dep in ids[id]['deps']:
  if dep in ids:visit(dep,active|{id})
 done.add(id)
for id in ids:visit(id,set())
for p in set(x['page'] for x in rows):
 assert sum(x['page']==p for x in rows)<=100
 assert len({x['domain'] for x in rows if x['page']==p})==1
receipt=json.loads((D/'kn-check.json').read_text());assert receipt['script_sha256']==hashlib.sha256((D/'check-kn.py').read_bytes()).hexdigest()
(D/'structural-checks.json').write_text(json.dumps({'status':'local structural pass','count':len(rows),'checks':['unique IDs','anchorsresolve','internal DAG','B leaves','homogeneous page domain','≤100 items per page','KN receipt hashes current script'],'not_checked':['production engine','independent proof audit','empirical acceptance'],'command':'python3 '+str(D/'build-records.py')},indent=2)+'\n')
print('local structural pass',len(rows),'items')
