import pathlib,json,hashlib,copy,yaml,datetime,difflib
R='frontier-43-complex-representation-15';D=pathlib.Path('research/'+R+'-batch3-decision-metadata-amendment-r1');ids=['thm-generic-irreducibility-and-the-exceptional-parameter-lattice','thm-equivalence-i-epsilon-nu-is-i-epsilon-minus-nu']
sha=lambda b:hashlib.sha256(b).hexdigest();canon=lambda x:json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False);h=lambda x:sha(canon(x).encode());load=lambda p:json.loads(pathlib.Path(p).read_text());write=lambda p,v:pathlib.Path(p).write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
prefix='research/'+R;decpath=prefix+'-alpha-batch-3-5a-decisions.json';old=load(decpath);new=copy.deepcopy(old);c=load(prefix+'-batch-3.proof-contracts.json');m=load(prefix+'-batch-3.pages.json');pre=load(prefix+'-step5-hash-3-pre.json');post=load(prefix+'-step5-hash-3-post.json')
archive={}
for p in [decpath,prefix+'-alpha-batch-3-5a.md',prefix+'-reader-3.md',prefix+'-reader-findings-3.json',prefix+'-refute-3.json',prefix+'-step5-scope-3.json',prefix+'-step5-hash-3-pre.json',prefix+'-step5-hash-3-post.json',prefix+'-batch-3.pages.json',prefix+'-batch-3.proof-contracts.json']:
 b=pathlib.Path(p).read_bytes();dest=D/'original'/pathlib.Path(p).name;dest.write_bytes(b);archive[p]={'raw_sha256':sha(b),'archive':str(dest)}
ledgerrows=[]
for l in pathlib.Path('research/defect-ledger.jsonl').read_text().splitlines():
 if l.strip():
  row=json.loads(l)
  if row.get('run')==R and (row['subject'] in ids or row.get('defect_id','').startswith('f43-b3-fourier')):ledgerrows.append(row)
write(D/'original/actual-native-subject-ledger-rows.json',ledgerrows)
notes={ids[0]:'Independently reviewed the complete current proof with actual compact-picture, K-mode/ladder/detection and rank-one central-character supplier interfaces. The finite cyclic interpolation extracts a weight; all nonexceptional arrows are nonzero. Smooth Fourier Fejer approximation and closed averaged modes prove smooth irreducibility, and Hilbert detection proves the Hilbert conclusion. At positive n the two simple tails give the unique finite simple quotient; at negative n the finite simple submodule and simple quotient tails have the reverse orientation. In repaired step 3.3, each internal tail arrow is nonzero in both directions, so any extracted interior weight reaches the boundary and every outward weight. At nu=-n the inward boundary arrow enters the finite chain, establishing uniqueness of the finite simple submodule. The Killing matrix, coroot, shifted Harish-Chandra polynomial (t^2-1)/8 and Casimir scalar (nu^2-1)/8 give exactly the claimed center/central-character conclusion. No new gap found; the native nonfatal tail-generation defect remains a real repaired finding.',ids[1]:'After completing generic-irreducibility and the actual eigenvalue/meromorphic-intertwiner supplier proofs, independently reviewed all current parameter-sign proof steps. Gamma numerator common poles occur outside the exceptional lattice and the half-integer denominators leave nonzero residues; the normalized quotient removes them in the smooth operator topology. Recurrence factors are nonzero off the lattice and reciprocal at opposite parameters, so both continuous multiplier composites are identity. Parameter continuity extends group intertwining through removed common poles. Imaginary-axis factors have modulus one, giving the Hilbert unitary extension; conjugation separately is anti-unitary. Nonzero exceptional parameters kill the opposite tail/finite strings and admit incompatible irreducible submodule K-supports, so smooth equivalence fails; odd zero is explicitly the identical split representation. The corrected title is necessary to state these exceptional failures. No new gap found; the native fatal overstrong-title defect remains a real repaired finding.'}
subjects=[];guards={}
for i in ids:
 before=pathlib.Path('/tmp/'+i+'.pre.md').read_bytes();now=pathlib.Path('items/'+i+'.md').read_bytes();assert sha(before)==pre['hashes'][i]['item_sha256'];assert sha(now)==post['hashes'][i]['item_sha256']
 (D/'original'/('pre-reader-'+i+'.md')).write_bytes(before);(D/'original'/('current-'+i+'.md')).write_bytes(now)
 # Canonical native reader-post contract replay is exact under its own fingerprint.
 bare={k:v for k,v in c['contracts'][i].items() if k not in ['risk_review','repair_confidence']};assert h(bare)==post['hashes'][i]['contract_sha256'];write(D/'original'/('reader-post-contract-'+i+'.json'),bare)
 page=next(p for p in m if any(x['id']==i for x in p['items']));row=next(x for x in page['items'] if x['id']==i);currentmanifest={**row,'__step6_page_id':page['id']};oldmanifest=load('/tmp/'+i+'.post-manifest.json');assert h(oldmanifest)==post['hashes'][i]['manifest_sha256'];write(D/'original'/('reader-post-manifest-'+i+'.json'),oldmanifest)
 changedkeys=[k for k in currentmanifest if currentmanifest.get(k)!=oldmanifest.get(k)];assert set(changedkeys)<= {'sources','title'}
 cur={'item_sha256':sha(now),'contract_sha256':h(c['contracts'][i]),'manifest_sha256':h(currentmanifest)};assert h(cur)!=h(pre['hashes'][i]) and h(cur)!=h(post['hashes'][i])
 originaldecision=next(x for x in old['decisions'] if x['id']==i);decision=next(x for x in new['decisions'] if x['id']==i);assert decision['verdict']=='accepted_repair' and len(decision['defect_ids'])==1
 ledger=next(x for x in ledgerrows if x['defect_id']==decision['defect_ids'][0]);assert ledger['disposition']=='fixed' and any(x.get('path')==decpath and x.get('obligation')==decision['obligation'] for x in ledger['adjudication_ref'])
 amendment=f" Current item raw bytes equal the immutable reader-post SHA-256 {sha(now)}. The actual composite now differs because native Alpha added only risk_review and repair_confidence to the contract and synchronized the manifest's {', '.join(changedkeys)} to the repaired item. Deleting exactly those two review-only contract keys reproduces the immutable reader-post contract fingerprint; restoring only original source records/title from the hash-matched pre-reader item reproduces the immutable reader-post manifest fingerprint. The full current item is the actual native reader proof/title repair, while these current metadata amendments prevent accepted_repair from naming the exact reader-result composite. This is amended_repair with repair_confidence=1. Existing closed ledger row {ledger['defect_id']} already references this exact touched obligation, so it remains unchanged and no append-only ledger correction is needed. Original accepted_repair and native findings remain archived."
 decision.update(verdict='amended_repair',evidence=notes[i]+amendment,repair_confidence=1,subject_sha256=h(cur))
 subjects.append({'id':i,'obligation':decision['obligation'],'pre_reader_carrier':pre['hashes'][i],'reader_post_carrier':post['hashes'][i],'current_carrier':cur,'current_subject_sha256':h(cur),'reader_post_contract_replayed_by_removing':['risk_review','repair_confidence'],'manifest_changed_keys':changedkeys,'reader_post_manifest':oldmanifest,'current_manifest':currentmanifest,'existing_closed_ledger_row':ledger['defect_id'],'existing_ledger_reference_valid':True,'math_assessment':notes[i]})
 (D/'original'/('actual-reader-delta-'+i+'.diff')).write_text(''.join(difflib.unified_diff(before.decode().splitlines(True),now.decode().splitlines(True),fromfile='exact-native-pre-reader',tofile='exact-native-reader-post-and-current')))
 f=yaml.safe_load(now.decode().split('---')[1]);
 for d in f['deps']+[i]:guards['items/'+d+'.md']=sha(pathlib.Path('items/'+d+'.md').read_bytes())
write(D/'proposed-decisions.json',new)
changes=[a['obligation'] for a,b in zip(old['decisions'],new['decisions']) if a!=b];assert len(changes)==2
fourier=[d for d in old['decisions'] if d['id']=='lem-k-type-decomposition-of-the-sl2-principal-series'];assert fourier and all(d==next(x for x in new['decisions'] if x['obligation']==d['obligation']) for d in fourier)
e={'version':1,'run':R,'branch':'Step5 batch3 accepted-repair composite metadata amendment round1','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'assessment':'Native reader repairs remain mathematically valid. Existing accepted_repair decisions need amended_repair because actual native Alpha review/confidence and manifest synchronization changed the composite. Ledger-unowned diagnostics are secondary; both exact ledger references already correct.','original_archives':archive,'canonical_metadata_raw_guards':{p:v['raw_sha256'] for p,v in archive.items()},'mathematical_raw_guards':guards,'subjects':subjects,'changed_obligations':changes,'preserved_fourier_decisions':fourier,'append_only_ledger_rows':[],'ledger_unchanged':True,'native_reader_log':{'path':prefix+'-dispatch/reader-reader-3.attempt-1.log','raw_sha256':sha(pathlib.Path(prefix+'-dispatch/reader-reader-3.attempt-1.log').read_bytes()),'exact_pre_carriers_recovered_and_hash_verified':True,'log_copied':False},'source_reading':[{'url':'https://ocw.mit.edu/courses/18-757-representations-of-lie-groups-fall-2023/mit18_757_f23_lec_full.pdf','pdf_raw_sha256':sha(pathlib.Path('/tmp/b3-etingof.pdf').read_bytes()),'printed_pages':[48,49,50],'pdf_pages':[49,50,51],'scope':'Complete relevant original §9.1 classification/short exact sequences and §9.2 smooth realization read with PyMuPDF.'}],'coverage_limits':['Complete current two-subject proofs and exact native pre-to-reader item deltas reviewed; all actual direct prerequisite Statement/Definition interfaces checked.','Full key local compact-picture, K-type, ladder, detection, standard-integral, eigenvalue recurrence, meromorphic-continuation and unitary-principal-series arguments checked; not exhaustive recursive audit of all transitive published proofs or full bibliography.','Native original report remains attributed to its reviewer; this is a current owner repair review, with no new judge/audit acceptance or engine gate closure.'],'local_checks':[]}
write(D/'evidence.json',e);print('Prepared two exact amended_repair decisions; '+str(len(guards))+' current math guards. Existing ledger/Fourier refs preserved; no ledger append proposed.')
