import json,hashlib,pathlib
root=pathlib.Path('research/frontier-40-geometry-braids-rep-27-owner-surface-resolution')
rows=[]
def row(id,statement,proof,deps=(),source='more-algebra.tex',labels=(),missing=()):
 rows.append(dict(id=id,kind='lemma',deps=list(deps),statement='Assume the Axiom of Choice. '+statement,strategy='direct',proof_argument=proof,source_evidence={'file':str(root/source),'url':'https://stacks.math.columbia.edu/download/'+source.replace('.tex','.pdf'),'labels':list(labels)},integration_status='proof-written-with-explicit-support-obligations' if missing else 'proof-written',missing_prerequisites=list(missing)))
row('lem-surface-p-basis-subfield-separation','For k of characteristic p, A=k[[X_1,...,X_n]][Y_1,...,Y_m], K=Frac(A), there is a downward directed family K_J containing K^p with intersection K^p, with A finite over A_J=k_J[[X_1^p,...,X_n^p]][Y_1^p,...,Y_m^p]. For every finite L/K, intersection L^p K_J=L^p.',
'''Choose a p-basis b_i of k over k^p by Zorn. For finite J put k_J=k^p(b_i:i outside J). The p-monomials on J form a finite basis of k/k_J. Together with X- and Y-monomials of exponents <p they give an explicit finite basis of A over A_J. If f/g^p lies in every K_J, clearing its denominator in K_J gives b^p f in A_J. Every A_J-derivation therefore kills f. Partial derivatives in X,Y force their exponents to be divisible by p; coefficient derivations dual to each b_i force every coefficient into k^p. Thus f is a pth power, proving intersection K_J=K^p. Directedness uses union of finite J. For a downward directed family F_J with intersection F, a finite-dimensional vector subspace V of H^r meets every F_J^r nontrivially only if it meets F^r nontrivially: induct on r, choose an F_J so the subspace with first coordinate zero has zero intersection, normalize the remaining vector's first coordinate to 1, and use uniqueness and directedness to force its other coordinates into F. Applying this observation to relations among any finite p-independent list proves that this list stays p-independent over some K_J. For finite L/K, prove intersection L^p K_J=L^p by a finite tower: a separable simple step has a basis of pth powers, and intersection is coefficientwise; a degree-p inseparable step uses the finite-dimensional subspace observation on the spans of 1,t,...,t^(p-1). This avoids silently assuming these spans stay linearly independent over every K_J.''',labels=['lemma-p-basis','lemma-intersection-subfields-subspace','lemma-intersection-subfields','lemma-power-series-ring-subfields'],missing=['Map published p-basis/derivation definitions or supply their elementary definitions inside this lemma. AC is spent on the p-basis.'])
row('lem-surface-non-pth-power-detected-by-derivation','If B is a domain of characteristic p, finite type over a complete equicharacteristic Noetherian local ring, and f is not a pth power in Frac(B), some derivation D:B→B has D(f)≠0.',
'''Replace the base by its image, a complete local domain, and use its published finite power-series subring R. Generic Noether normalization gives R[Y]⊂B′⊂B with B′ finite over R[Y] and B′_g=B_g, g∈R nonzero: normalize over Frac(R), then replace each algebra generator x by g x to clear its monic equation. Replace f by g^(pN)f in B′. In L=Frac(B′), df is nonzero because the kernel of the universal absolute derivation is L^p (expand on a p-basis). The preceding separation lemma chooses J so df remains nonzero over K_J. A linear functional on the finite-dimensional differential space gives a K_J-derivation of L detecting f. Clear its values on finitely many A_J-module generators of B′ to obtain D′:B′→B′. Derivations extend to localization by D(a/s)=D(a)/s-aD(s)/s². If B′_g=B_g, multiply D′ by g^(N+1), where g^N times each B′-algebra generator of B lies in B′; the quotient formula proves that this derivation preserves B. Because the initial multiplier g^(pN) has derivative zero, the resulting derivation detects the original f.''',deps=['lem-surface-p-basis-subfield-separation','cor-complete-local-domain-finite-over-a-regular-power-series-ring'],labels=['lemma-find-D','lemma-derivation-extends'],missing=['The generic normalization reduction is proved here from published field Noether normalization; map its exact supplier ID.'])
row('lem-surface-derivations-and-regular-hypersurfaces','Derivations extend through localizations and Noetherian adic completions. If T is regular and D(f) is a unit, T[z]/(z^r-f) is regular.',
'''D(I^n)⊂I^(n-1) gives a compatible map on inverse limits, whose Leibniz identity follows modulo every I^n; the localization quotient formula gives the other extension. Extend D to T[z] with D(z)=0. At a local ring with maximal ideal n containing z^r-f, membership of z^r-f in n² would imply its derivative belongs to n, whereas that derivative is -D(f), a unit. Thus the equation is part of a regular system of parameters, and its quotient is regular. Polynomial regularity and localization regularity are needed here.''',deps=['thm-completion-preserves-regular-local-rings'],labels=['lemma-derivation-extends','lemma-quotient-regular','lemma-degree-p-extension-regular'],missing=['Map exact published regular-local parameter/regular-quotient and polynomial-regularity suppliers; completion regularity alone does not prove them.'])
row('lem-surface-finite-completion-factors','For a finite map R→S of Noetherian rings and p∈Spec(R), R_p^hat⊗_R S is the product of the maximal-adic completions S_q^hat for q over p.',
'''Finite-module completion is tensoring by R_p^hat. For each n, S_p/p^nS_p is Artinian and is the product of its localizations at the finitely many q over p; take inverse limits. In each factor the radical of pS_q is qS_q, so the two adic topologies are equivalent. Quotients commute with completion by exactness. In particular formal fibres for a finite ring extension are factors of residue-field base changes of the old formal fibres.''',deps=['thm-completion-of-a-noetherian-local-ring'],source='algebra.tex',labels=['lemma-completion-finite-extension'],missing=['Map finite-module completion tensor supplier and Artinian product supplier; proof is given, but these exact IDs were not located/read in this session.'])
row('lem-surface-generic-power-series-formal-fibres','For A=k[[X]][Y], every completed local generic fibre A_p^hat⊗_A Frac(A) is geometrically regular.',
'''It is regular before purely inseparable base change because A is regular and regularity survives completion and localization. In characteristic zero finite extensions are separable and preserve regularity. In characteristic p test finite purely inseparable extensions by degree-p towers M⊂M[z]/(z^p-f). Choose a finite A-subalgebra B⊂M with fraction field M and f∈B by clearing denominators with pth powers. B and B[z]/(z^p-f) have unique primes over p since their fraction-field extensions are purely inseparable. The finite-completion-factor lemma identifies A_p^hat⊗M with B_r^hat⊗_B M. Inductively it is regular. The detecting-derivation lemma gives D:B→B with D(f) nonzero; extend through localization, completion, and localization. Its value on f is a unit because it lies in M×. The hypersurface lemma proves regularity after the next degree-p step. This proves geometric regularity by the finite purely inseparable test.''',deps=['lem-surface-non-pth-power-detected-by-derivation','lem-surface-derivations-and-regular-hypersurfaces','lem-surface-finite-completion-factors','thm-completion-preserves-regular-local-rings'],labels=['lemma-helper-G-ring'],missing=['Finite purely inseparable testing and separable base-change preservation of regularity must be proved or mapped; they are not a consequence of the definition alone.'])
row('lem-surface-complete-equicharacteristic-formal-fibres','Every complete equicharacteristic Noetherian local ring has geometrically regular formal fibres at every localization.',
'''For q⊂p replace the ring by its complete local domain quotient by q. Its generic formal fibres suffice, since completion commutes with that quotient. Choose its published finite regular power-series subring. By the finite-completion-factor lemma each generic formal fibre is a factor of the corresponding geometric base change of a generic formal fibre of the power-series subring. The preceding lemma proves that fibre geometrically regular. Quotient, localization, and finite residue extensions preserve the indicated identifications.''',deps=['lem-surface-generic-power-series-formal-fibres','lem-surface-finite-completion-factors','cor-complete-local-domain-finite-over-a-regular-power-series-ring'],labels=['lemma-check-G-ring-easy','proposition-Noetherian-complete-G-ring'])
row('lem-surface-completed-polynomial-generic-fibre','For complete equicharacteristic local A, q maximal in A[t] over its closed point and r⊂q with r∩A=0 and r≠0, the fibre A[t]_q^hat⊗κ(r) is geometrically regular.',
'''The field κ(r) is finite over K=Frac(A). For every finite purely inseparable L/κ(r), choose finite A⊂A′⊂L with Frac(A′)=L. Since A′ is a complete local domain (finite algebra over complete local A, and a domain), finite completion factors reduce the problem to the case κ(r)=Frac(A). In that case rK[t]=(t-f), f∈K. Put T=A[t]_q^hat⊗_A K. Need T geometrically regular over K. Reduce first to a finite regular power-series subring A0 of A, and to factors of the finite base change of its completed polynomial local ring B0. B0 is regular, since A0[t]_q0 is regular. To prove B0⊗K0 geometrically regular in characteristic p, induct on finite purely inseparable extensions as in the generic-power-series lemma. A detecting derivation on a finite A0-subalgebra A1 extends to B0⊗A0 A1 because the completion of a polynomial localization is topologically formally smooth: apply its square-zero lifting property to the map a↦a+εD(a). The resulting derivation detects f, so each degree-p step is a regular hypersurface. In characteristic zero separable extensions suffice. Thus T is regular; ∂/∂t extends to T and sends t-f to 1, so the hypersurface lemma proves T/(t-f) regular. The argument also applies after the finite A′ reduction and hence gives geometric regularity.''',deps=['lem-surface-complete-equicharacteristic-formal-fibres','lem-surface-non-pth-power-detected-by-derivation','lem-surface-finite-completion-factors','lem-surface-derivations-and-regular-hypersurfaces'],labels=['lemma-another-helper-G-ring','lemma-lift-derivation-through-fs','proposition-fs-regular'],missing=['WRITE the continuous square-zero lifting proof for completed polynomial localizations and its finite base changes, including compatibility of inverse-limit lifts. The present argument isolates this exact unresolved obligation; do not cite general André or label this row closed.'])
row('lem-surface-finite-type-formal-fibres','Fields and complete equicharacteristic Noetherian local bases have geometrically regular formal fibres for every essentially finite-type algebra.',
'''A field is a complete local ring. A quotient has the property by completion/quotient compatibility. Reduce finite-type algebras to polynomial rings and induct on the number of variables. For the one-variable step, check local rings at maximal primes q. Put p=q∩R, localize R at p, and base change to its completion. The resulting completed polynomial local ring has the same completion as R[t]_q, as is seen modulo each power of q. Base change of R_p→R_p^hat is regular, and the preceding two fibre lemmas cover respectively the zero and nonzero generic primes after quotienting the complete base by their contraction. Thus the polynomial completion map is regular by composition and faithfully flat descent. To pass from maximal primes to all primes, choose P′ above P in R_m^hat, complete at P′, and use the complete-ring formal-fibre result and faithfully flat descent for R_P^hat→(R_m^hat)_(P′)^hat. Flatness here is the completion/base-change flatness; fibres descend because regularity descends along faithfully flat local maps. These are substantive permanence facts, not an inference from a graph.''',deps=['lem-surface-completed-polynomial-generic-fibre','lem-surface-complete-equicharacteristic-formal-fibres'],labels=['lemma-check-G-ring-maximal-ideals','proposition-finite-type-over-G-ring','lemma-regular-permanence','lemma-regular-composition'],missing=['Map/prove regularity faithful-flat descent and base-change/composition, and flatness of the map between the two completions in the maximal-prime reduction. Parent reports this route independently read; exact closure must remain explicit.'])
row('lem-surface-open-regular-locus','Every finite-type algebra over a field or a complete equicharacteristic Noetherian local ring has open regular locus.',
'''First every complete local domain has a nonempty regular open. It is finite over a regular power-series subring; induct on fraction-field degree. Separable steps become standard étale after choosing a separating primitive element and clearing its equation/discriminant denominators. Degree-p steps are B[z]/(z^p-b) on a nonempty open: a detecting derivation of B has nonzero D(b), and invert D(b) and the denominator identifying the actual finite algebra with this hypersurface. The hypersurface lemma gives regularity. For any finite purely inseparable extension of a residue fraction field of the complete base, choose a finite subalgebra in that field; it is a complete local domain and has a regular open. For a finitely generated field extension K/k, enlarge k and K by finite purely inseparable extensions until K/k is separably generated: choose a transcendence basis; adjoin pth roots of finitely many coefficients in the minimal polynomial of a degree-p inseparable generator, and pth roots of the basis variables; the inseparable degree strictly decreases, giving a finite induction. Therefore every finite-type domain over the complete base has a regular open: base change to this finite inseparable subalgebra, spread a separating transcendence basis plus primitive separable generator to a standard smooth open, and descend regularity by generic flatness (restrict the base also so the open map is faithfully flat). Finally for any prime P at which T_P is regular, choose generators f_i of P_P forming a regular sequence; their generation and regularity spread to an open. On V(P), a nonempty regular open of T/P lifts to a regular open of T by the regular-sequence quotient criterion. The regular locus is stable under generalization, and this condition on every irreducible closed subset implies openness by Noetherian induction.''',deps=['lem-surface-non-pth-power-detected-by-derivation','lem-surface-derivations-and-regular-hypersurfaces','thm-generic-flatness-morphisms'],labels=['lemma-complete-Noetherian-domain-J-0','lemma-J-2','lemma-J-0-goes-down','lemma-J-0-goes-up','lemma-intersection-regular-with-closed','proposition-ubiquity-J-2'],missing=['Map/prove standard étale spread for a finite separable fraction-field extension; separating-transcendence-basis spread; descent of regularity; and openness of regular-sequence condition. These are actual proof obligations rather than a claim that J2 is available by citation.'])
row('lem-surface-complete-equicharacteristic-finite-integral-closure','The integral closure of any complete equicharacteristic Noetherian local domain in a finite extension of its fraction field is finite.',
'''Use the finite regular power-series subring R. For a finite separable extension of Frac(R), choose an integral power basis and use the nondegenerate trace pairing: traces of products of integral elements are integral and belong to R because R is normal; invert one discriminant to place every integral element in one finite R-module. In characteristic p first pass to a finite normal envelope and its maximal purely inseparable subextension. Handle that subextension by degree-p induction. At a step, the preceding normalization B is finite over R, normal and Noetherian. For L=Frac(B)[z]/(z^p-b), b∈B not a pth power, choose D:B→B with D(b)≠0. If u=sum_(j≤i) a_j z^j is integral, differentiate u^p∈B. Its derivative is the pth power of sum_(j≥1) j D(b) a_j z^(j-1), up to the harmless factor D(b)^(p-1), so that sum is integral. Inducting on i gives D(b)^i a_j∈B; the constant coefficient follows by subtraction and normality. All integral elements lie in sum_(j<p) B D(b)^(-(p-1))z^j, hence form a finite B-module. Separable trace finiteness then applies to the normal envelope. Integral closure in the desired intermediate field is a submodule of its finite closure; transitivity of integrality identifies closure of the original domain with closure of R. No Tate or mixed characteristic input is needed.''',deps=['cor-complete-local-domain-finite-over-a-regular-power-series-ring','lem-surface-non-pth-power-detected-by-derivation'],source='algebra.tex',labels=['lemma-Noetherian-normal-domain-insep-extension','lemma-Noetherian-normal-domain-finite-separable-extension','lemma-domain-char-p-N-1-2'],missing=['Map exact normality of power-series ring and separable trace-pairing suppliers. Published polynomial normalization theorem proves the field case only, not this power-series case.'])
row('lem-surface-regular-fibres-preserve-normality','A flat map of Noetherian rings with regular fibres carries normality of the base to normality of the target. In particular a normal essentially finite-type local ring over the permitted bases has normal completion, which is a domain.',
'''At S_Q over R_P the published flat-local depth formula and the inequality dim(S_Q)≤dim(R_P)+dim(fibre) prove S2: the inequality follows by lifting a system of parameters from the base and fibre, which together generate an ideal primary for the maximal ideal. For height≤1 in S, going down bounds dim(R_P)≤1, and the fibre is a quotient of S_Q so also has dimension≤1; base and fibre are regular. Lift their regular systems of parameters. The published sequence-lifting lemma makes their concatenation regular; they generate the maximal ideal, so depth≤dimension≤embedding dimension forces regularity. Thus S is S2 and R1. For completeness, the domain-only published Serre criterion is not enough. An S2 ring is S1, hence has no embedded associated primes; with R0 it is reduced, by injecting into localizations at its minimal associated primes, all fields. Let t∈Q(S) be integral. It lies in every height≤1 localization, since they are regular local domains. Put I={a∈S:at∈S}. If proper, choose a prime minimal over I, of height≥2, and localize there. The localized I is primary for the maximal ideal; S2 supplies an S-regular sequence x,y in I by prime avoidance. From y(xt)=x(yt), regularity modulo x gives xt∈xS, and cancellation gives t∈S, contradiction. Hence S is integrally closed in Q(S). The idempotents of Q(S), one per minimal component, are integral and belong to S, so a local such S has only one component and is a domain. Apply this to the completion map using the preceding formal-fibre lemma and published faithful flatness.''',deps=['lem-surface-finite-type-formal-fibres','cor-flat-local-depth-additivity','lem-flat-local-depth-formula-regular-sequence-split','cor-serre-normality-criterion-two-directions','thm-completion-of-a-noetherian-local-ring'],source='algebra.tex',labels=['lemma-Sk-goes-up','lemma-Rk-goes-up','lemma-normal-goes-up-noetherian'],missing=['Map regular local CM and associated-prime/prime-avoidance suppliers. The proof explicitly includes the extension from domain Serre to general rings; no circular assumption that completion is already a domain.'])
row('lem-surface-finite-type-normalization-finite','Every integral finite-type algebra B over a complete equicharacteristic Noetherian local base has finite normalization; the same holds over a field and after localization.',
'''At every maximal ideal m of B, the preceding formal-fibre lemma implies that the completion of B_m is reduced: flatness embeds it into its generic fibre, which is geometrically regular and hence reduced. For a reduced complete equicharacteristic local ring T, its normalization in Q(T) is the product of the finite normalizations of its finitely many complete domain components, hence is finite by the complete-domain finiteness lemma. If C is the normalization of B_m, flatness embeds C⊗T into Q(T); it is integral, hence a T-submodule of that finite normalization and is finite. Faithful flatness descends its finitely many generators to C. Thus every B_m has finite normalization. J2 gives a nonzero f with B_f regular and normal. To globalize without silently assuming local finiteness is uniform: for every finite birational B⊂B′⊂Frac(B), B′_f is normal; its nonnormal locus is closed. Indeed S2 failures are detected by embedded associated primes of B′/fB′, and R1 failures by its finitely many height-one associated primes, so Serre gives a finite union of their closures. Its finite image Z_(B′) in Spec(B) is closed. For each m choose finitely many global integral elements generating the local normalization; the finite algebra they generate has m outside Z. Quasi-compactness gives finitely many such algebras; their composite has every localization normal, because at each point one selected algebra already equals the local closure. This composite is the normalization and is finite. Localization commutes with integral closure by clearing the denominators in a monic equation. The published finite-type-over-field theorem supplies the field case directly.''',deps=['lem-surface-finite-type-formal-fibres','lem-surface-complete-equicharacteristic-finite-integral-closure','lem-surface-open-regular-locus','thm-integral-closure-finite-finite-type-domain-over-field'],source='algebra.tex',labels=['lemma-analytically-unramified-easy','lemma-characterize-N-1','lemma-openness-normal-locus'],missing=['For nonnormal-locus proof map associated-prime finiteness and Serre criterion for arbitrary domain localizations. No claim of universal catenarity or mixed characteristic is made.'])
files={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in [root/'algebra.tex',root/'more-algebra.tex',root/'flat.tex',root/'resolve.tex']}
packet=dict(version=1,run='frontier-40-geometry-braids-rep-27',consumer='thm-resolution-of-normal-surface-singularities',scope='Normal surfaces over arbitrary fields and complete equicharacteristic local bases, including finite-type modifications.',status='ordered-proof-packet-with-exact-unclosed-support',item_count=len(rows),count_caveat='This is the actual number of proposed rows, not a dependency-graph count. Parent must count all integrated suppliers and split additions in the actual A inventory.',source_hashes=files,reading=dict(instructions='CLAUDE.md and README.md read fully. SCHEMA.md read fully. WORKFLOW.md read in combined output and overlapping 100–240 segment; initial combined output truncated so no complete-file claim for every output carrier.',source_extent=['More Algebra complete arguments for p-bases, subfield intersections, singular locus/J2, derivations, complete formal-smooth regularity, G-ring complete and finite-type proofs, quasi-excellent/Nagata and normal completion.','Algebra complete proof blocks for finite-completion factors, generic Noether normalization, inseparable normalization by derivations, analytically unramified normalization, normality ascent and S_k/R_k ascent; finite-type field normalization published suppliers read fully.','Published complete-local finite power-series subring, domain Serre criterion, completion regularity/localness, depth-localization inequality, flat-local depth/sequence lifting, polynomial-local fibre step, generic flatness read fully.'],retrieval_uncertainty='Source files were supplied as previously fetched official Stacks TeX. No new network retrieval was made and no claim of reading complete chapters or resolve.pdf is made. Hashes bind inspected local sources. Explicit source proof omissions are not certified by citation.'),rows=rows)
(root/'normal-completion-sources'/'helper-packet.json').write_text(json.dumps(packet,indent=2)+'\n')
# Refine the packet after closing the specific completion-derivation gap.
by={r['id']:r for r in rows}
r=by['lem-surface-completed-polynomial-generic-fibre']
r['proof_argument']=r['proof_argument'].replace('A detecting derivation on a finite A0-subalgebra A1 extends to B0⊗A0 A1 because the completion of a polynomial localization is topologically formally smooth: apply its square-zero lifting property to the map a↦a+εD(a). The resulting derivation detects f, so each degree-p step is a regular hypersurface.', 'For finite A0⊂A1⊂M, apply finite-completion factors to A0[t]⊂A1[t]: B0⊗A0 A1 is exactly the product of the local completions of A1[t] at primes over q0. Extend the detecting derivation of A1 coefficientwise to A1[t], fixing t, and then by the already proved localization/completion formulas to every factor. Taking their product gives a derivation on B0⊗A0 A1, and localizing gives one on B0⊗K0 M. Its value D(f) lies in M×. The hypersurface argument closes each degree-p step. The completion formula uses the q0-adic topology, which is equivalent on every finite factor to its maximal-adic topology; no formal-smooth lifting or André theorem is used.')
r['missing_prerequisites']=[]
r['integration_status']='proof-written'
# These supplier interfaces have now been read on current published carriers.
for id,extra in {
 'lem-surface-derivations-and-regular-hypersurfaces':['thm-localisation-and-polynomial-extension-of-regular-rings','lem-regular-local-quotient-by-parameter-is-regular','lem-regular-system-of-parameters-equivalent-basis'],
 'lem-surface-finite-completion-factors':['thm-completion-is-exact-on-finite-modules'],
 'lem-surface-regular-fibres-preserve-normality':['thm-regular-local-rings-are-domains-and-cohen-macaulay','lem-ring-detected-at-associated-prime-localizations','thm-finiteness-of-associated-primes','lem-flat-local-ascent-of-regularity'],
 'lem-surface-finite-type-normalization-finite':['thm-finiteness-of-associated-primes'],
 'lem-surface-complete-equicharacteristic-finite-integral-closure':['lem-trace-pairing-for-a-finite-separable-extension','cor-serre-normality-criterion-two-directions','thm-regular-local-rings-are-domains-and-cohen-macaulay','cor-localisations-of-regular-local-rings-are-regular']
}.items():
 by[id]['deps'].extend(extra)
 by[id]['missing_prerequisites']=[]
 by[id]['integration_status']='proof-written'
by['lem-surface-finite-completion-factors']['proof_argument']+=' Tensor/completion compatibility itself follows by taking a finite presentation R^a→R^b→S→0: exact completion gives the same cokernel as tensoring that presentation by the completed ring. Artinian product decomposition is the Chinese remainder decomposition into the powers of its finitely many maximal ideals; their sufficiently high product is zero. Thus no unproved finite-completion tensor formula is being hidden.'
by['lem-surface-complete-equicharacteristic-finite-integral-closure']['proof_argument']+=' Regular power-series rings are normal: they and all prime localizations are regular and Cohen–Macaulay, hence R1/S2; apply the published domain Serre criterion. The trace of an integral element is integral since it is the sum of its conjugates in a finite normal envelope (with the usual multiplicity); its trace lies in the base fraction field and hence in the normal base. The inseparable induction uses v=sum_(j≥1)j D(b)a_j z^(j-1) with v^p=D(b)^(p-1)D(u^p)∈B, so v is integral; the displayed bound follows exactly without assuming D preserves arbitrary integral closures.'
by['lem-surface-regular-fibres-preserve-normality']['proof_argument']+=' For the denominator-ideal regular sequence, in the localization at a minimal prime over I one has sqrt(I)=m. Depth≥2 means m is contained in no associated prime of S, so I is contained in none either. Finite prime avoidance chooses a nonzerodivisor x∈I. Depth(S/xS)≥1 similarly chooses y∈I nonzerodivisor modulo x. This proves the required sequence in I. At all height-one primes Q(S) localizes into the fraction field of S_Q: a global nonzerodivisor remains one under localization.'
# Keep only the exact remaining mathematical obligations until their proofs below are supplied.
by['lem-surface-finite-type-formal-fibres']['deps'].extend(['lem-ag-local-flatness-regular-parameters','lem-flat-local-ascent-of-regularity','thm-completion-is-exact-on-finite-modules'])
by['lem-surface-finite-type-formal-fibres']['proof_argument']+=' The map between completions in the maximal-prime reduction is flat, by the following direct argument. For a flat local R→S, choose a degreewise finite free resolution of its residue field over R. Tensoring with S is exact in positive degrees; complete those finite S-modules, using exactness of completion, and identify the complex with its tensor over R^hat with S^hat. This gives Tor_1^(R^hat)(k,S^hat)=0. Apply the published lem-ag-local-flatness-regular-parameters, whose first assertion allows a finite S^hat-module without requiring finiteness over R^hat. Locality then gives faithful flatness. In the polynomial step R[t]_q^hat and (R^hat[t]_q′)^hat are actually isomorphic: modulo q^n the coefficients are unchanged since m^n⊂q^n, and localization commutes with this comparison. Composition/base change of regular maps is checked fibrewise using flat-local ascent, after each finite field extension; faithful-flat descent uses the descent clause of lem-flat-local-ascent-of-regularity at each prime. No universal catenarity is used.'
by['lem-surface-finite-type-formal-fibres']['missing_prerequisites']=[]
by['lem-surface-finite-type-formal-fibres']['integration_status']='proof-written'
by['lem-surface-p-basis-subfield-separation']['proof_argument']+=' In the degree-p subfield-intersection step t∈K\\K^p has t^p∈K^p. Choose J0 with t∉K_J0, possible by intersection K_J=K^p. For all J refining J0 the powers 1,t,...,t^(p-1) are independent over K_J; express elements in this fixed basis and intersect their coefficients. Cofinality of refinements proves the result. Thus the source display of a direct sum for every J is used only on a justified cofinal subfamily.'
by['lem-surface-p-basis-subfield-separation']['missing_prerequisites']=[]
by['lem-surface-p-basis-subfield-separation']['integration_status']='proof-written'
by['lem-surface-non-pth-power-detected-by-derivation']['deps'].append('cor-noether-normalisation-module-finiteness')
by['lem-surface-non-pth-power-detected-by-derivation']['missing_prerequisites']=[]
by['lem-surface-non-pth-power-detected-by-derivation']['integration_status']='proof-written'
packet['rows']=rows
packet['reading']['instructions']='CLAUDE.md, README.md, SCHEMA.md and WORKFLOW.md read fully, with overlapping chunked rereads to recover initial output truncation.'
packet['reading']['source_extent'].append('Additional full Algebra geometric-regular testing/descent proof, local flatness criterion proof; published polynomial/localization regularity, regular-local CM/domain, parameter quotient, trace pairing, associated-prime detection/finiteness, regular-parameter flatness and finite-module exact-completion carriers read fully.')
(root/'normal-completion-sources'/'helper-packet.json').write_text(json.dumps(packet,indent=2)+'\n')
row('lem-surface-geometric-regularity-field-test-and-generic-spread','For a Noetherian k-algebra T it suffices to test geometric regularity after finite purely inseparable field extensions. If K/k is finitely generated, finite purely inseparable enlargements K′/K and k′/k can make K′/k′ separably generated. A separably generated generic fraction-field extension of finite-type domains spreads to a standard smooth nonempty open.',
'''Choose a transcendence basis y for K/k and the maximal separable intermediate field M of K/k(y). If K/M has positive inseparable degree, choose β∈K\\M with α=β^p∈M. Write the separable minimal polynomial P of α over k(y). Adjoin to k pth roots of the finitely many coefficients of the numerator and denominator polynomials expressing coefficients of P, and replace each y by y^(1/p). All coefficients of P now have pth roots in k′(y^(1/p)); taking coefficient roots gives a separable polynomial Q whose pth power is P(T^p). Thus the unique pth root β of α lies in a separable extension of the new rational field: Q(β)=0 and Q′(β)≠0. In the compositum K′, the inseparable degree therefore decreases by at least p. Repeat finitely; degrees multiply and all extensions made are finite purely inseparable. In characteristic zero there is nothing to do. For separably generated K/k, choose its separating transcendence basis y and a primitive separable generator θ. Clearing finitely many denominators makes its monic minimal polynomial P have coefficients in R[y]_a for a domain base R with k=Frac(R). Invert P′(θ). The algebra (R[y]_a[θ])_(P′) is a standard smooth algebra over R, and lies inside K; its injection follows by monic polynomial division and minimality over k(y). Given any finite-type R-subalgebra S⊂K with fraction field K, choose a common open containing y,θ and their inverses: the elements y,θ are fractions of elements of S, so first localize S to contain them. Conversely each of its finitely many generators and inverted denominators is a fraction in the standard smooth algebra, so invert their finitely many denominators there. The resulting two localized algebras agree inside K and are a nonempty standard smooth open of S after possibly restricting R. Published standard-smooth flatness and geometric-fibre regularity, together with flat-local regular ascent, prove regularity over a regular base. For the field test, take arbitrary finitely generated E/k and finite inseparable E′/E, k′/k as above. By hypothesis T⊗k k′ is regular. The standard smooth fraction-field model of E′/k′ makes T⊗k E′ regular by smooth ascent and localization. The map T⊗k E→T⊗k E′ is faithfully flat; published flat-local regular descent makes T⊗k E regular. This proves the test and also stability under finitely generated residue-field extensions.''',deps=['lem-ag-standard-smooth-flatness','lem-ag-standard-smooth-regular-geometric-fibres','lem-flat-local-ascent-of-regularity','thm-localisation-and-polynomial-extension-of-regular-rings'],source='algebra.tex',labels=['lemma-make-separably-generated','lemma-geometrically-regular','lemma-geometrically-regular-descent'])
fieldrow=rows.pop()
# Place field support before the first consumer; it has only published deps.
rows.insert(4,fieldrow)
for id in ['lem-surface-generic-power-series-formal-fibres','lem-surface-open-regular-locus']:
 by[id]['deps'].append(fieldrow['id'])
 by[id]['missing_prerequisites']=[]
 by[id]['integration_status']='proof-written'
by['lem-surface-open-regular-locus']['deps'].extend(['lem-flat-local-ascent-of-regularity','thm-regular-local-rings-are-domains-and-cohen-macaulay','thm-quotient-and-lifting-regularity-across-a-regular-element'])
by['lem-surface-open-regular-locus']['proof_argument']+=' Spreading a regular sequence is justified by its successive multiplication kernels: they are finite modules and vanish at the chosen prime, so one denominator kills each kernel; generation of P is spread by the same finite-module argument on P/(f_i). Regularity lifts from the quotient successively by the published regular-element lifting theorem. For generic-flat descent of a regular source open, apply generic freeness to that localized algebra over the domain base; it becomes a nonzero free module, hence faithfully flat (the algebra is nonzero and injection at the generic point guarantees at least one basis element). Published flat-local regular descent then applies. The topological criterion follows by Noetherian induction: on every irreducible closed set the regular locus is empty if its generic point is absent (generalization stability), and otherwise contains a nonempty relative open; induction on the remaining proper closed subset proves constructibility. A constructible generalization-stable subset of a Noetherian space is open, as its specialization-stable constructible complement is closed.'
packet['rows']=rows
packet['item_count']=len(rows)
packet['status']='ordered-complete-proof-package-for-parent-integration-review'
packet['remaining_mathematical_obligations']=[]
packet['readiness_caveat']='Proof completion is the author assessment of these explicit arguments, not independent audit acceptance or a request to clear the engine hold. Parent must integrate exact dependencies, definitions, layout and actual A-item count, and independently review.'
packet['reading']['source_extent'].append('Full current published standard-smooth flatness and regular-geometric-fibre supplier carriers, and standard-etale definition read.')
(root/'normal-completion-sources'/'helper-packet.json').write_text(json.dumps(packet,indent=2)+'\n')
for r in rows:
 if 'def-axiom-of-choice' not in r['deps']: r['deps'].append('def-axiom-of-choice')
packet['supplier_uses']={
 'cor-complete-local-domain-finite-over-a-regular-power-series-ring':'Only its equicharacteristic complete-domain finite injective regular power-series subring, with AC; not mixed characteristic.',
 'thm-integral-closure-finite-finite-type-domain-over-field':'Finite normalization of field finite-type domains; does not supply completion normality.',
 'thm-polynomial-algebras-over-fields-have-finite-integral-closures':'Read in full; confirms finite-field-extension normalization over polynomial fields but is not misused for formal power series.',
 'cor-serre-normality-criterion-two-directions':'Normality iff R1/S2 for Noetherian DOMAINS. Packet supplies the extension to arbitrary Noetherian rings and proves local completion is a domain.',
 'lem-depth-localisation-inequality':'Read in full for parent codimension plan; not needed in packet ascent proof because actual flat-local depth additivity is available.',
 'thm-completion-of-a-noetherian-local-ring':'Completion local, Noetherian and faithfully flat, with same residue field.',
 'thm-completion-preserves-regular-local-rings':'Regular-local completion; never used to assert completion normality directly.',
 'thm-completion-is-exact-on-finite-modules':'Exactness of finite-module completion; finite presentation gives tensor formula, and completing finite resolution gives Tor vanishing for flat-local completion.',
 'cor-flat-local-depth-additivity':'Depth target equals base plus closed-fibre depth, with AC; used for S2 ascent.',
 'lem-flat-local-depth-formula-regular-sequence-split':'Lift base/fibre regular sequences and preserve quotient flatness.',
 'lem-flat-local-ascent-of-regularity':'Both ascent from regular base and fibre, and descent from flat local regular target; used in geometric-regular permanence.',
 'lem-ag-local-flatness-regular-parameters':'Its FIRST assertion permits a module finite over the target without finiteness over the source. This supplies flatness of induced completion maps from Tor_1 vanishing.',
 'thm-localisation-and-polynomial-extension-of-regular-rings':'Only regularity under localization/polynomial extension and maximal-local test, not its global-dimension conclusion.',
 'thm-regular-local-rings-are-domains-and-cohen-macaulay':'Regular rings supply CM/S2 and domains at prime localizations; regular parameter sequences.',
 'lem-regular-local-quotient-by-parameter-is-regular':'A hypersurface equation outside maximal ideal squared has regular quotient.',
 'thm-quotient-and-lifting-regularity-across-a-regular-element':'Lift regularity successively from a regular quotient in the J2 proof.',
 'lem-ag-standard-smooth-flatness':'Flatness of the concrete spread monic separable hypersurface presentation.',
 'lem-ag-standard-smooth-regular-geometric-fibres':'Regularity of its fibre after arbitrary field extension; only clause 1 used.',
 'lem-trace-pairing-for-a-finite-separable-extension':'Nondegenerate trace gives one uniform denominator bounding integral closure.',
 'lem-ring-detected-at-associated-prime-localizations':'S1/R0 ring injects into fields at minimal associated primes and is reduced.',
 'thm-finiteness-of-associated-primes':'Choose regular elements in primary denominator ideal and close global nonnormal locus.',
 'thm-generic-flatness-morphisms':'Generic flatness is read; in the actual affine descent argument its explicitly identified generic-freeness supplier makes the localized nonzero algebra faithfully flat.'
}
packet['integration_notes']=[
 'Three immediate consumer endpoints: finite normalization, open regular locus, normal local completion. Formal-fibre lemmas are internal support; no definition of universal excellence or universal catenarity is needed.',
 'All affine results extend to finite-type integral schemes by finite affine covers, normalization localization compatibility, and agreement in the common function field. The normal-completion conclusion applies to all finite-type normal modifications.',
 'For the surface-resolution theorem, open singular loci on normal dimension-two Noetherian schemes have codimension at least two, so their closed singular set is a finite set of closed points. Regularity is the needed conclusion over arbitrary imperfect fields; do not substitute smoothness.',
 'The source finite-type G-ring proof calls a nonzero-prime characteristic-zero fibre a localization of a regular completion; the packet uses the derivative-one hypersurface argument for that branch instead.',
 'The p-subfield intersection proof needs a cofinal subfamily before asserting independence in a degree-p step; packet makes that refinement explicit.',
 'This packet has thirteen actual rows. A parent may merge finite-completion factors into the existing finite-module completion helper, and geometric-regular field test into an existing genuine supplier, after reading their exact interfaces. A dependency graph cardinality is not an item budget.'
]
packet['rows']=rows
(root/'normal-completion-sources'/'helper-packet.json').write_text(json.dumps(packet,indent=2)+'\n')
fieldrow['deps'].append('thm-primitive-element-theorem-for-finite-separable-extensions')
by['lem-surface-open-regular-locus']['deps'].append('lem-generic-freeness-finite-type-algebra-module')
packet['supplier_uses']['thm-primitive-element-theorem-for-finite-separable-extensions']='Every finite separable extension is simple; current carrier read fully, used to spread one monic polynomial.'
packet['supplier_uses']['lem-generic-freeness-finite-type-algebra-module']='Localized nonzero finite-type domain algebra becomes a nonzero free module over the base, hence faithfully flat; current carrier read fully.'
packet['published_supplier_hashes']={id:hashlib.sha256((pathlib.Path('items')/(id+'.md')).read_bytes()).hexdigest() for id in packet['supplier_uses']}
packet['rows']=rows
(root/'normal-completion-sources'/'helper-packet.json').write_text(json.dumps(packet,indent=2)+'\n')
