import json,hashlib,re,datetime
from pathlib import Path
R='frontier-43-complex-representation-15';prefix=Path('research')
hashbytes=lambda b:hashlib.sha256(b).hexdigest()
def ref(path):
 p=Path(path);return {'path':str(p),'sha256':hashbytes(p.read_bytes())}
def rp(suffix):return f'research/{R}-{suffix}'
started=datetime.datetime.now(datetime.timezone.utc).isoformat()
HAND=json.load(open(rp('complex-final-handoff-evidence.json')));handoff={x['id']:x for x in HAND['owned_items']}
I=json.load(open(rp('complex-escalation-closure-current-inputs.json')))
for x in I['subjects'].values():
 if 'current_examined_dependency_union' in x:x['declared_dependency_union_for_future_root_examination']=x.pop('current_examined_dependency_union')
I['boundary']='Read-only declaration/input capture, not a dependency-examination attestation, native audit, stable snapshot, certification or gate. Native13/14 writers resumed; recompute after all drain.'
Path(rp('complex-escalation-closure-current-inputs.json')).write_text(json.dumps(I,indent=2)+'\n')
pages=[p for b in [12,13,14] for p in json.load(open(rp(f'batch-{b}.pages.json')))];ids={i['id']:{'page':p['id'],'batch':b,'item':i} for b in [12,13,14] for p in json.load(open(rp(f'batch-{b}.pages.json'))) for i in p['items']}
full=[p for path in prefix.glob(R+'-batch-*.pages.json') for p in json.load(open(path))];graph={i['id']:set(i.get('deps',[])) for p in full for i in p['items']}
claims=json.load(open(rp('complex-phase1-handoff-evidence.json')));changed={x['id'] for x in claims['changes'] if x['claim_changed']};changed.add('lem-area-and-l2-derivative-bounds-for-quasiconformal-maps')
# These are descriptions of the already authored and reviewed repairs, not new proofs.
C={
'lem-riemann-maps-of-jordan-domains-extend-homeomorphically':'Existing native ID was relocated to earlier12. Steps6.1–8.1 obtain short rectifiable image half-circles by conformal energy, polar integration and Cauchy–Schwarz before endpoint limits exist. Explicit connected-exterior Jordan arguments establish boundary injection and crosscut components. The unsupported compact-family modulus interface and former page-cycle edge are removed from this proof.',
'thm-geometric-and-analytic-quasiconformality-equivalent':'Earlier quadrilateral core supplies general differentiability/lower area and two-sided quadrilateral bounds. Thin-strip estimates prove ACL independently; FTC and published ACL/weak-W1,2 interface are mapped explicitly. Singular-value square-area comparison gives the sharp K bound without inverse regularity or modulus continuity. The inverse follows by geometric inverse inequalities and this same independent equivalence.',
'lem-inverse-of-a-quasiconformal-map-is-quasiconformal':'Same-K inverse regularity comes first from independent geometric/analytic equivalence. Signed degree/winding on ACL-selected rectangles, smooth inverse branches, rounded-corner C1 Stokes and finite pi-system measure uniqueness prove reverse area. Applying area equality to map and independently regular inverse proves both N properties and positive Jacobian almost everywhere, then the inverse coefficient formula. No circular use of inverse-N occurs.',
'lem-analytic-quasiconformality-implies-modulus-distortion':'Full quadrilateral/annular/area/N-inverse claim retained. Earlier core/equivalence/inverse supply differentiability, signed area equality and independent inverse regularity. Compact-segment barriers and improper weighted lengths compare locally rectifiable proper two-ended annular paths; Jordan neighborhood/collar exhaustion transports both ends, including degenerate rings. Apply the map and independently regular inverse for opposite inequalities. Earlier Jordan/core repair replaces the unsupported rectification supplier cycle.',
'thm-composition-and-inverse-quasiconformal':'Current proof composes the independent geometric quadrilateral bounds, then uses the earlier area/N-inverse interface to transport exceptional differentiability sets and calculate the a.e. Beltrami chain rule. The independent inverse supplier gives the inverse coefficient; the algebraic product bound and group conclusion are retained.',
'thm-one-quasiconformal-is-conformal':'Independent earlier geometric/analytic equivalence reduces K=1 to the weak zero-Wirtinger equation. Distributional harmonicity of the two components and the published Weyl interface give smooth representatives; continuity makes them agree with the homeomorphism, so Cauchy–Riemann yields conformality. The earlier unresolved equivalence input is completed.',
'thm-normalized-quasiconformal-compactness':'Current proof is independent of later general circular/QS regularity: weighted spherical energy and polar Cauchy bounds yield short image circles; Jordan separation and three fixed separated points give equicontinuity for maps and inverses. Ascoli yields a homeomorphic limit. Weak derivative/determinant distribution identities and convex lower semicontinuity give the sharp analytic limit; general Sobolev ACL is explicitly supplied.',
'lem-circular-dilatation-quasisymmetry-and-analytic-quasiconformality':'Essential orientation hypothesis in(iii) retained and actual13 area consumer rerouted to core Remark. Local continuum/circle Loewner bound proves finite macroscopic dilatation from analytic QC; dyadic shrink gives local QS and its explicit global-plane auxiliary control. Only qualitative bounded metric dilatation→some finite analytic QC uses the exact delegated Gehring1967 Definition8-prime citation. Earlier core differentiability and derivative eccentricity then give the sharp L bound. Citation authorization and complete1967 text read are recorded; original1960 proof is not claimed read.',
'ex-affine-quasiconformal-ellipse-map':'Original affine derivative/coefficient calculation is retained; its geometric conclusion now consumes the completed earlier analytic→quadrilateral/full-wrapper interface.',
'ex-radial-stretch-quasiconformal-map':'Original radial derivatives, inverse, coefficient and annulus values are retained; the exact geometric-QC use now consumes the completed earlier modulus-distortion/equivalence chain.',
'ex-quasiconformal-composition-dilatation-bound':'Native positive-area alignment correction remains unchanged. The explicit affine/radial maps and completed composition theorem now supply the previously held product-bound and essential-supremum comparison.',
'ex-modulus-obstruction-to-quasiconformal-equivalence':'Original round-annulus/punctured-disc calculations remain; full earlier two-ended annular distortion, inverse regularity and analytic/geometric equivalence now supply the exact obstruction uses.',
'ex-beltrami-coefficient-of-an-inverse-map':'Independent real-linear inverse computation is retained; its comparison consumes the completed composition/inverse theorem and the now established affine geometric-QC interface.',
'lem-area-and-l2-derivative-bounds-for-quasiconformal-maps':'Differentiability now comes directly from the general earlier core Remark and ACL, avoiding circular(i)/(iii). Existing lower-area density argument and Wirtinger/Hilbert–Schmidt constants remain. Approved Lusin-N clause is restored in full and supplied separately by the earlier full area formula, followed by Borel completion for arbitrary null subsets. Its actual direct consumer is MRMT; no lower-area→N inference remains.',
'thm-measurable-riemann-mapping-sphere':'Earlier local Holder coordinate/atlas/uniformization theorem solves smooth sphere coefficients. Unit-disk mollifier support makes the displayed Lebesgue-point estimate exact. Completed energy and independent normalized compactness give bounded weak derivatives and a homeomorphic limit. The weak pairing passes the equation. Earlier area equality and inverse-N in step4.1 force f_z nonzero a.e. and coefficient equality. Composition/one-QC give uniqueness and all normalizations.',
'cor-local-integrability-beltrami-structures':'The already authored zero-extension, finite-chart restriction and conformal quotient argument now uses complete coefficient-compatible normalized MRMT and earlier composition/one-QC interfaces, with all original local coordinate and uniqueness clauses retained.',
'thm-holder-regularity-beltrami-solutions':'Current local factorization proof consumes established MRMT existence/homeomorphism/weak equation. Injectivity makes the holomorphic factor derivative nonzero, so exact higher-order Holder regularity, positive Jacobian and the chartwise inverse follow from the already authored nondegenerate-coordinate and factorization suppliers. No coefficient-ratio premise is silently added.',
'ex-constant-coefficients-and-affine-solutions':'Direct affine/infinity-chart/ellipse calculations retained; established MRMT now supplies the exact normalized uniqueness and full Mobius family consumed in Statement(b) and Proof3.1.',
'ex-normalization-by-mobius-maps':'Direct normalizer and chart derivative computation retained; complete MRMT supplies normalized uniqueness and the full solution family in the exact existing uses.',
'cex-uniqueness-of-beltrami-solutions-without-normalization':'Explicit identity/inversion counterexample remains direct. Completed analytic/conformal interfaces supply zero coefficient, and complete MRMT supplies the additional general Mobius ambiguity and three-point uniqueness assertion.',
'lem-smooth-arcs-and-circles-are-removable-for-quasiconformal-maps':'Native dyadic-square/Fubini finite-crossing gluing proof now consumes the repaired earlier14 energy bound and12 analytic/ACL equivalence interfaces. The late energy item retains native origin; its origin refresh is held separately from this mathematical supplier closure.',
'lem-ahlfors-extension-of-line-quasisymmetric-maps':'Adjacent-interval extension estimates and local C1/Wirtinger calculation are retained. Earlier analytic definition and independently proved smooth-line gluing now establish the analytic identification and whole-plane/sphere extension.',
'thm-beurling-ahlfors-extension':'Existing line extension, circle descent, reflection and gluing proof consumes completed line/smooth-gluing/composition interfaces. Its analytic-QC→QS use is explicitly the independently proved circular auxiliary global-plane Remark, rather than an unsupported general metric argument. Unit-circle chordal comparison was corrected.',
'def-quasicircle':'All image-based Definitions and infimum caveat retained. Quotient-circle parametrization and Jordan separation give the components; earlier conformal composition/inversion preserves K, proving two quasidisks and Mobius invariance. Unavailable Martin source is disposed by a valid source-only drop with complete local alternative; no definition or derived claim is dropped.',
'thm-quasicircle-characterizations':'Existing bounded-turning/cross-ratio argument and actual Ahlfors reflection-source interface are retained. Earlier completed modulus, Jordan extension, line extension, smooth gluing and composition supply the exact previously held branches. Involutive reflection is constructed by QC conjugation of circle reflection, with the corrected step locator.',
'def-conformal-removable-compact-set':'Rich global and neighborhood-local predicates and their equivalence preserved, with essential AC interface made explicit. Local→global uses the whole-plane neighborhood. Global→local handles compact subsets componentwise, constructs a finite real-analytic collar by Gaussian regular levels with analytic implicit/complete-flow suppliers, extends each complementary disk via earlier BA/gluing, and straightens the inverse coefficient by complete MRMT. Global removability makes the comparison Mobius; zero coefficient on the whole image neighborhood proves the local map conformal. No unproved extension off K or QC-invariance circularity is assumed.',
'lem-zero-length-sets-are-removable-for-continuous-analytic-functions':'Complete finite-H1 proof uses finite overlapping Hausdorff-square covers, polygon-cell perimeter control and internal-edge cancellation. Cauchy is applied only outside the union, subtracting constants on cell contours and using uniform continuity for the vanishing error. Area-zero/density extends the Cauchy formula; sphere compactness and Liouville give constancy. Countable Choice stated. Unread Garnett chapter is not imported; six actual recovery records and valid source-only alternative resolution preserve the claim.',
'lem-round-circles-are-conformally-removable':'Current source-side conformal chart normalization/pasting argument consumes independently proved smooth-circle gluing and earlier one-QC criterion. Its exact analytic/conformal interface is established, and full sphere claim remains.',
'lem-positive-area-compact-sets-are-not-conformally-removable':'Complete sphere MRMT realizes coefficient(1/2) times the finite-chart indicator. Weak zero coefficient off K gives conformality there; prescribed nonzero coefficient on a positive-area set contradicts Mobius conformality. All coefficient/chart/one-QC supplier uses are established.',
'lem-conformal-removability-is-quasiconformally-invariant':'Earlier positive-area counterexample implies removable K has area zero; complete area/N property transports it under QC. Straighten the coefficient of h-inverse composed with the test inverse off its exceptional image, using complete MRMT; removability of K makes the comparison Mobius. The rearranged test map is globally QC and zero coefficient a.e.; one-QC gives Mobius. Apply the forward implication to h-inverse for converse.',
 'thm-zero-length-sets-and-quasicircles-are-conformally-removable':'Finite-length part consumes the complete independent scalar lemma and its retained quotient argument; quasicircle part consumes completed round-circle removability and QC invariance. Full finite-H1 and quasicircle claims remain, with exact MRMT-dependent source uses reconciled.',
 'def-conformal-welding-of-a-jordan-curve':'Full boundary-welding Definition and normalization conventions retained. Earlier relocated Jordan extension supplies the boundary maps, and established quasicircle definition supplies its exact terminology; no later-page cycle remains.',
 'thm-quasiconformal-welding-existence':'Earlier BA disk extension supplies the coefficient inside the disk, zero outside. Complete MRMT realizes it; equal-coefficient composition gives conformal maps on both sides. Native extension-independence and two-sided disk-automorphism constructions remain local and complete using smooth-circle gluing/composition. No stronger uniqueness among arbitrary weldings is asserted.',
 'thm-welding-uniqueness-under-removability':'Existing pasted comparison of two boundary-extended conformal weldings is conformal off the removable curve and therefore Mobius. Earlier Jordan, welding Definition, full welding existence and finite-length/quasicircle removability supply the exact original comparison and QS branch.',
 'ex-quasisymmetric-power-map-on-the-circle':'Direct power and endpoint calculations retained; its extension clause now consumes the completed line/BA/gluing chain.',
 'ex-snowflake-quasicircle':'Original checked Koch geometry/dimension/nonrectifiability argument retained; established bounded-turning characterization and quasicircle removability supply the final two conclusions.',
 'ex-conformal-welding-of-the-round-circle':'Explicit identity welding remains; completed welding Definition, round-circle removability and removable-boundary uniqueness supply the exact comparison.',
 'ex-mobius-ambiguity-in-conformal-welding':'Explicit Mobius action and normalization calculations retained; completed welding Definition, round-circle removability and uniqueness supply the exact additional uses.',
 'cex-every-compact-set-is-conformally-removable':'Direct disk witness remains; completed round-circle and general positive-area lemmas supply the additional asserted cases. The global/local definition equivalence is established under its explicit AC interface.',
 'ex-single-point-conformal-removability':'Existing local bounded-singularity argument remains complete; its use of the global/local compact-removability Definition now consumes the proved AC-conditional equivalence, not an unresolved scope amendment.'}
E={k:ref(rp(k)) for k in ['complex-phase1-handoff.md','complex-phase1-handoff-evidence.json','complex-final-handoff.md','complex-final-handoff-evidence.json','complex-source-resolution-handoff.json','circular-metric-citation-authorization.json','supervision.md']}
scopes={}
for p in pages:
 if p['kind']=='A':
  f=rp('step3a-owner-'+p['id']+'.json');row=json.load(open(f));scopes[p['id']]={**ref(f),'receipt':row,'captured_scope_hash':I['scopes'][p['id']]['current_scope_sha256'],'matches_captured_scope':row['sha256']==I['scopes'][p['id']]['current_scope_sha256']}
subjects=[]
for id,data in ids.items():
 path=Path(rp('step3b-review-'+id+'.json'))
 if not path.exists():continue
 review=json.load(open(path))
 if review['decision']!='escalate':continue
 assert id in C
 item=Path('items')/(id+'.md');raw=item.read_bytes();rawhash=hashbytes(raw);owner=Path(rp('step3b-owner-'+id+'.json'));latest=json.load(open(owner)) if owner.exists() else None
 evidence=['complex-phase1-handoff.md','complex-phase1-handoff-evidence.json'] if data['batch']==12 else ['complex-final-handoff.md','complex-final-handoff-evidence.json']
 if data['batch']==14:evidence+=['complex-phase1-handoff.md']
 if id in ['lem-zero-length-sets-are-removable-for-continuous-analytic-functions','def-quasicircle']:evidence+=['complex-source-resolution-handoff.json']
 if id=='lem-circular-dilatation-quasisymmetry-and-analytic-quasiconformality':evidence+=['circular-metric-citation-authorization.json']
 currentdeps=I['subjects'][id]['declared_dependency_union_for_future_root_examination'];unchanged=rawhash==handoff[id]['sha256']
 subjects.append({'id':id,'current_batch':data['batch'],'current_page':data['page'],'original_escalation':{**ref(path),'receipt':review},'latest_ordinary_item_owner_receipt':({'evidence':ref(owner),'receipt':latest} if latest else None),'point_in_time_item':{'path':str(item),'raw_sha256':rawhash,'read_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'matches_completed_reviewed_handoff_bytes':unchanged,'input_sha256_capture':I['subjects'][id]['current_input_sha256'],'input_capture_boundary':I['boundary']},'completed_repair_and_review':{'same_reviewer':'/root/complex_page_structure_repair','description':C[id],'proof_steps_present':re.findall(r'^(\d+\.\d+)\b',raw.decode(),re.M),'source_owner_evidence':[E[k] for k in evidence],'root_review_evidence':scopes[data['page'] if data['page'] in scopes else next(p['id'] for p in pages if p['kind']=='A' and p.get('companion')==data['page'])]},'current_declared_dependencies_for_future_root_examination':currentdeps,'completed_component_supplier_interfaces':[d for d in currentdeps if d in ids],'remaining_mathematical_gap':None if unchanged else {'finding':'Current item bytes differ from completed reviewed handoff; proposal does not attest the new native edits.','smallest_missing_action':'Source owner/root must inspect exact difference after native drain.'},'claim_change_impacts':{'subject_claim_changed_in_completed_repair':id in changed,'applicable_changed_supplier_claims':sorted(set(currentdeps)&changed),'closed_in_completed_source_owner_review':unchanged,'evidence':[E['complex-phase1-handoff-evidence.json'],E['complex-final-handoff-evidence.json']]},'proposal':{'ordinary_decision':'repaired' if unchanged else 'held','reason':C[id],'certification_boundary':'Ordinary completed-mathematics closure only; no native provenance/origin audit, independent native audit, stable384 pass or gate claim.'}})
# Derive exact downstream impacts in current frontier, preserving all subjects.
impact=[]
for supplier in sorted(changed):
 direct=sorted(id for id,deps in graph.items() if supplier in deps);seen=set(direct);queue=list(direct)
 while queue:
  target=queue.pop()
  for id,deps in graph.items():
   if target in deps and id not in seen:seen.add(id);queue.append(id)
 outside=sorted(seen-set(ids));impact.append({'supplier':supplier,'direct_frontier_consumers':direct,'indirect_frontier_consumers':sorted(seen-set(direct)),'outside_owned_component':outside,'closed_by_existing_completed_component_evidence':not outside,'review_evidence':[E['complex-phase1-handoff-evidence.json'],E['complex-final-handoff-evidence.json']],'remaining_gap':None if not outside else 'Outside-component affected consumer review not attested by this task.'})
# Fresh last-read check detects writers touching subjects while this proposal is assembled.
drift=[]
for row in subjects:
 last=hashbytes(Path(row['point_in_time_item']['path']).read_bytes());row['point_in_time_item']['raw_sha256_at_last_check']=last
 if last!=row['point_in_time_item']['raw_sha256']:
  drift.append(row['id']);row['remaining_mathematical_gap']={'finding':'Native writer changed carrier during capture; previous completed review remains historical evidence.','smallest_missing_action':'Reconcile exact current diff after native drain.'};row['proposal']['ordinary_decision']='held'
core=rp('step3b-owner-lem-analytic-quasiconformality-implies-quadrilateral-modulus-bounds.json')
proposal={'version':1,'run':R,'purpose':'Evidence-only proposal to close actual original complex12/13/14 ordinary escalations using completed same-reviewer repairs/root reviews. Not a receipt, certification, gate or new mathematical repair round.','writer':'/root/complex_page_structure_repair','capture_started_at_utc':started,'capture_finished_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'native_writer_boundary':'Root reports resumed native13/14 after DeepSeek top-up. Hashes are point-in-time only; final ordinary records/current input hashes and384 stable certification must await all writers drain.','original_escalated_subject_count':len(subjects),'subjects_by_current_batch':{str(b):sum(x['current_batch']==b for x in subjects) for b in [12,13,14]},'scope_owner_evidence':scopes,'new_core_support':{'id':'lem-analytic-quasiconformality-implies-quadrilateral-modulus-bounds','ordinary_owner_receipt':ref(core),'receipt':json.load(open(core)),'current_raw_sha256':hashbytes(Path('items/lem-analytic-quasiconformality-implies-quadrilateral-modulus-bounds.md').read_bytes()),'not_an_original_escalated_subject':True},'subjects':subjects,'changed_claim_impact_closure':impact,'drift_during_capture':drift,'genuine_operational_holds_separate_from_mathematical_gaps':['Genuine native13 postbaseline postcomposition-addition provenance refresh and current-input native audit','Genuine native14 late-energy-addition provenance refresh and current-input native audit','All native writers must drain before root stable384 recertification/gate'],'native_additions_not_reclassified':['lem-local-postcomposition-chain-rule-for-w-one-two','lem-quasiconformal-local-jacobian-energy-bound'],'source_read_boundary':'Existing evidence only: complete Gehring1967 paper read but proof deferred elsewhere; exact qualitative citation authorization only. Gehring1960 original and Garnett chapter unread. Source-only Garnett/Martin drops retain original attempts/claims and complete local alternatives. This task conducted no new mathematical/source proof review.','writes':'This distinct proposal/build/input-capture research artifacts only. No items/shared carrier/runtime/receipt/certificate/native evidence writes.'}
Path(rp('complex-escalation-closure-proposal.json')).write_text(json.dumps(proposal,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'subjects':len(subjects),'batches':proposal['subjects_by_current_batch'],'mathematical_holds':[x['id'] for x in subjects if x['remaining_mathematical_gap']],'outside_claim_impacts':[x for x in impact if x['outside_owned_component']],'scope_receipts_match':{k:v['matches_captured_scope'] for k,v in scopes.items()}},indent=2))
