import pathlib,json,copy
D=pathlib.Path('research/frontier-40-geometry-braids-rep-27-owner-arithmetic-models');f=pathlib.Path('research/frontier-40-geometry-braids-rep-27-batch-27.pages.json');p=json.loads(f.read_text());by={x['id']:x for pg in p for x in pg['items']}
template=by['lem-abelian-scheme-base-change-and-products'];source={'title':'Bosch, Lutkebohmert, Raynaud, Neron Models (1990), 7.3/2–3 and 7.4/5; full local proof routes in owner-arithmetic-models/etale-source/closure-packet.md','url':'https://www.math.stonybrook.edu/~kamenova/homepage_files/Bosch_Raynaud_Neron_Model_tc.pdf'}
def add(id,kind,title,statement,deps):
 x=copy.deepcopy(template);x.update(id=id,kind=kind,title=title,statement=statement,deps=list(dict.fromkeys(['def-axiom-of-choice','def-dependent-choice']+deps)),sources={'references':[source]},local_addition=True);p[0]['items'].append(x);by[id]=x
add('def-arith-tate-module-and-inertia','definition','Prime-to-residue-characteristic Tate modules and inertia',r'''Let A/K be an abelian variety, fix a separable closure K^sep, and let ell≠char K be prime. Define T_ell(A)=lim_{v≥1} A[ell^v](K^sep) with transition maps multiplication by ell, and Z_ell=lim Z/ell^v with the usual reduction transitions. Thus an element is a sequence a_v with ell a_{v+1}=a_v; coordinatewise scalar multiplication gives the Z_ell-module structure. Give this group the subspace topology from the product of the finite discrete torsion groups. Galois acts coordinatewise. For a DVR R with fraction field K and a chosen strict henselization R^sh embedded via its fraction field K^sh⊂K^sep, the inertia group is I=Gal(K^sep/K^sh). The Tate module is unramified at R if I acts trivially. This definition specifies the action and the test; no freeness or reduction criterion is assumed.''',['def-abelian-variety-over-a-field','def-inverse-limit-topology-for-finite-discrete-groups','def-profinite-group-by-inverse-limit','def-inverse-system-and-inverse-limit-of-modules','lem-arith-strict-henselization-and-smooth-sections','thm-nonaffine-abelian-multiplication-finite-faithfully-flat'])
by['def-arith-tate-module-and-inertia']['provenance']['proof']='not-applicable'
pkt=json.loads((D/'etale-source/closure-packet.json').read_text()); helpers=pkt['helpers']
extras={
helpers[0]['id']:['def-henselian-pair-and-henselian-local-ring','lem-arith-strict-henselization-and-smooth-sections'],
helpers[1]['id']:[helpers[0]['id'],'def-group-scheme-over-a-scheme','def-smooth-morphism-schemes','thm-differentials-smooth-locally-free'],
helpers[2]['id']:[helpers[1]['id'],'def-arith-tate-module-and-inertia','thm-fundamental-theorem-of-finite-abelian-groups-elementary-divisor-form','thm-existence-of-separable-closures'],
helpers[3]['id']:['lem-nonaffine-connected-group-geometrically-connected','cor-weak-nullstellensatz-algebraically-closed-coordinate-form','thm-affine-domain-dimension-transcendence-degree'],
helpers[4]['id']:[helpers[2]['id'],helpers[3]['id'],'thm-barsotti-chevalley-perfect-field-group-variety','lem-nonaffine-geometric-properness-field-descent'],
helpers[5]['id']:['lem-arith-group-model-with-abelian-generic-fibre-quasiprojective','thm-completion-as-extension-of-scalars','thm-faithfully-flat-ring-map-characterisations','thm-flatness-of-noetherian-completion','lem-projective-coherent-cohomology-finite-and-vanishing','thm-global-functions-proper-integral-variety','thm-over-a-pid-flat-is-equivalent-to-torsion-free','cor-dvr-is-a-pid','lem-proper-source-to-separated-target-proper'],
helpers[6]['id']:[helpers[0]['id'],helpers[1]['id'],helpers[2]['id'],'def-abelian-scheme','lem-multiplication-by-n-on-abelian-scheme'],
helpers[7]['id']:[helpers[0]['id'],helpers[1]['id'],helpers[2]['id'],helpers[4]['id'],helpers[5]['id'],helpers[6]['id'],'thm-neron-model-existence-in-stated-class','lem-neron-model-uniqueness-etale-base-change-and-local-nature','thm-abelian-scheme-is-the-neron-model-of-its-generic-fibre','def-good-reduction-and-abelian-scheme-model','lem-arith-smooth-group-identity-component-open']}
for h in helpers:
 deps=h.get('candidate_exact_existing_deps',[])+extras[h['id']]
 deps=[d for d in deps if d!='lem-affine-algebraic-group-faithful-rational-representation' and d!='thm-quasi-finite-algebra-open-finite-factorization']
 stmt='Assume AC and DC as inherited from the stated suppliers. '+h['statement']+' Proof strategy: '+h['strategy_and_source_evidence']
 # Source packet contains a tentative extra-supplier line; the exact actual dependency list above governs.
 add(h['id'],'theorem' if h['id'].startswith('thm-') else 'lemma',h['id'].replace('lem-arith-','').replace('thm-arith-','').replace('-',' ').capitalize(),stmt,deps)
x=by['thm-good-reduction-and-smooth-proper-base-change'];s=x['statement'];s=s[:s.index('The commissioned smooth-proper')]+r'''(e) [prime-to-residue-characteristic etale good reduction] Locally let R be a DVR, K its fraction field and k its residue field, A_K an abelian variety and ell a prime different from char k. Then A_K has good reduction over R if and only if inertia acts trivially on T_ell(A_K), equivalently on A_K[ell^v](K^sep) for every v≥1. This is the Neron-Ogg-Shafarevich criterion, proved by the finite-etale torsion, affine torsion-growth and Neron properness route supplied locally. For an abelian scheme model the finite etale schemes A[ell^v] commute with every base change and specialize over a strict henselization to the special geometric torsion, preserving rank ell^{2gv}. The coherent cohomology clauses above and this etale good-reduction clause are both retained; no all-degree smooth-proper etale cohomology theorem is claimed by this finite-torsion route.''';x['statement']=s;x['deps']+=[helpers[7]['id'],helpers[6]['id'],'def-arith-tate-module-and-inertia']
f.write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('added9 etale/Tate scaffolds; awaiting exact Neron suppliers')
