import json,pathlib,copy,re
D=pathlib.Path('research/frontier-40-geometry-braids-rep-27-owner-arithmetic-models');f=pathlib.Path('research/frontier-40-geometry-braids-rep-27-batch-27.pages.json');p=json.loads(f.read_text());by={x['id']:x for pg in p for x in pg['items']}; template=by['lem-abelian-scheme-base-change-and-products']; pkt=json.loads((D/'neron-source/packet.json').read_text());nodes={n['code']:n for n in pkt['nodes']};text=(D/'neron-source/closure-supplement.md').read_text(); sections={}
for m in re.finditer(r'^### (.+?)\n(.*?)(?=^### |^## |\Z)',text,re.M|re.S):sections[m.group(1)]=m.group(2).strip()
def sec(key):return next(v for k,v in sections.items() if key in k)
source={'title':'Bosch, Lutkebohmert, Raynaud, Neron Models (1990), Chapters2–6; exact source/local proof closure in owner-arithmetic-models/neron-source/closure-supplement.md','url':'https://www.math.stonybrook.edu/~kamenova/homepage_files/Bosch_Raynaud_Neron_Model_tc.pdf'}
def add(id,title,claim,proof,deps):
 x=copy.deepcopy(template);x.update(id=id,title=title,kind='lemma',statement='Assume AC and DC as inherited from the supplied algebra and scheme results. '+claim+' Complete proof strategy: '+proof,deps=list(dict.fromkeys(['def-axiom-of-choice','def-dependent-choice']+deps)),sources={'references':[source]},local_addition=True);p[0]['items'].append(x);by[id]=x
regular=['lem-ag-flat-local-regularity-ascent-descent','thm-ag-standard-smooth-geometric-regularity','thm-nonaffine-regular-local-ring-is-ufd','thm-line-bundle-rational-section-cartier-divisor','lem-normal-noetherian-domain-intersection-of-height-one-localizations','lem-scheme-zariski-main-factorization-quasi-finite']
domain=['def-s-dense-open-and-s-rational-map','lem-s-rational-map-descends-along-faithfully-flat-smooth-maps','lem-nonaffine-fppf-descent-of-scheme-morphisms','cor-morphisms-equal-on-dense-open-reduced-source']
add('lem-arith-strict-henselization-and-smooth-sections','Strict henselization of a DVR and smooth sections',nodes['F01']['claim'],sec('F01'),['def-henselian-pair-and-henselian-local-ring','thm-etale-locally-standard-etale','thm-jacobian-criterion-smooth-morphism','thm-one-dimensional-regular-local-rings-are-dvrs','thm-filtered-colimits-of-flat-modules-are-flat','thm-faithfully-flat-ring-map-characterisations','lem-nonempty-smooth-scheme-finite-separable-point'])
add('lem-arith-smooth-group-identity-component-open','The identity model of a smooth group with abelian generic fibre',r'''Let R be a DVR and G/R a smooth separated finite-type group scheme with abelian generic fibre. Then G^0=G_K∪(G_k)^0 is an open subgroup scheme, smooth separated finite type with geometrically connected fibres. On each geometric fibre its orbits on G are exactly the connected components.''',sec('F14–F15').split('For smooth G')[1].join(['For smooth G','']),['def-group-scheme-over-a-scheme','def-abelian-variety-over-a-field','lem-nonaffine-connected-group-geometrically-connected','def-locally-noetherian-and-noetherian-scheme'])
ids={'N01':'lem-arith-dilatations-and-defect-of-smoothness','N02':'lem-arith-finite-permissible-smoothening','N03':'lem-arith-projective-weak-model-and-rational-mapping','N04':'lem-arith-invariant-volume-and-finite-minimal-models','N05':'lem-arith-separated-minimal-model-and-translations','N06':'lem-arith-birational-group-law-from-minimal-model','N07':'lem-arith-strictification-of-dvr-birational-group-law','N08':'lem-arith-strict-law-translation-and-graph-calculus','N09':'lem-arith-separated-translate-gluing','N10':'lem-arith-finite-translate-group-completion','N11':'lem-arith-affine-codimension-one-neighbourhood-and-divisors','N12':'lem-arith-cube-derived-square-over-dvr','N13':'lem-arith-group-model-with-abelian-generic-fibre-quasiprojective','N14':'lem-arith-effective-ample-pair-and-group-descent','N15':'thm-weil-extension-rational-map-into-group-scheme','N16':'lem-arith-full-minimal-model-embedding'}
extra={
'N01':(['thm-affine-blowup-standard-charts','lem-affine-blowup-algebra-properties','thm-blowup-projective','thm-valuative-criterion-properness','lem-local-fibre-dimension-bound-via-polynomial-quasifiniteness','thm-etale-formally-etale-finite-presentation','thm-differentials-smooth-locally-free','thm-jacobian-criterion-smooth-morphism','thm-over-a-pid-flat-is-equivalent-to-torsion-free','cor-dvr-is-a-pid']+regular,sec('F05–F06')+' '+sec('F08–F09')),
'N02':(['lem-generic-freeness-finite-type-algebra-module','thm-ag-separating-transcendence-basis-perfect-field','thm-ag-field-differentials-separable-rank','lem-ag-geometric-regularity-field-tests'],sec('F07')),
'N03':(['lem-arith-strict-henselization-and-smooth-sections','thm-abelian-variety-is-projective','thm-valuative-criterion-properness','lem-schematic-closure-and-dense-agreement','thm-prime-filtration-of-a-finite-module','thm-existence-of-associated-primes','thm-associated-primes-in-a-short-exact-sequence','thm-filtered-colimits-exact-modules','lem-finite-presentation-image-constructible']+domain,sec('F02')+' '+sec('F08–F09')+' '+text.split('## Universal density and strictification refinements')[1].split('For the closure of the bad locus')[0]),
'N04':(regular+['thm-differentials-smooth-locally-free','thm-etale-formally-etale-finite-presentation'],sec('F03–F04')),
'N05':(['lem-schematic-closure-and-dense-agreement']+domain,sec('F08–F09')),
'N06':(domain,''),
'N07':(['lem-local-fibre-dimension-bound-via-polynomial-quasifiniteness','lem-finite-presentation-image-constructible','lem-constructible-dense-contains-open']+domain,sec('F13')+' '+text.split('For the closure of the bad locus in strictification')[1]),
'N08':(domain+['lem-scheme-zariski-main-factorization-quasi-finite'],''),
'N09':(domain+['thm-gluing-schemes-along-open-subschemes'],''),
'N10':(['lem-arith-strict-henselization-and-smooth-sections']+domain,''),
'N11':(regular+['thm-valuative-criterion-properness','thm-prime-avoidance-finite'],sec('F10')+' '+sec('F14–F15').split('For smooth G')[0]),
'N12':(['lem-arith-smooth-group-identity-component-open','lem-theorem-of-the-square-and-mumford-homomorphism','lem-nonaffine-theorem-of-the-cube-for-abelian-variety']+regular,text.split('## Two construction details that must remain explicit')[1].split('In Weil extension')[0]),
'N13':(['lem-arith-strict-henselization-and-smooth-sections','def-ample-invertible-sheaf','thm-serre-criterion-ampleness','thm-faithfully-flat-descent-vanishing','thm-ample-powers-very-ample-proper-base'],sec('F11–F12').split('For effective descent')[0]),
'N14':(['lem-nonaffine-effective-affine-algebra-descent','lem-fpqc-cover-submersive','lem-faithfully-flat-effective-descent-of-modules-and-algebras','lem-fpqc-descent-properness-components','thm-faithfully-flat-descent-of-flatness','lem-ag-geometric-regularity-field-tests']+domain,sec('F11–F12').split('For effective descent')[1].join(['For effective descent',''])),
'N16':(regular+domain,'')}
for row in pkt['reduced_authoring_packets']:
 lab=row['label']
 if lab in ['N15','original']:continue
 parts=[nodes[c] for c in row['includes']]; claim=' '.join(n['claim'] for n in parts);proof=' '.join(n['proof_strategy']+' Source locator: '+n.get('reading',n.get('source_locator','BLR source packet'))+'.' for n in parts)
 deps=[ids[z] for z in row['earlier_labels']]+extra[lab][0]
 if lab=='N11':deps.remove(ids['N04']) # Pure local affine-neighbourhood lemma requires no minimal-model machinery.
 if lab=='N12':deps.remove(ids['N10']) # Conditional square theorem is independent of constructing a group completion.
 if lab=='N13':
  claim+=r''' In particular every such smooth separated finite-type R-group scheme H with abelian generic fibre is quasi-projective over R: choose the R-dense affine open supplied by the codimension-one neighbourhood lemma, take its effective horizontal Cartier boundary D, and O(D) is ample by the orbit/square argument. The ample-powers/projective-immersion supplier gives a locally closed projective-space embedding.'''
 add(ids[lab],row['title'],claim,proof+' '+extra[lab][1],deps)
x=by['thm-neron-model-existence-in-stated-class'];x['statement']=r'''Assume AC and DC. Let R be an arbitrary DVR, with fraction field K and residue field k, and let A_K be an abelian variety over K. There exists a smooth separated finite-type R-group scheme N with generic fibre A_K such that for every smooth R-scheme Z restriction Hom_R(Z,N)→Hom_K(Z_K,A_K) is bijective. N is unique up to unique isomorphism inducing the given generic-fibre identity. No excellence, completeness, perfect-residue-field or reduction-type hypothesis is imposed. Complete proof strategy: '''+' '.join(nodes[c]['proof_strategy'] for c in ['P24','P25'])+' The locally ordered helper DAG supplies projective weak models, finite smoothening, invariant-volume minimal models, birational-law strictification, graph/translation completion over the strict henselization, an ample stable-open descent, full original-model embedding and regular-DVR Weil extension. The weak-model construction uses proper projective closure, so BLR general bounded-model or Artin-approximation branches are unnecessary. Relative rational maps are over R; the final universal-translation argument does not assert that an R-rational map is automatically Z-rational. On Z×_R N extend generic translation, apply the regular-base Weil theorem over R, then evaluate at the unit. All auxiliary field and scheme arguments are detailed in the exact current supplier packet and closure supplement.'
x['deps']=['def-axiom-of-choice','def-dependent-choice','def-neron-model-and-mapping-property','def-discrete-valuation-ring',ids['N05'],ids['N15'],ids['N16'],'lem-neron-model-uniqueness-etale-base-change-and-local-nature']
f.write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('added17 Neron/common helpers, reusing original Weil')
