import {readFileSync,writeFileSync,appendFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {itemHashGuard,itemSurfaceHash} from '../../tools/item-hash.mjs';
import {recordedPublishedRepair} from '../../tools/published-repair-policy.mjs';
const d='research/frontier-42-coxeter-32-codex-step6-a-external-definitions',run='frontier-42-coxeter-32',map=JSON.parse(readFileSync(d+'/consumer-map.before.json','utf8')),guards=JSON.parse(readFileSync(d+'/guards.before.json','utf8')),snapshot=readFileSync(d+'/direct-consumers.fulltext.before.txt','utf8'),sha=s=>createHash('sha256').update(s).digest('hex');
const beforeTexts=new Map(snapshot.split('\nFILE ').slice(1).map(s=>{const n=s.indexOf('\n');return[s.slice(0,n),s.slice(n+1).replace(/\n$/,'')];}));
const changed=['def-free-module-on-a-set-and-standard-basis','lem-graded-degreewise-direct-sums-and-homogeneous-free-covers','def-simple-module','thm-schurs-lemma-for-modules','thm-matrix-rings-over-division-rings-are-semisimple'];
const frontier=new Set(JSON.parse(readFileSync(d+'/frontier-direct-ids.json','utf8')));
const override={
 'lem-graded-degreewise-direct-sums-and-homogeneous-free-covers':'Original L4 repeats arbitrary-ring inclusion; corrected to indexed family and canonical map. Proof 1.2 uses only the singleton generator/universal extension; 3.3 uses summand assembly. For A=0 all unital modules X=0, H_X empty, so the cover remains valid. Statement and Proof byte-identical.',
 'ex-unit-and-counit-of-the-free-vector-space-adjunction':'F1 uses an inclusion over a field k, where 1 is nonzero, so distinct indices give distinct vectors. Unit/counit formulas need only coordinates. No repair.',
 'thm-universal-property-of-free-modules':'F1 and Proof 1.1–5.1 use indexed summands, unique coefficient families and e_x=j_x(1). For the zero ring unital M=0 since m=1m=0m=0, so every X→M and its linear extension are uniquely zero. No injectivity of X→R^(X) is used. No repair.',
 'lem-hh-free-associative-ring-and-relations-descent':'F3 and word multiplication use indexed finite-word coefficients, extension from a family and the empty word. The zero ring produces the zero algebra and the same universal property; no injectivity assertion is required. No repair.',
 'lem-hh-finite-polynomial-and-localization-constructions':'F6 uses indexed polynomial/Laurent monomial coefficients, F7 linear extension. Domain and fraction-field clauses explicitly require an integral domain (1≠0); arbitrary commutative-ring free-module clauses need no index injection. No repair.',
 'lem-hh-universal-presentations-and-base-change':'F6 supplies coordinate-family extensions and basis transport via mutually inverse module maps. Arbitrary base change includes zero rings without requiring distinct basis-vector images; all coefficients then zero. No repair.',
 'lem-hh-commuting-left-right-hecke-length-operators':'F2/F6 and operator comparisons use the W-indexed family in E=R^(W), unique coefficients and equality of linear maps on it. No injection W→E is used; over the zero ring all maps and coefficients are zero. No repair.',
 'thm-hh-generic-coxeter-hecke-standard-basis':'F4 extracts indexed coefficients from a relation after evaluation at e_1. This remains valid over the zero ring because all a_w=0; injectivity of the representation is a map of zero modules there. F6 transports a basis family. No repair.',
 'cex-hh-infinite-dimensional-tensor-dual-identification-fails':'Given fixes a field k and infinite I; F1 uses the indexed family, F2 product basis, F3 coordinate duals, and the refutation uses their independence. A field is nonzero, so all needed distinctness is sound. No repair.',
 'lem-hh-finite-matrix-and-module-preliminaries':'F1 supplies finite indexed coordinates, including n=0. Proof 1.1, 2.1 and 3.1 use a coordinate right inverse and determinant; no basis-index injection is needed. Proof 2.3 and 3.3 form each N_{i-1}/N_i with N_i strictly proper in nonzero N_{i-1}, hence each simple factor is nonzero. Proof 1.4, 2.4 and 3.4 use each S_i simple and nonzero and the zero-or-whole intersection property. No repair.',
 'thm-schurs-lemma-for-modules':'Original L1 repeats the false equivalence; corrected to M≠0 and no proper nonzero submodule. The Statement already assumes simple modules, and Proof 1.1–4.1 uses their full nonzero zero-or-whole condition. Statement and Proof byte-identical.',
 'thm-matrix-rings-over-division-rings-are-semisimple':'Original L5 repeats the false equivalence; corrected to M≠0 and no proper nonzero submodule. Given D is a division ring and n≥1, so column modules D^n are nonzero; Proof 3.1 proves every nonzero submodule is all. Statement and Proof byte-identical.',
 'prop-normal-p-subgroups-act-trivially-on-simple-modules':'F1 is the valid implication simple⇒no proper nonzero submodule; it does not assert the converse. Proof 1.1 chooses T nonzero explicitly before concluding simplicity; Proof 3.1 has S simple from Given and S^N nonzero. The defective equivalence is not used. No repair.',
 'cex-a-deligne-kernel-need-not-be-one-external-tensor-factor':'Statement and F1 use simplicity only for a one-dimensional module over a field, which is nonzero. Zero a or b cannot realize the nonzero three-dimensional regular bimodule. No use of the false zero-module converse. No repair.',
 'def-composition-series-and-length-of-a-module':'Simple factors occur in a strict chain, hence are nonzero; the zero module is explicitly assigned the empty series. The malformed converse is not used. No repair.',
 'def-semisimple-module':'Internal direct sums of simple submodules use the original full simple definition; the empty sum explicitly includes the semisimple zero module without calling it simple. No repair.',
 'def-socle-of-a-module':'The sum ranges over simple submodules in the original full definition; no-simple-submodule case is explicitly zero. No false characterization of zero as simple. No repair.',
 'def-exterior-algebra-of-a-finite-free-module':'Metadata dependency only; the Definition uses an ordered finite indexed basis to form exterior monomials. No standard-map inclusion assertion. No repair.'};
const impacts=map.report.map(r=>({supplier:r.id,original_definition_changed:true,direct_edges:r.consumers.map(c=>{const original=beforeTexts.get(c.file);if(!original)throw Error(c.file);const current=readFileSync(c.file,'utf8');const paras=original.split(/\n\s*\n/);const uses=paras.filter(p=>p.includes('[['+r.id));const given=paras.filter(p=>p.includes('**Given:**'));let review=override[c.id];if(!review){if(r.id.startsWith('def-free-'))review='Actual cited/declared use is the finite-support coordinate construction, generation, direct-sum decomposition, or extension of maps on an indexed basis family. The reviewed Statement/Definition and Given retain that family or a nonzero coefficient setting (integers, field, or PID) whenever distinct vectors are needed. They make no arbitrary-ring basis-map inclusion claim. No repair.';else review='The reviewed Definition/Statement and Given use the full nonzero simple-module notion. Cited facts either state nonzero explicitly, retain simple as a hypothesis, or use a positive-dimensional/strict quotient witness when proving simplicity. No conclusion declares the zero module simple solely for lacking a proper nonzero submodule. No repair.';}return{...c,status:changed.includes(c.id)?'surgical-fact-correction-closed':'reviewed-no-change',frontier:frontier.has(c.id),actual_original_cited_passages:uses,actual_original_given:given,review,original_content_sha256:guards[c.file].content,current_content_sha256:itemHashGuard(current),statement_definition_changed:changed.includes(c.id)?false:undefined};}),homes:r.homes.map(file=>({file,review:'Placement and page prose read; no faulty mathematical equivalence or arbitrary-ring inclusion assertion; unchanged.'})),page_prose_links:r.pageLinks}));
const policy=changed.map(id=>({id,...recordedPublishedRepair(process.cwd(),id,readFileSync('items/'+id+'.md','utf8'),`${d}/${id}.receipt.json`)}));if(policy.some(x=>!x.ok))throw Error(JSON.stringify(policy));
const guardReport={changed:[],unchanged:[],fact_carrier_surfaces:[],all_policies:policy};
for(const [file,before] of Object.entries(guards)){const t=readFileSync(file,'utf8'),now={raw:sha(t),content:itemHashGuard(t),surface:itemSurfaceHash(t)};if(before.raw===now.raw)guardReport.unchanged.push(file);else{if(!changed.some(id=>file==='items/'+id+'.md'))throw Error('unexpected writer '+file);guardReport.changed.push({file,before,current:now});}}
for(const id of changed.filter(x=>!x.startsWith('def-'))){const before=readFileSync(`${d}/${id}.before.md`,'utf8'),now=readFileSync('items/'+id+'.md','utf8');const section=(s,name)=>new RegExp('^## '+name+'\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))','m').exec(s)?.[1]??null;const row={id,statement_unchanged:section(before,'Statement')===section(now,'Statement'),proof_unchanged:section(before,'Proof')===section(now,'Proof')};if(!row.statement_unchanged||!row.proof_unchanged)throw Error(id);guardReport.fact_carrier_surfaces.push(row);}
writeFileSync(d+'/consumer-impact.json',JSON.stringify({run,reviewer:'Codex owner repair agent step6_a_external_definitions_repair',classification:'confirmed-definition-defects; frontier-claims-preserved',native_alerts:JSON.parse(readFileSync(d+'/native-context.before.json','utf8')).alerts,edge_count:86,unique_consumers:new Set(impacts.flatMap(r=>r.direct_edges.map(c=>c.id))).size,review_scope:'Entire items/library reverse deps, justified_by, external_refs, forward_refs and wikilinks resolved by tools/consumers.mjs; complete supplier-citing passages plus original Statements/Definitions/Givens and pertinent proof uses reviewed. Phrase search checks inclusion/equivalence formulations beyond named edges.',further_propagation:'No consumer original Statement/Definition changed; three copied Facts corrected; no further hop triggered.',impacts},null,2)+'\n');
writeFileSync(d+'/guards.current.json',JSON.stringify(guardReport,null,2)+'\n');console.log({edges:86,unique:new Set(impacts.flatMap(r=>r.direct_edges.map(c=>c.id))).size,changed:guardReport.changed.map(x=>x.file),unchanged:guardReport.unchanged.length,all_policies:policy.map(x=>[x.id,x.ok])});
