import json,pathlib
r='frontier-40-geometry-braids-rep-27';base=pathlib.Path('research')/f'{r}-owner-surface-resolution';packet=json.loads((base/'normal-completion-sources/helper-packet.json').read_text());p=pathlib.Path('research')/f'{r}-batch-25.pages.json';a=json.loads(p.read_text())
statements={
'lem-surface-p-basis-subfield-separation':r'''Assume AC. Let $k$ have characteristic $p>0$, $A=k[[X_1,\ldots,X_n]][Y_1,\ldots,Y_m]$ and $K=\operatorname{Frac}A$. Choose a possibly infinite $p$-basis $(b_i)_{i\in I}$ of $k/k^p$, meaning its restricted monomials of finite support form a $k^p$-basis. For finite $J\subset I$ put $k_J=k^p(b_i:i\notin J)$, $A_J=k_J[[X_1^p,\ldots,X_n^p]][Y_1^p,\ldots,Y_m^p]$ and $K_J=\operatorname{Frac}A_J$. Then $A$ is finite free over $A_J$, the family $(K_J)$ is downward directed with intersection $K^p$, and for every finite field extension $L/K$, $\bigcap_J L^pK_J=L^p$.''',
'lem-surface-non-pth-power-detected-by-derivation':r'''Assume AC. Let $B$ be a domain of characteristic $p>0$ finite type over a complete equicharacteristic Noetherian local ring, and let $f\in B$ not be a $p$th power in $\operatorname{Frac}B$. There is a derivation $D:B\to B$ with $D(f)\ne0$.''',
'lem-surface-derivations-and-regular-hypersurfaces':r'''Assume AC. Derivations of Noetherian rings extend uniquely through localization and adic completion. If $T$ is regular Noetherian, $D:T\to T$ a derivation and $D(f)$ a unit, then $T[z]/(z^r-f)$ is regular for every $r\ge1$.''',
'lem-surface-finite-completion-factors':r'''Assume AC. For a finite map $R\to S$ of Noetherian rings and $\mathfrak p\in\operatorname{Spec}R$, $\widehat{R_{\mathfrak p}}\otimes_RS\cong\prod_{\mathfrak q\cap R=\mathfrak p}\widehat{S_{\mathfrak q}}$. The finitely many factors use their maximal-adic completions. Thus formal fibres for finite extensions are factors of residue-field base changes of the original formal fibres.''',
'lem-surface-geometric-regularity-field-test-and-generic-spread':r'''Assume AC. For a Noetherian $k$-algebra $T$, call $T$ geometrically regular if $T\otimes_kE$ is regular for every finitely generated field extension $E/k$. It suffices to test finite purely inseparable $E/k$. Geometric regularity is stable under finitely generated field extension. If $K/k$ is finitely generated, finite purely inseparable enlargements $K'/K$ and $k'/k$ make $K'/k'$ separably generated. A separably generated generic fraction-field extension of finite-type domains spreads to a nonempty standard smooth open after localizing the base and source.''',
'lem-surface-generic-power-series-formal-fibres':r'''Assume AC. For $A=k[[X_1,\ldots,X_n]][Y_1,\ldots,Y_m]$ and $K=\operatorname{Frac}A$, every completed local generic fibre $\widehat{A_{\mathfrak p}}\otimes_AK$ is geometrically regular over $K$.''',
'lem-surface-complete-equicharacteristic-formal-fibres':r'''Assume AC. For a complete equicharacteristic Noetherian local ring $A$ and primes $\mathfrak q\subseteq\mathfrak p$, the formal fibre $\widehat{A_{\mathfrak p}}\otimes_A\kappa(\mathfrak q)$ is geometrically regular over $\kappa(\mathfrak q)$.''',
'lem-surface-completed-polynomial-generic-fibre':r'''Assume AC. Let $A$ be a complete equicharacteristic Noetherian local domain, let $\mathfrak q$ be maximal in $A[t]$ over its closed point, and let $0\ne\mathfrak r\subset\mathfrak q$ have $\mathfrak r\cap A=0$. Then $\widehat{A[t]_{\mathfrak q}}\otimes_{A[t]}\kappa(\mathfrak r)$ is geometrically regular over $\kappa(\mathfrak r)$.''',
'lem-surface-finite-type-formal-fibres':r'''Assume AC and DC. Let $A$ be a field or a complete equicharacteristic Noetherian local ring and $B$ an essentially finite-type $A$-algebra. Every formal fibre of every local ring of $B$ is geometrically regular over its residue fraction field. Equivalently, for primes $\mathfrak q\subseteq\mathfrak p$ of $B$, $\widehat{B_{\mathfrak p}}\otimes_B\kappa(\mathfrak q)$ is geometrically regular.''',
'lem-surface-open-regular-locus':r'''Assume AC and DC. Every finite-type algebra over a field or a complete equicharacteristic Noetherian local ring has open regular locus. Thus the regular locus of any scheme locally of finite type over one of these bases is open.''',
'lem-surface-complete-equicharacteristic-finite-integral-closure':r'''Assume AC. The integral closure of a complete equicharacteristic Noetherian local domain in every finite extension of its fraction field is a finite module.''',
'lem-surface-regular-fibres-preserve-normality':r'''Assume AC and DC. A flat map of Noetherian rings with regular fibres carries normality of the base to normality of the target. Consequently a normal essentially finite-type local ring over a field or complete equicharacteristic Noetherian local base has normal maximal-adic completion, which is a domain.''',
'lem-surface-finite-type-normalization-finite':r'''Assume AC and DC. Every integral finite-type algebra over a field or a complete equicharacteristic Noetherian local base has finite normalization, and so do its localizations. Integral schemes of finite type over these bases consequently have finite scheme normalization.'''
}
for x in packet['rows']:
 deps=sorted(set(x['deps']+['def-axiom-of-choice','def-dependent-choice']))
 proof=x['proof_argument']
 if x['id']=='lem-surface-p-basis-subfield-separation':
  deps += ['def-derivation-algebra','def-kahler-differentials-algebra','def-linear-basis']
  proof=proof.replace('Choose a p-basis b_i of k over k^p by Zorn.','For a possibly infinite family, p-independence means independence of its restricted monomials of finite support. Zorn supplies a maximal such family: its monomial span is a field, since each finite subfamily generates a finite exponent-one extension; any element outside that field would have degree p over it and extend the independent family. Thus maximality gives a p-basis b_i of k over k^p.')
 if x['id']=='lem-surface-non-pth-power-detected-by-derivation':deps += ['def-derivation-algebra','def-kahler-differentials-algebra']
 if x['id']=='lem-surface-open-regular-locus':
  proof=proof.replace('Therefore every finite-type domain over the complete base has a regular open: base change to this finite inseparable subalgebra,','Therefore every finite-type domain S over the complete base has a regular open: choose a finite base subalgebra in k\u2032 and a finite S-subalgebra of K\u2032 with fraction field K\u2032 (multiply its finitely many algebraic field generators by denominators to make them integral). Work on this finite domain extension,')
 if x['id']=='lem-surface-finite-type-normalization-finite':deps += ['thm-integrality-commutes-with-localisation','lem-relative-spec-glues-affine-algebras']
 refs=[{'title':'The Stacks Project: full proof imports for normal-surface resolution, '+', '.join(x['source_evidence']['labels']),'url':x['source_evidence']['url']}]
 row={'id':x['id'],'kind':'lemma','title':x['id'][4:].replace('-',' ').capitalize(),'deps':sorted(set(deps)),'statement':statements[x['id']],'strategy':proof+' Exact source/proof evidence is retained in the normal-completion-sources helper packet; AC and DC inherited from the used suppliers are explicit.','design_row':'AG-BIR-1','local_addition':True,'provenance':{'statement':'literature-derived','proof':'ai-altered'},'sources':{'references':refs},'dependency_level':0}
 idx=next(i for i,y in enumerate(a[0]['items']) if y['id']=='thm-resolution-of-normal-surface-singularities');a[0]['items'].insert(idx,row)
p.write_text(json.dumps(a,indent=2)+'\n')
