import json,pathlib,hashlib,datetime
r='frontier-40-geometry-braids-rep-27';base=pathlib.Path('research');b=base/(r+'-owner-surface-resolution');p=base/(r+'-batch-25.pages.json');a=json.loads(p.read_text());rows={i['id']:i for q in a for i in q['items']}
rem=rows['rem-surface-contraction-and-resolution-scope-boundaries'];rem['statement']=r'''The page's commissioned claims comprise the intrinsic exceptional-curve and contraction definition, universal property and uniqueness of a contraction, the point-blowup direction, negativity of contracted curves, factorization of proper birational morphisms of regular surfaces, and resolution of normal integral finite-type surfaces over every field and characteristic ([[def-exceptional-curve-and-contraction]], [[lem-universal-property-of-a-contraction]], [[lem-blowing-up-a-regular-point-is-a-contraction]], [[thm-negativity-for-exceptional-curves-on-smooth-surfaces]], [[thm-factorization-of-birational-morphisms-of-smooth-surfaces]], [[thm-resolution-of-normal-surface-singularities]]). The surface resolution concludes regularity over an arbitrary field and smoothness only over a perfect field.

The page does not claim Castelnuovo's existence criterion for contracting every exceptional curve on a proper regular surface, negative definiteness of the complete intersection matrix of a reducible exceptional divisor, the arbitrary-Noetherian alteration/resolution equivalence of Stacks 54.14.5, or a resolution theorem in dimension at least three. These are outside the commissioned scope. The corrected local proof of the commissioned surface theorem includes the triple-cubic and stable-cubic square-conic cases, without adding these stronger statements.''';rem['strategy']='Scope accounting from the exact commissioned statements and their declared local proof suppliers.';rem['deps']=sorted(set(rem['deps']+['lem-universal-property-of-a-contraction','lem-blowing-up-a-regular-point-is-a-contraction']))
allrows={}
for f in base.glob(r+'-batch-*.pages.json'):
 for q in json.loads(f.read_text()):
  for i in q['items']:allrows[i['id']]=i
allrows.update(rows);levels={};active=set()
def lev(id):
 if id in levels:return levels[id]
 if id in active:raise ValueError('cycle '+id)
 active.add(id);v=max([lev(d)+1 for d in allrows[id]['deps'] if d in allrows]+[0]);active.remove(id);levels[id]=v;return v
for id,i in rows.items():i['dependency_level']=lev(id)
for q in a:q['items'].sort(key=lambda i:i['dependency_level'])
p.write_text(json.dumps(a,indent=2)+'\n')
cp=base/(r+'-batch-25.coverage.json');cov=json.loads(cp.read_text())
history=[{'page':q['page'],'url':s['url'],'fetch_verified':s.get('fetch_verified'),'recovery_attempts':s.get('recovery_attempts')}for q in cov['pages']for s in q['sources']];(b/'before-square-closure-source-history.json').write_text(json.dumps(history,indent=2)+'\n')
# Preserve earlier fetch objects exactly; update only the mathematical disposition.
for s in cov['pages'][0]['sources']:
 for x in s.get('contents',[]):
  if x.get('item')=='thm-resolution-of-normal-surface-singularities':x['reason']='Commissioned arbitrary-characteristic finite-type normal-surface theorem retained. The corrected Lipman triple-cubic transition and stable fixed-coordinate class close the square-conic proof gap; complete-local induction, normalized-point conversion, completion descent and globalization are explicit local strategies. No arbitrary-Noetherian strengthening or cap assertion is imported.'
 if s['url']=='https://stacks.math.columbia.edu/download/resolve.pdf':s['locator']='Original contraction/factorization ranges and §§54.8–54.12, 54.14 exact proof blocks read as described in owner reports. The omitted square-conic transition is repaired by the full Lipman chart/ideal argument, not accepted from the short source inference.'
newids=['lem-double-plus-simple-cubic-rational-surface-branch-terminates','lem-triple-cubic-rational-surface-branch-reduces-in-two-steps','thm-rational-gorenstein-normal-surface-singularity-resolved-by-point-blowups','lem-complete-normal-surface-regular-resolution-converts-to-normalized-point-blowups','thm-complete-equicharacteristic-normal-surface-resolution-by-normalized-point-blowups']
first=cov['pages'][0]['sources'][0]
for id in newids:first['contents'].append({'name':'Corrected prerequisite proof: '+rows[id]['title'],'disposition':'included','item':id,'reason':'Full local argument with explicit hypotheses in the current manifest and square-conic-closure.md; scaffold readiness is not independent authored-proof acceptance.'})
for stem,title,url,locator,contents in [
 ('lipman-rational','Joseph Lipman, Rational singularities (1969), complete author-hosted paper',rows[newids[0]]['sources']['references'][0]['url'],'§24, printed pp.264–268 (PDF pages70–74): cubic branch arguments, Case IV and exact relations (5)/(5′); extracted text and rendered pages read. No whole-paper reading claim.',[
  {'name':'Nonzero cubic and simple closed-factor successors, pp.264–265','disposition':'inline','item':'lem-square-tangent-conic-blowup-singularities-controlled-by-a-cubic'},
  {'name':'Case IV double-plus-simple cubic, pp.266–267; persistence completed with full chart coefficients','disposition':'included','item':newids[0]},
  {'name':'Relations (5)/(5′) and triple-cubic Case V, pp.267–268; unit alternatives and chart reductions proved locally','disposition':'included','item':newids[1]},
  {'name':'Exceptional intersection/classification diagrams for Cases III–V','disposition':'out-of-scope','reason':'The commissioned theorem needs resolution existence; the proof gives a complete chart-and-arc termination argument and imports none of the additional ADE classification diagrams or intersection claims.'}]),
 ('lipman-desingularization','Joseph Lipman, Desingularization of two-dimensional schemes (1978), complete author-hosted paper',rows[newids[0]]['sources']['references'][1]['url'],'Printed pp.164–174 (PDF pages14–24), embedding-dimension control, Theorem1.25 square cases, relation1.29 and Proposition1.28 fixed-coordinate termination; only these blocks read.',[
  {'name':'Relation (1.29) and finite triple-cubic reduction, pp.171–172','disposition':'included','item':newids[0]},
  {'name':'Proposition1.28 fixed-coordinate quadratic-sequence termination, pp.171–174','disposition':'inline','item':'lem-normal-complete-surface-nonsingular-formal-arc-blowups-terminate'},
  {'name':'Theorem1.25 full pseudo-rational embedding-dimension termination outside the Gorenstein case','disposition':'out-of-scope','reason':'The current route has already reduced to rational Gorenstein points and proves the needed square/nonsquare conic termination locally; no larger embedding-dimension pseudo-rational theorem is commissioned or required here.'}])]:
 f=b/(stem+'.pdf');at=datetime.datetime.fromtimestamp(f.stat().st_mtime,datetime.timezone.utc).isoformat();import fitz;pages=len(fitz.open(f));sha=hashlib.sha256(f.read_bytes()).hexdigest()
 cov['pages'][0]['sources'].append({'title':title,'kind':'paper','url':url,'locator':locator,'contents':contents,'recovery_attempts':[{'url':url,'at':at,'outcome':'full-text author-hosted PDF body fetched by curl -fL --max-time 30; exit 0; text extracted with PyMuPDF'}],'fetch_verified':{'at':at,'bytes':f.stat().st_size,'sha256':sha,'kind':'pdf','pages':pages},'manual_fetch_receipt':'research/'+r+'-owner-surface-resolution/square-conic-source-read.json'})
cp.write_text(json.dumps(cov,indent=2)+'\n')
held=b/'square-conic-held-interface.json';v=json.loads(held.read_text());v['status']='closed-local-scaffold-strategy';v['historical_unproved_part']=v.pop('unproved_part');v['resolution']={'proof':'research/'+r+'-owner-surface-resolution/square-conic-closure.md','proof_sha256':hashlib.sha256((b/'square-conic-closure.md').read_bytes()).hexdigest(),'exact_suppliers':newids[:3],'corrected_invariant':'z²+a xy² ∈ z m²+(x,y)^4, with a a unit','triple_relation':'z²+a y³+ρ x³y+σ x⁵ ∈ (x³z,x²y²,xyz,y²z)','unit_alternative':'Normality of the next rational point blowup forces ρ or σ to be a unit; if only σ is a unit the exact swap X=u,Y=x,Z=v gives new ρ=a a unit.','characteristic_check':'Square and repeated-root coefficient identities are used without division by 2 or 3; closed-factor multiplicity and all chart ideal/order arguments work over arbitrary residue fields.'};v['decision']='The omitted square-conic interface is closed by the complete local Lipman chart/ideal and arc argument. The historical E8 calculation remains valid and is handled by the triple-cubic finite transition. Target readiness is refreshed only after scoped checks; this is not independent authored-proof acceptance.';held.write_text(json.dumps(v,indent=2)+'\n')
# Actual PDF receipts and read extent; earlier recovery histories remain unchanged.
receipts=[]
for stem in ['lipman-rational','lipman-desingularization']:
 f=b/(stem+'.pdf');receipts.append({'file':str(f),'retrieval_completed_at':datetime.datetime.fromtimestamp(f.stat().st_mtime,datetime.timezone.utc).isoformat(),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'exit_code':0,'pages':len(fitz.open(f)),'extracted_text_file':str(b/(stem+'.txt'))})
(b/'square-conic-source-read.json').write_text(json.dumps({'version':1,'run':r,'receipts':receipts,'authoritative_entrypoint':'https://www.math.purdue.edu/~jlipman/papers-older/','read_extent':['1969 printed pp.264–268 / PDF70–74: complete extracted text and rendered pages, including relations5/5′; no full-paper read claim.','1978 printed pp.164–174 / PDF14–24: complete displayed extracted proof blocks for tangent-cone control, square cases and Proposition1.28; no complete external recursive-source read claim.'],'discovery_failures':['https://www.math.purdue.edu/~jlipman/papers.html returned404','https://www.math.purdue.edu/~jlipman/papers-older.html returned404; author index linked directory papers-older/ succeeded'],'limitations':'The ADE diagrams/classification conclusions are not imported; omitted chart details are independently filled in square-conic-closure.md. New PDF fetches succeeded at their first actual paper URLs. All earlier source fetch/recovery objects are preserved.'},indent=2)+'\n')
