import {readFileSync,writeFileSync} from 'node:fs';
import {sha256,splitFrontmatter} from '../../tools/step9-lib.mjs';
import {itemHashGuard,itemHashJudge} from '../../tools/item-hash.mjs';
const dir='research/frontier-43-complex-representation-15-step9-draft-status-owner';const proposal=JSON.parse(readFileSync(`${dir}/proposal.json`));
const notes={
'def-kazhdans-property-t':'The quantified almost-invariance implication matches the declared definition; empty tests and zero Hilbert space are handled without a supremum convention or hidden compactness hypothesis.',
'def-kazhdan-pair-and-kazhdan-constant':'Downward closure and extended-real infimum handle zero representations and empty tests. Compact displacement attainment is essential to the endpoint equivalence, and no endpoint equivalence is claimed for noncompact tests.',
'def-relative-property-t-for-a-pair':'Arbitrary subgroup fixed vectors are well defined without normality or closedness. The source closed-subgroup qualification is explicitly distinguished from the broader definition.',
'lem-quasi-regular-representation-on-a-discrete-coset-space':'Open cosets make the quotient discrete. Finite-support orbit continuity extends by uniform unitary approximation; transitivity forces constant invariant coordinates and square summability excludes a nonzero constant on an infinite coset set.',
'lem-irreducible-c-star-representations-separate-arbitrary-c-star-algebras':'Norm-attaining character extends by complex Hahn–Banach. The imaginary-part estimate and positive order estimate make the extension positive. The norm-attaining face is compact; its extreme state gives GNS irreducibility by the commuting-projection calculation E=tI. Nonunital ideal restriction is nondegenerate and irreducible. No separability hypothesis is introduced.',
'lem-sl-n-r-is-boundedly-generated-by-elementary-root-subgroups':'Right multiplication E(j,k) repairs a zero pivot by adding column j to k. Later column and row elimination preserve earlier pivots. The two six-factor block products give diag(a,a^-1); the conservative total 2(n^2-1)+6(n-1) is below the advertised bound.',
'lem-sl2-r-has-no-invariant-probability-on-the-projective-line':'Distinct fixed lines provide an SL2 conjugating basis. Equal-mass integer translation intervals force mass onto infinity; the second unipotent moves infinity to a finite point. The statement is probability-specific and preserves the source local-finiteness caveat.',
'lem-almost-invariant-vectors-and-positive-type-functions':'The coefficient/displacement square identity and Cauchy–Schwarz bounds establish both directions. Compact-set/tolerance indexing is directed by finite unions. The reverse GNS/direct-sum clause only asserts eventual coordinate invariance and direct-sum almost invariance.',
'thm-property-t-is-equivalent-to-the-existence-of-a-kazhdan-pair':'The contradiction uses a set of coefficient functions and canonical GNS witnesses, avoiding choice from a proper class of representations. Orthogonal-complement quantitative bounds use the exact relative displacement normalization and handle empty tests.',
'lem-normal-relative-property-t-controls-distance-to-invariant-vectors':'Normality preserves the fixed subspace and its complement. Pythagoras yields distance and factor-two displacement bounds. The positive-power compact-generator clause uses pointwise coefficient convergence, a compact Hausdorff coefficient image, finite complex measure duality, dominated convergence, and Mazur finite convex combinations; it does not assume a bounded compact word length.',
'lem-sl2-r-semidirect-r2-has-relative-property-t':'Set-indexed coefficients give separable cyclic GNS carriers, meeting the spectral-PVM hypotheses. Rational characters identify the zero spectral projection with translation invariants. The 2/m projection-measure bound pushes to the projective line; weak subsequences and regular-measure uniqueness contradict two distinct-fixed-line dual unipotents.',
'thm-compact-groups-have-property-t':'Continuous compact orbit images admit uniformly convergent finite Borel simple approximants. Haar left invariance yields the fixed Bochner average; compact maximum attainment converts pointwise strict pair bounds to a uniform strict bound below one.',
'thm-property-t-implies-compact-generation':'Open compactly generated subgroups cover each compact test by a finite subcover and a generated finite union. Infinite-index quasi-regular summands have no invariant vectors, but a single coordinate supplies the required almost-invariant vector; finite index gives compact generation.',
'thm-property-t-is-equivalent-to-isolation-of-the-trivial-representation':'Kernel separation makes chi injective on the isolated-class ideal. Scaling yields a central self-adjoint idempotent p, and weak-containment kernel inclusion forces pi(p) nonzero. The reduced nondegenerate summand is the amplified trivial representation. The arbitrary-set R clause excludes invariant nontrivial classes explicitly.',
'thm-property-t-is-uniform-spectral-gap-for-representations':'A compact Kazhdan pair controls every invariant complement. In the converse compact attainment gives D<epsilon, and Pythagoras makes the fixed component nonzero. The empty-test and adjoined-identity cases are treated explicitly.',
'thm-property-t-passes-to-quotients':'The quotient map is open; closed normality yields Hausdorff separation and the product quotient property yields group-operation continuity. Compact images transfer almost invariance to the pullback, and surjectivity transfers invariants back. No choice is used by this proof.',
'thm-sl-n-r-has-property-t-for-n-at-least-three':'The spare coordinate embeds each root into a real semidirect translation subgroup. The finite relative tests and delta/(4M) tolerance bound root displacement by 1/(2M), then bounded generation bounds the whole orbit by one half. The invariant closed convex orbit hull has a unique least-norm point of norm at least one half.',
'cex-z-does-not-have-property-t':'The rational-circle scalar has unit modulus and nonzero imaginary part; geometric sums bound all signed integer powers on each finite compact set. Nonexistence of a compact Kazhdan pair, under the declared AC equivalence, gives non-(T); individual scalar representations are not asserted almost invariant.',
'ex-a-kazhdan-pair-for-a-compact-group':'The already checked Haar-average supplier supplies the tolerance-one pair and exact norm estimate. The conclusion remains nonoptimal, and the zero-Hilbert-space pair implication is vacuous.'};
const byId=new Map(proposal.rows.map(r=>[r.id,r]));const order=[];const visit=id=>{if(order.includes(id))return;const text=readFileSync(`${dir}/before/${byId.get(id).file}`,'utf8'); const fm=splitFrontmatter(text).frontmatter;for(const m of fm.matchAll(/^  - (\S+)$/gm)) if(byId.has(m[1]))visit(m[1]);order.push(id);};for(const id of byId.keys())visit(id);
const rows=order.map(id=>{const r=byId.get(id);const text=readFileSync(r.file,'utf8');const before=readFileSync(`${dir}/before/${r.file}`,'utf8');if(splitFrontmatter(text).body!==splitFrontmatter(before).body)throw Error('body changed '+id);return {id,file:r.file,current_raw_sha256:sha256(text),current_guard_sha256:itemHashGuard(text),current_judge_sha256:itemHashJudge(text),body_sha256:sha256(splitFrontmatter(text).body),mathematical_body_unchanged:true,review:notes[id],uncertain:false};});
writeFileSync(`${dir}/review.json`,JSON.stringify({version:1,run:proposal.run,owner:'/root/step9_draft_status_owner',reviewed_at:new Date().toISOString(),scope:'The exact 19 selected missing-status subjects, dependency ordered; local full item proofs and their explicitly restated interfaces reviewed. No new mathematical repair.',source_qualification:'This owner read the complete local item arguments and source locators, and consulted native batch4 review evidence and contract structure. This receipt does not claim a new full reading of BHV, Farah, Breuillard, Tao, or every external supplier proof. Actual prior native source reading and all bounded C-star source qualifications remain on their immutable original evidence. Exercise prompts are not treated as proofs.',direct_consumer_impact:'No Statement, Definition, Facts, proof, deps, source, assumption or title changes. No mathematical consumer repair is triggered. Raw/guard/judge/surface carrier hashes change because current tools include status; ordinary current judgment/stamping/readiness must establish currency.',spine_affected:[],contract_mutation_needed:false,audit_manifest_mutation_needed:false,plan_mutation_needed:false,rows},null,2)+'\n');console.log(JSON.stringify({reviewed:rows.length,order,body_unchanged:true},null,2));
