import pathlib,json
out=pathlib.Path('research/frontier-41-ha-dt-29-owner5b-completion-group-2')
fixes={
('def-regular-continuation-datum-between-morse-smale-pairs','def-parametrized-morse-trajectory-space'):'No current direct body citation. The Definition instead defines C(p,q) as unshifted solutions and identifies it with a finite-window fibre product. The autonomous parametrized-orbit definition is background only; its translation action is explicitly not imposed on C(p,q).',
('ex-continuation-across-a-birth-death-adds-an-acyclic-pair','lem-unstable-orientations-induce-trajectory-moduli-orientations'):'No direct body citation. F1 and the unique local orbit calculation use the signed-differential convention, which in turn uses the supplier Statement 3 flow comparison to assign that orbit +1 or -1. Either sign is a unit, so the acyclic-pair conclusion needs no additional gluing or ambient orientation claim.',
('ex-morse-and-cellular-boundaries-for-a-surface-handle-presentation','lem-boundary-orientation-of-compactified-one-dimensional-morse-moduli'):'No current body use. F2 computes opposite signs on the two halves of the oriented unstable interval using the unstable-orientation lemma; it does not use this supplier, which concerns an index-drop-two orbit compactification. The declared dependency is harmless surplus context.',
('ex-two-morse-functions-on-the-circle-have-isomorphic-morse-homology','lem-boundary-orientation-of-compactified-one-dimensional-morse-moduli'):'No current body use. F2 and the circle computation compare the flow direction on opposite unstable arcs directly. This supplier concerns a one-dimensional orbit moduli space (drop two), and is not misapplied to the circle rigid orbit sets.',
('lem-cellular-boundary-coefficient-equals-the-morse-trajectory-count','cor-index-one-trajectory-moduli-spaces-are-finite'):'No direct body citation. Proof 1.1 proves the required rigid finiteness from the actual metric/relative height compactness, zero orbit dimension and absence of a broken drop-one limit. The older closed normalized-field finiteness corollary is not extended to metric or relative data by declaration.',
('lem-compactified-unstable-manifolds-give-a-cw-decomposition','def-handle-decomposition-relative-to-the-incoming-boundary'):'Implicit notation in Statement 2 and Proof 8.1: the relative handle stages start at the M0 collar and attach the actual value-ordered handles. This is exactly the Definition finite ordered list and collar-base convention, including the empty base and index-zero empty attaching sphere; no uniqueness or skeletal-order claim is borrowed.',
('lem-compactified-unstable-manifolds-give-a-cw-decomposition','lem-breaking-length-is-bounded-by-index-drop'):'Implicit bound in Proof 3.1: positive component index drops bound the number of critical breaks. This is the supplier Statement length <= total index drop, applied to the normalized orbit convention; the actual-metric branch establishes the same positive-drop argument through its transverse invariant disks and matching charts.',
('lem-compactified-unstable-manifolds-give-a-cw-decomposition','lem-gluing-broken-index-two-trajectories-gives-collar-ends'):'No current load-bearing use. F3 and Proof 4.1-6.1 use the actual metric mixed-boundary/matching/pointed-crossing suppliers for arbitrary broken configurations. A drop-two normalized collar alone is not asserted to prove disk topology.',
('lem-compactified-unstable-manifolds-give-a-cw-decomposition','lem-interior-slab-handle-attachment'):'No direct body citation or stronger use. F1 and Proof 2.1 use the ordinary one-critical Morse handle theorem, and Proof 8.1 compares attaching maps by homotopy in the previous stage. The declared interior-slab supplier is not used to assert a diffeomorphism fixing the original lower sublevel.',
('lem-compactified-unstable-manifolds-give-a-cw-decomposition','thm-index-two-compactification-is-a-compact-one-manifold-with-boundary'):'No current load-bearing use. The disk and all-corner claims are constructed in Proof 3.1-6.1 using actual metric pointed passage and crossing. This normalized drop-two one-manifold conclusion is neither extended to arbitrary indices nor used as a disk-homeomorphism theorem.',
('lem-compactified-unstable-manifolds-give-a-cw-decomposition','thm-morse-trajectory-compactness-up-to-breaking'):'No current load-bearing use. F2 and Proof 3.1 explicitly use the actual-metric pointed-tail interface in continuation compactness and supply moving-endpoint/exit extraction locally. The older normalized fixed-critical-end theorem is not silently promoted to this relative pointed setting.',
('lem-continuation-map-of-constant-data-is-the-identity','thm-continuation-trajectories-are-compact-up-to-breaking'):'No current load-bearing use. F1-F4 identify empty distinct-critical equal-index spaces and the sole positive constant solution; the map is explicitly finite by this classification. General compactness remains a declared background supplier.',
('lem-gluing-broken-index-two-trajectories-gives-collar-ends','def-broken-morse-trajectory'):'Implicit object in Statement and Proof: the once-broken pair gamma1#gammma2 is a two-component string of nonconstant orbit classes with a distinct intermediate critical point. This is the Definition orbit-set identification and length-two convention; the collar fixes representatives by sections.',
('lem-metric-end-flow-matching-gives-local-broken-charts','def-broken-continuation-trajectory'):'Implicit configuration and topology in Statement and Proof: a fixed-time middle with independently translated autonomous tails, including a constant middle, is matched at its anchors. This is the Definition temporal-order/unshifted-middle convention. The proof extends it to augmented and autonomous/free-endpoint contexts explicitly rather than borrowing their transversality from that Definition.',
('lem-orientation-lines-orient-continuation-moduli-spaces','def-parametrized-morse-trajectory-space'):'No direct body citation. Autonomous tail signs use the unstable-orientation supplier and its evaluation/positive-flow convention; the middle uses F1 unshifted evaluation. The autonomous translation quotient is not imposed on the continuation determinant sequence.',
('lem-orientation-lines-orient-continuation-moduli-spaces','def-signed-morse-differential-over-the-integers'):'Implicit sign dictionary in Statement 2: tail signs are the unstable-orientation comparison signs, hence exactly epsilon in the signed-differential formula. The lower and upper boundary signs are +epsilon*tau and -tau*epsilon respectively. The signed definition contributes no additional analytic compactness claim.',
('lem-orientation-lines-orient-continuation-moduli-spaces','thm-continuation-trajectories-are-compact-up-to-breaking'):'No current load-bearing use for orientation. The lemma assumes a specified boundary collar and computes its ordered determinant sign from exact matching. General existence/compactness of that boundary is supplied to downstream count theorems separately; orientation is not a substitute for it.',
('thm-continuation-composition-law-on-homology','def-two-parameter-continuation-homotopy'):'No direct body citation. F5 invokes datum independence from the homotopic-data theorem, whose exact input is an augmented-regular fixed-end two-parameter family. The long-plateau argument here retains T as its own parameter and does not require every finite-T datum regular; it uses exact matching and then generic perturbation.',
('thm-continuation-trajectories-are-compact-up-to-breaking','lem-continuation-solutions-have-critical-limits'):'Implicit endpoint assertion in Proof: the extracted unshifted middle solves the fixed equation and has critical end limits on its autonomous half-lines. The supplier Statement gives these limits for every global solution on closed M; actual compact half-tail extraction retains which criticals and broken tails occur.',
('thm-homotopic-continuation-data-give-chain-homotopic-maps','def-mod-two-morse-chain-group'):'Implicit modules in Statement K_k: source degree k and target degree k+1 are the finite free critical-point modules; mod-two signs are discarded. For actual metric ends the explicit metric-end complex supplies the extension of this basis convention, so no normalized-gradient assumption is imposed.',
('thm-homotopic-continuation-data-give-chain-homotopic-maps','def-morse-homology-of-a-morse-smale-pair'):'Implicit consequence in Statement and final Proof: the chain-homotopy identity induces equality on ker partial/im partial. The Definition metric-pair paragraph supplies precisely these finite actual-end complexes; no new pair-independence claim is assumed to prove the identity.',
('thm-morse-homology-is-naturally-isomorphic-to-singular-homology','def-morse-homology-of-a-morse-smale-pair'):'Implicit domain throughout Statement and Proof 6.1: HM is homology of the supplied normalized or actual-metric finite complex. The Definition explicitly uses the metric-end lemma for arbitrary g. The proof transports those homology groups via its filtered comparison rather than assuming singular comparison from the Definition.'
}
def refine(notes):
 rows=notes.split('\n');new=[]
 for r in rows:
  if ': declared prerequisite only;' in r:
   supplier=r.split(':',1)[0];key=(current,supplier);assert key in fixes,key
   new.append(supplier+': '+fixes[key])
  else:new.append(r)
 return '\n'.join(new)
p=out/'impact-dispositions.json';d=json.loads(p.read_text())
for x in d['dispositions']:current=x['id'];x['notes']=refine(x['notes'])
p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
p=out/'edge-verdicts.jsonl';rows=[json.loads(s) for s in p.read_text().splitlines()]
for x in rows:
 key=(x['from'],x['to'])
 if key in fixes:x['note']=x['to']+': '+fixes[key]+' Interface adjudication: '+json.loads((out/'interface-evidence.json').read_text())['consumer_adjudications'][x['from']]
p.write_text(''.join(json.dumps(x,ensure_ascii=False)+'\n' for x in rows))
(out/'implicit-and-surplus-interface-notes.json').write_text(json.dumps([{'consumer':c,'supplier':s,'note':v} for (c,s),v in fixes.items()],indent=2)+'\n')
print('Refined all 22 uncited interfaces individually, distinguishing implicit use from surplus declarations.')
