from pathlib import Path
import json
p=Path(__file__).parent
source=[{'title':'Meinel and Hütten, electrically counterpoised dust (2011)','url':'https://arxiv.org/pdf/1105.3807','reading':'supplier-reading.md'},{'title':'Harte, Gravitational lensing beyond geometric optics I (2019)','url':'https://arxiv.org/pdf/1808.06203','reading':'supplier-reading.md'},{'title':'Carroll, Lecture Notes on General Relativity','url':'https://arxiv.org/pdf/gr-qc/9712019','reading':'supplier-reading.md'}]
math=[
('def-emg-matter-formal-systems','Smooth formal matter, EM tensors and observer quantities',[],0,'EMG-MM01'),
('thm-emg-charged-dust-projection','Charged dust balance equivalence and advected charge ratio',[0],1,'EMG-MM01'),
('thm-emg-charged-fluid-projections','Perfect-fluid exchange projections and conduction heating',[0],2,'EMG-MM01'),
('thm-emg-selected-matter-energy-conditions','EM/dust/fluid energy inequalities and causal addition',[0],3,'EMG-MM01'),
('thm-emg-charged-symmetry-current','Killing exchange current and gauge-compensated charged first integral',[0,'lem-emg-maxwell-stress-divergence','thm-gr-density-divergence-and-finite-chain-flux','thm-gr-killing-and-on-shell-matter-identities'],4,'EMG-MM01'),
('lem-emg-controlled-maxwell-wkb','Finite WKB Maxwell residual, null rays and polarization quotient',[0,'thm-gr-lorentz-curvature-bianchi-and-jacobi'],5,'EMG-MM03'),
('lem-emg-source-and-test-scaling','Smooth source/dust scaling and test-backreaction obstructions',[0,3,'prop-emg-test-field-residual-order'],6,'EMG-MM03'),
('lem-emg-conformastatic-curvature','Arbitrary-positive-H conformastatic Ricci and Einstein components',[0],7,'EMG-MM02'),
('thm-emg-smooth-counterpoised-dust','Exact smooth superharmonic counterpoised dust family',[0,1,3,7],8,'EMG-MM02'),
('cor-emg-regular-counterpoised-sphere','Globally regular sphere, proper integrals and dilute bounds',[3,7,8],9,'EMG-MM02'),
('thm-emg-weak-slow-test-lorentz-limit','Controlled weak/slow charged test trajectory comparison',[0,'lem-rpm-external-charge-local-ivp','thm-picard-lindelof-local-existence-and-uniqueness'],10,'EMG-MM03')]
scopes={0:'Smooth oriented time-oriented Lorentz domain,−+++; formal equation hypotheses; observers and SI interpretations separately declared.',1:'rho>0,C1 scalars,C2 U,U²=−c²; current sigma U; no coupled IVP inference and no division on zero density.',2:'C1 epsilon,p,current and C2 U; perfect-fluid tensor; exact longitudinal/spatial equations; optional explicitly specified Ohmic q=chi E_U,chi>=0.',3:'Positive mu and metric observers; EM positive quadratic energy/causal flux; specified perfect-fluid inequalities only; no general matter positivity assumption.',4:'Smooth Maxwell/exchange tensors and a supplied Killing field; finite GR chart/chain flux domains; local potential symmetry LxiA=dchi for test-curve scalar.',5:'C4 real phase,C3 complex amplitudes; exact finite-order null/transverse/transport constraints; compact positive-component norm bounds; residual/leading-field estimate only, no exact-solution error.',6:'Fixed smooth metric, smooth actual Maxwell solution, real source amplitude scaling; quadratic stress residual and source/dust comparison; no nearby coupled family or point-charge construction.',7:'H>0,C3,static on open D inR3; explicit connection/Ricci/Einstein tensor table for arbitrary H, not only harmonic H.',8:'Smooth H>0,DeltaH<=0,explicit parameters and units; checks Maxwell,dust,Einstein withLambda0 pointwise; no equilibrium stability or general PDE existence.',9:'a,b>0,H=1+a/sqrt(r²+b²) on wholeR3; actual finite proper mass/charge integrals; explicit metric/density dilute comparison; infinite extent.',10:'Stationary weak metric with exact C2 remainder orders; prescribed E/B scaling; alpha nonzero; uniformly small speed, common compact trajectory containment and finite scaled duration; no full coupled family construction.'}
rows=[];mid={n:i for i,t,ds,n,pg in math}
for i,t,ds,n,pg in math:
 ds=[mid[d] if isinstance(d,int) else d for d in ds]
 if n==0:ds=['def-gr-smooth-lorentzian-objects','thm-gr-nondegenerate-levi-civita-and-tensor-derivative','def-countable-choice']
 rows.append({'id':i,'title':t,'domain':'mathematics','kind':i.split('-')[0].replace('thm','theorem').replace('lem','lemma').replace('cor','corollary').replace('def','definition'),'deps':ds,'dependency_roles':{d:'mathematical-premise' for d in ds},'page':pg,'side':'A','proof_module':'mathematical-proofs.md#ml'+str(n).zfill(2),'scope':scopes[n],'physical_scope':None,'proof_status':'explicit-definition' if n==0 else 'completed-local-argument','status':'research-only','production_ready':False,'empirical_premises':[],'source_references':source})
physics=[
('def-emg-matter-observables','Smooth matter quantities, current and observer observables',['def-emg-geometry-units',mid[0]],0,'EMG-MP01','definition'),
('post-emg-transported-charged-dust','Selected transported charged-dust Einstein–Maxwell model',['def-emg-matter-observables','post-emg-einstein-maxwell-equations','post-emg-covariant-maxwell',mid[1]],1,'EMG-MP01','postulate'),
('post-emg-charged-fluid-balance','Selected charged perfect-fluid exchange/Ohmic branch',['def-emg-matter-observables','post-emg-einstein-maxwell-equations','post-emg-covariant-maxwell',mid[2]],2,'EMG-MP01','postulate'),
('post-emg-background-maxwell-test','Separately adopted fixed-background Maxwell and charged probes',['def-emg-matter-observables','post-rpm-external-charge-action','pthm-rpm-external-charge-action-equivalence',mid[5]],3,'EMG-MP03','postulate'),
('pthm-emg-dust-mass-force-reduction','Dust continuity, transport and Lorentz acceleration',['post-emg-transported-charged-dust',mid[1]],4,'EMG-MP01','physics-theorem'),
('pthm-emg-fluid-work-heating','Convective/Ohmic comoving mechanical work prediction',['post-emg-charged-fluid-balance',mid[2]],5,'EMG-MP01','physics-theorem'),
('pthm-emg-matter-symmetry-charges','Selected total-stress/Killing charges',['post-emg-transported-charged-dust',mid[4],'lem-emg-maxwell-stress-divergence'],6,'EMG-MP01','physics-theorem'),
('pthm-emg-matter-energy-conditions','Observer energy conditions for selected matter plus EM',['def-emg-matter-observables',mid[3]],7,'EMG-MP01','physics-theorem'),
('pthm-emg-counterpoised-smooth-sphere','Exact smooth coupled counterpoised dust and observables',['post-emg-transported-charged-dust',mid[8],mid[9]],8,'EMG-MP02','physics-theorem'),
('pthm-emg-controlled-test-geometric-optics','Controlled test-wave rays, polarization and Maxwell residual',['post-emg-background-maxwell-test',mid[5],mid[6]],9,'EMG-MP03','physics-theorem'),
('pthm-emg-source-test-backreaction-scope','Exact source/test-field/backreaction consistency distinction',['post-emg-background-maxwell-test',mid[6]],10,'EMG-MP03','physics-theorem'),
('pthm-emg-weak-slow-test-motion','Finite-time weak/slow charged probe correspondence',['post-emg-background-maxwell-test',mid[10]],11,'EMG-MP03','physics-theorem')]
pid={n:i for i,t,ds,n,pg,k in physics}
for i,t,ds,n,pg,k in physics:
 roles={d:'mathematical-premise' if d in mid.values() or d.startswith(('lem-','thm-','cor-')) else 'physical-assumption' if d.startswith('post-') else 'physical-result' if d.startswith('pthm-') and k=='physics-theorem' else 'formulation-prerequisite' for d in ds}
 scope={0:'Framework-local SI primitive/derived quantities; observers and current/stress constructions; metric/field unknown versus prescribed distinction.',1:'Smooth single-stream charged dust, full EM/Einstein branch, transported charge-to-mass ratio; undivided zero-density equations; no general PDE or caustic theorem.',2:'Smooth selected isotropic fluid with explicitly chosen current/EOS/Ohmic law; local mechanical exchange only; no global conducting-fluid/entropy theorem.',3:'Fixed prescribed g/F test model; no Einstein condition on unchanged metric and no probe self-field; WKB only on the stated bounded phase region.',4:scopes[1],5:scopes[2],6:scopes[4]+' Selected adopted exchange; no universal gravitational energy.',7:scopes[3]+' Physical observer interpretation conditional.',8:scopes[8]+' Finite observables additionally require ML09 exact spherical family.',9:scopes[5]+' Fixed-background test Maxwell interpretation.',10:scopes[6]+' Fixed-background physical scope; no point-charge source.',11:scopes[10]+' Maxwell/Einstein background compatibility is extra, not constructed.'}[n]
 rows.append({'id':i,'title':t,'domain':'physics','kind':k,'deps':ds,'dependency_roles':roles,'page':pg,'side':'A','proof_module':'physical-models.md#pml'+str(n).zfill(2),'scope':scope,'physical_scope':scope,'proof_status':'source-scoped-adopted-model' if k=='postulate' else 'explicit-definition' if k=='definition' else 'completed-local-argument','status':'research-only','production_ready':False,'empirical_premises':[],'source_references':source})
examples=[(1,[mid[1]],'EMG-MM01'),(2,[mid[2]],'EMG-MM01'),(3,[mid[3]],'EMG-MM01'),(4,[mid[4]],'EMG-MM01'),(5,[mid[8],mid[9]],'EMG-MM02'),(6,[mid[9]],'EMG-MM02'),(7,[mid[5],mid[6]],'EMG-MM03'),(8,[mid[10]],'EMG-MM03')]
for n,ds,pg in examples:
 rows.append({'id':'ex-emgmath-ml-b'+str(n).zfill(2),'title':['','Advected nonconstant ratio without Maxwell closure','Explicit local conduction energy','Anisotropic magnetic stress and null energy flux','Static electrostatic first integral','Regular smooth counterpoised sphere','Quantified dilute exact coupled family','Exact finite-frequency transverse Maxwell field','Constant magnetic slow-orbit error'][n],'domain':'mathematics','kind':'example','deps':ds,'dependency_roles':{d:'mathematical-premise' for d in ds},'page':pg+'-examples','side':'B','proof_module':'examples.md#b'+str(n).zfill(2),'scope':'Complete explicit ideal calculation in B'+str(n).zfill(2)+' with its stated exclusions; B leaf.','physical_scope':None,'proof_status':'completed-local-verification','status':'research-only','production_ready':False,'empirical_premises':[],'source_references':source})
pex=[(3,[pid[7]],'EMG-MP01'),(4,[pid[3],mid[4]],'EMG-MP03'),(5,[pid[8]],'EMG-MP02'),(6,[pid[8]],'EMG-MP02'),(7,[pid[9],pid[10]],'EMG-MP03'),(8,[pid[11]],'EMG-MP03')]
for n,ds,pg in pex:
 rows.append({'id':'ex-emg-ml-b'+str(n).zfill(2),'title':'Conditional physical interpretation of B'+str(n).zfill(2),'domain':'physics','kind':'example','deps':ds,'dependency_roles':{d:'mathematical-premise' if d in mid.values() else 'physical-assumption' if d.startswith('post-') else 'physical-result' for d in ds},'page':pg+'-examples','side':'B','proof_module':'examples.md#b'+str(n).zfill(2),'scope':'The actual B'+str(n).zfill(2)+' calculation interpreted under its A model: exact coupled dust only B05/B06; others are pointwise observer/test-background statements, not full coupled-field examples.','physical_scope':'Conditional ideal model calculation under supplied A premises; no experiment or simulation; B leaf.','proof_status':'completed-local-verification','status':'research-only','production_ready':False,'empirical_premises':[],'source_references':source})
pairs=[{'a':pg,'b':pg+'-examples','domain':domain}for domain,pgs in [('mathematics',['EMG-MM01','EMG-MM02','EMG-MM03']),('physics',['EMG-MP01','EMG-MP02','EMG-MP03'])]for pg in pgs]
(p/'inventory.json').write_text(json.dumps({'research_only':True,'date':'2026-10-04','items':rows,'page_pairs':pairs,'no_production_or_independent_acceptance':True},indent=2)+'\n')
