from pathlib import Path
import json,hashlib
W=Path(__file__).resolve().parent;R=Path.cwd();B='physics/research/extended-frameworks-2026-10-03/'
def rec(path,extent,status,use,ids=[]):
 p=R/path
 return dict(path=path,sha256=hashlib.sha256(p.read_bytes()).hexdigest(),reading_extent=extent,status=status,consumer_use=use,ids=ids,transitive_proof_audit=False)
s=[]
s.append(rec('physics/research/first-principles-2026-10-03/relativity/scaffold/gr-local-proofs.md','G0–G4 read in earlier current conversation; G6/G7 reread fully for current role','research-proof-scaffold','ET00–ET03 connection, Killing/isometry/geodesic and flux identities',['def-gr-smooth-lorentzian-objects','thm-gr-nondegenerate-levi-civita-and-tensor-derivative','thm-gr-local-lorentz-tetrad-existence','thm-sr-local-congruence-adapted-charts-and-frobenius']))
s.append(rec(B+'einstein-maxwell-models/workers/geometry-actions/proof-modules.md','GA7 reread fully; no claim all module reread','completed research dossier, read-only','ET03 Cartan identity and Lorentz-force sign convention'))
s.append(rec('physics/research/first-principles-2026-10-03/thermodynamics/scaffold/completed-developments.md','M22 and M34 fully read; no fresh whole-file/transitive certification','research-proof-scaffold','ET06 rectangular heat reflection, time-zero compatibility, uniqueness, entropy and Poincare estimate'))
s.append(rec(B+'quantum-statistical-mechanics/workers/finite-states/state-proofs.md','Q0–Q7 and B1–B3 fully read; Q6 separately reread after initial output slice','completed research dossier, read-only','ET04 Q0 finite matrix and Q6 finite Gibbs KMS; ET05 Q2 covariance; Q5 trace-class qualifications',['lem-qsm-matrix-state-calculus','lem-qsm-finite-gibbs-kms','lem-qsm-matrix-exponential-response']))
s.append(rec(B+'quantum-statistical-mechanics/workers/infinite-equilibrium/proof-modules.md','I5/I5a/I6 fully read only','completed research dossier, read-only','ET04 actual bounded-strip definition, invariance and finite characterization; I6 comparison only, no curved-state existence',['def-qsm-kms-state']))
s.append(rec(B+'quantum-statistical-mechanics/workers/dynamics-transport/equilibrium-response.md','T0–T6 fully read','completed research dossier, read-only','ET05 finite-time Kubo remainder, spectral measure FDT, recurrence/Green–Kubo limitations; qubit calculated locally rather than logical dependence on B example',['thm-qsm-dt-finite-kubo','thm-qsm-dt-spectral-fdt']))
s.append(rec(B+'thermodynamics-and-general-relativity/workers/covariant-thermodynamics/proof-modules.md','CT0–CT4 fully read; later sections not claimed read','current sibling research scaffold','ET06 exact q=cQ specialization and local state/Euler identities; ET08 consumes first-order model post, no duplicate',['def-tgr-local-fluid-state','lem-tgr-local-gibbs-euler','lem-tgr-dissipative-entropy-identity','post-tgr-first-order-dissipation']))
s.append(rec(B+'thermodynamics-and-general-relativity/quantities-and-postulates.md','Entire current body read, including framework units/material/entropy-admissibility; later edits require refresh','canonical current research scaffold','ET08 exact physical units, material/entropy model premise scopes',['def-tgr-framework-units','post-tgr-local-material-thermodynamics','post-tgr-local-entropy-admissibility']))
for ident in ['thm-heat-cauchy-solution-for-bounded-continuous-data','lem-heat-kernel-normalisation-scaling-and-derivatives','lem-spatial-and-time-derivatives-pass-through-heat-convolution-for-positive-time','cor-l-one-approximate-identities-converge-uniformly-on-compacta-for-continuous-functions']:
 p='items/'+ident+'.md';txt=(R/p).read_text();status='published' if '\nstatus: published' in txt else 'draft'
 s.append(rec(p,'Entire frontmatter, statement, hypotheses and proof read for current role',status,'ET06 exact bounded uniformly continuous Gaussian heat construction and declared Countable Choice; no blanket PDE existence',[ident]))
s.append(rec('items/def-countable-choice.md','Existing exact choice definition retained from supplier contract; not newly fully reread','published definition inherited','Explicit ET06 integration choice premise',['def-countable-choice']))
ext=[]
for stem,url,title,pages,findings in [
 ('becattini-four-temperature','https://arxiv.org/pdf/1606.06605','Becattini, The four-temperature vector in relativistic thermodynamics and quantum field theory',13,['Formal stress exponential is not a curved QFT trace construction; ET04 uses actual finite states or supplied KMS only.','One given stress/current cancellation is not a universal necessity argument; ET02 supplies full massive-shell polynomial argument.','Do not assume every observable is an analytic local-jet expression; ET01 proves tensor naturality, quantum stationarity uses actual invariant state.','Entropy surface integrals are definable without global conservation; broad source phrasing not inherited.']),
 ('santiago-visser-stationary','https://arxiv.org/pdf/1807.02915','Santiago and Visser, Tolman temperature gradients in a general stationary spacetime',7,['Eq2.6 acceleration/T Taylor sign corrected: T displacement is −a·dx.','Eq7.7 angular velocity denominator must be gφφ, not gtt, to match adjacent equations.','Normal/freefall zero heat or acceleration relation alone does not establish Killing rigidity/global KMS; ET01 and ET07 preserve this distinction.']),
 ('klein-potentials','https://arxiv.org/pdf/1104.4062','Rueda, Ruffini and Xue, The Klein first integrals in an equilibrium system with electromagnetic, weak, strong and gravitational interactions',12,['Eq65 aggregate Σn_i dE_i=0 needs truly independent species variations to imply individual constancy; ET03 supplies exchange/Liouville proof and retains explicit premises.','Eq28 displayed scalar stress contains apparent second-derivative typo, Eq30 apparent mixed rho/omega typo; no stress/EOS or coupled mean-field theorem imported.','Strong/weak neutron-star mean-field equations and global solutions not certified; only gravitational/electrochemical equilibrium motivation consumed.'])]:
 p=W/'sources/raw'/f'{stem}.pdf';t=p.with_suffix('.txt')
 ext.append(dict(title=title,url=url,retrieved='2026-10-04',pdf_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),text_sha256=hashlib.sha256(t.read_bytes()).hexdigest(),pdf_pages=pages,reading_extent=f'All {pages} extracted PDF pages read, including bibliography; bibliography references not retrieved or claimed read.',disposition='checked contextual full source; local proofs supply all asserted new claims, no imported continuum existence theorem',findings=findings))
inv=json.loads((W/'inventory.json').read_text())['records'];own={r['id'] for r in inv};deps=sorted({d for r in inv for d in r['deps'] if d not in own})
registry={}
for d in deps:
 candidates=[x for x in s if d in x['ids']]
 assert candidates,d
 registry[d]=dict(domain='physics' if d.startswith('post-') or d=='def-tgr-framework-units' else 'mathematics',path=candidates[0]['path'],status=candidates[0]['status'],reading_extent=candidates[0]['reading_extent'])
(W/'sources-and-suppliers.json').write_text(json.dumps(dict(local_suppliers=s,external_sources=ext,external_registry=registry,source_claim='Actual extents only; no fresh transitive audit or independent acceptance claimed; all earlier dossiers read-only.'),ensure_ascii=False,indent=2)+'\n')
(W/'sources/.gitignore').write_text('raw/\n')
