import copy, hashlib, json, pathlib, shutil, subprocess
R=pathlib.Path('.'); RUN='frontier-43-complex-representation-15'; B=R/'research'/f'{RUN}-step8-owner-f-proposal'
for s in ['before','proposed','source-evidence','shadow/research']: (B/s).mkdir(parents=True,exist_ok=True)
def sha(p): return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def write(p,d): pathlib.Path(p).write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
paths=[f'research/{RUN}-alpha-f-scope-decisions.json',f'research/{RUN}-step8-scope-delta.json','research/plan-spec.json','research/plan-quantum-groups-track.md','research/plan-kazhdan-lusztig-track.md']+[f'research/{RUN}-batch-{n}.{ext}.json' for n in [6,7,8] for ext in ['coverage','pages']]+['items/thm-quantized-sl-two-string-formulas.md','items/thm-triangular-decomposition-of-a-quantized-enveloping-algebra.md','items/thm-the-drinfeld-jimbo-formulas-define-a-hopf-algebra.md','items/def-normalized-type-a-hecke-algebra-and-its-bar-involution.md']
guards=[]
for p in paths:
 dst=B/'before'/pathlib.Path(p).name;shutil.copy2(p,dst);guards.append({'path':p,'raw_sha256':sha(p),'snapshot':str(dst)})
passages=[('berkeley-quantum-weyl.txt','/tmp/scope-df-berkeley.txt',17835,18100),('berkeley-highestweight-center.txt','/tmp/scope-df-berkeley.txt',18180,18795),('berkeley-rootunity-coordinate.txt','/tmp/scope-df-berkeley.txt',16105,16370),('berkeley-r-schur-crystals.txt','/tmp/scope-df-berkeley.txt',18792,19155),('etingof-exercise11.txt','/tmp/scope-df-etingof.txt',568,594),('lusztig-negative-sign.txt','/tmp/f42-b10-lusztig.txt',1780,1830)]
source_reads=[]
for name,src,a,z in passages:
 lines=pathlib.Path(src).read_text().splitlines();dst=B/'source-evidence'/name;dst.write_text('\n'.join(f'{i}: {lines[i-1]}' for i in range(a,min(z,len(lines))+1))+'\n');source_reads.append({'source_text':src,'source_text_raw_sha256':sha(src),'line_range':[a,z],'durable_excerpt':str(dst),'excerpt_raw_sha256':sha(dst),'qualification':'Read the specified full-text passage for source-claim and prerequisite comparison; no whole-source reading or new proof certification asserted.'})
D=json.load(open(paths[0])); originals={d['decline_id'][:8]:d for d in D['decisions'] if d['decision']=='owner-decision'}
Cs={n:json.load(open(f'research/{RUN}-batch-{n}.coverage.json')) for n in [6,7]}
REASONS={
'04024288':'The finite-type braid action, reduced-word root parameterization and root-vector PBW route are optional additional results, outside this pair’s approved formal-shuffle/crossed-double triangular-decomposition route. Generic-field divided powers already occur before the source’s integral-form discussion and crystal operators; neither later construction is a prerequisite asserted here. QG-2 does not declare these results. Owner resolves their deferral beyond the current 15-pair build: destination owner-decision records uncommissioned future placement, with no current delivery claim or new page/item authorized.',
'a0787ad8':'Section 6.8 changes the formulas for negative weight L(s)<0 by replacing v_s with -v_s^{-1}. This pair has the equal positive weight L(s)=1 throughout, so these formulas are unused. Owner retains the out-of-scope disposition for this build and removes the unsupported KL-8 placement: KL-8 is the degenerate Ariki theorem, not a registered home for negative-weight Hecke theory. No future placement or additional result is commissioned.',
'aa2f224e':'The exclusions are only §12.2.2 root-of-unity representations and §12.2.4 matrix-coefficient duality with C_q(SL(2)). The present pair works over Q(q) and develops neither exclusion. §12.2.3 Hopf formulas are not excluded by this row: the pair proves its fixed JKK inverse-torus Hopf convention locally. Coordinate duality requires the quantum coordinate Hopf algebra and matrix-coefficient pairing, not an asserted q-scheme prerequisite. Owner retains these exact exclusions outside the current build.',
'efcd565c':'Finite-type completed universal R-matrix/quasitriangular structure and quantum Schur–Weyl mutual-centralizer duality are additional results unused by this pair’s presentation, Hopf structure and triangular decomposition. The source develops them before Kashiwara operators, so no crystal prerequisite is asserted. The QG-5 weightwise quasi-R tensor bar and QG-6 affine q-wedge/Fock inventories promise neither exact theorem. Owner resolves deferral beyond the current 15-pair build: destination owner-decision records uncommissioned future placement of both results, with no affine/Fock delivery claim and no new page/item authorized.'}
E={
'04024288':'Berkeley §13.1.4, printed pp.310–312: generic divided-power formulas in Theorem13.1.4.2, reduced-word positive-root parameterization13.1.4.5 and PBW13.1.4.7 precede integral-form Remark13.1.4.8 and crystals§13.3. The source displays these theorem statements and only a partial relation check; it does not give full proofs of the three theorems here. Current triangular-decomposition Statement(i)–(iii)/Proof1.1–3.1 invokes the crossed-double and generic shuffle suppliers, not the braid action. Complete QG-2 inventory in plan-quantum-groups-track.md declares integral forms, skew derivations and highest weights, not these three results. Resolved owner disposition is deferral to an uncommissioned future frontier; the owner-decision destination is a sentinel for future placement, not an unresolved current-run decision. No source theorem is newly certified.',
'747fc77d':'Berkeley §§13.2.1–13.2.2, printed pp.313–323 and complete presented passages: Verma construction/simple quotient, dominant finite-dimensional highest weights and character deformation are distinct from shifted Harish-Chandra isomorphism13.2.2.5 onto even-torus Weyl invariants. QG-2 declares type-one quantum Verma/simple and integrable highest-weight theory, with character deformation; it declares no quantum-center/Harish-Chandra theorem. Splitting this coverage locator does not certify all incidental statements of either section. Current rank-one theorem covers its N≥0 cyclic quotient separately; the general finite-type results and center isomorphism are not suppliers of current triangularity. Owner resolves the highest-weight component to its actual planned QG-2 home, and the center component to explicit beyond-build uncommissioned future placement.',
'9cbeedc9':'Etingof–Semenyakin §2.7 Exercise(11), printed p.11, is an exercise, with no supplied proof; it asks for M_m for every integer m, its K/e action, then an M_m-to-PBW proof. Current thm-quantized-sl-two-string-formulas Statement(iii)/Proof3.1 proves the universal cyclic quotient and infinite divided-power basis/action for N≥0 before Proof4.1–5.1 forms its finite simple quotient. In ordinary basis u_t=F_i^t w_N, the action is K_i u_t=q_i^{N-2t}u_t and E_i u_t=[t]_i[N-t+1]_i u_{t-1}; this is the exercise’s nonnegative m case. Current proof relies on earlier triangular decomposition/PBW, so it does not deliver the reverse Verma-to-PBW route. Its statement does not promise m<0. Owner records the already local N≥0 content inline, retains m<0 as declared future general-Verma content at QG-2, and excludes the unused alternate PBW proof route. No duplicate module or new proof is authored.',
'aa2f224e':'Berkeley §§12.2.2,12.2.3,12.2.4, printed pp.277–281, complete presented passages: root-of-unity theory; the intervening Hopf formulas; then generators/relations C_q(Mat2)/(det_q-1), matrix coefficients of the two-dimensional module and a bialgebra-duality proof. That proof uses matrix coefficients and faithfulness, not a q-scheme surface. Current Hopf Statement/Proof uses its explicit JKK inverse-torus convention; the source’s different §12.2.3 convention is not a newly omitted result. Owner resolves exclusion to exactly §§12.2.2 and12.2.4 and removes both the imprecise intervening locator and unsupported prerequisite. This is placement evidence, not independent certification of the coordinate-duality proof.',
'efcd565c':'Berkeley §§13.2.3–13.2.4, printed pp.323–327: §13.2.3.1 constructs quasitriangular structure from the quantum double in the h-adic completed tensor product,13.2.3.12 states its braid/root-vector product formula, and13.2.4.3 states quantum Schur–Weyl duality on the defining representation tensor powers. Kashiwara operators begin only in§13.3. The Schur–Weyl theorem is stated without a full mutual-centralizer proof here, and no new proof completion is asserted. Exact QG-5/6 inventories distinguish weightwise quasi-R bars and affine q-wedges/Fock from these results. Current QG-1 asserts neither theorem. Owner resolves both as deferred uncommissioned future material outside this build; sentinel owner-decision is an explicit disposition, not a pending decision.',
'a0787ad8':'Lusztig §6.8, printed p.31, complete short paragraph read with adjacent6.6–6.7: for L(s)<0 replace v_s by -v_s^{-1} in statements and proofs. Current def-normalized-type-a-hecke-algebra-and-its-bar-involution explicitly fixes the positive equal-parameter type-A convention. The complete KL-8 inventory in plan-kazhdan-lusztig-track.md is the degenerate Ariki theorem and contains no negative-weight Hecke theorem. Owner resolves the existing out-of-scope row by removing its false future-home assertion, with no source proof certification or current claim change.'}
patches=[]; evidence_by_key={}
for prefix,old_dec in originals.items():
 n=int(old_dec['batch']);C=Cs[n]
 for pi,p in enumerate(C['pages']):
  for si,s in enumerate(p['sources']):
   matches=[(ci,c) for ci,c in enumerate(s['contents']) if c['name']==old_dec['name'] and s['url']==old_dec['source_url'] and p['page']==old_dec['page']]
   for ci,old in matches:
    new=copy.deepcopy(old)
    if prefix in REASONS: new['reason']=REASONS[prefix]
    if prefix in ['04024288','efcd565c']:new['destination']='owner-decision'
    if prefix=='aa2f224e':new['name']='Ch. 12, §§12.2.2 and 12.2.4 only: Rep(U_q sl(2)) at a root of unity and the duality with the coordinate Hopf algebra C_q(SL(2)); §12.2.3 Hopf structure is not excluded'
    replacements=[new]
    if prefix=='747fc77d':
     replacements=[{'name':'Ch. 13, §13.2.1: quantum Verma modules, simple highest-weight quotients and type-one integrable highest-weight theory','disposition':'deferred','destination':'divided-powers-integral-forms-and-quantum-highest-weights','reason':'The declared QG-2 inventory contains general quantum Verma/simple quotients and type-one integrable highest weights with character deformation. These general results are outside the current QG-1 inventory, whose retained rank-one N≥0 cyclic-module computation is separately covered. This is future placement for those exact components, not certification that every incidental statement of §13.2.1 is promised at QG-2.'},{'name':'Ch. 13, §13.2.2, Theorem 13.2.2.5: the shifted Harish-Chandra isomorphism for the quantum center onto even-torus Weyl invariants','disposition':'deferred','destination':'owner-decision','reason':'The quantum-center/Harish-Chandra theorem is not in QG-1 or the declared QG-2 inventory and is unused by this pair. Owner resolves its deferral outside the current 15-pair build; destination owner-decision records uncommissioned future placement, with no claimed delivery at QG-2 and no new page/item authorized.'}]
    if prefix=='9cbeedc9':
     replacements=[{'name':'§2.7, Problems, Exercise (11) (printed p. 11), nonnegative highest-weight case m=N≥0: the infinite cyclic rank-one Verma quotient and its K/e action','disposition':'inline','item':'thm-quantized-sl-two-string-formulas','reason':'Statement(iii)/Proof3.1 locally constructs A_i/(A_iE_i+A_i(K_i-q_i^N)), its infinite F_i^(t) basis and K/E/F action for N≥0 before the finite simple quotient. This is the nonnegative m case of the exercise; source proof is not imported and the full integer-m exercise is not claimed delivered.'},{'name':'§2.7, Problems, Exercise (11) (printed p. 11), negative highest-weight case m<0: the rank-one Verma module M_m and its K/e action','disposition':'deferred','destination':'divided-powers-integral-forms-and-quantum-highest-weights','reason':'The current rank-one Statement(iii) promises N≥0, not m<0. The negative-integer case belongs to the general quantum Verma/simple-quotient construction declared at QG-2; it is deferred future content, not an unmet supplier of the present finite simple string construction.'},{'name':'§2.7, Problems, Exercise (11) (printed p. 11), final instruction: use Verma modules M_m to prove the rank-one PBW theorem','disposition':'out-of-scope','reason':'The current rank-one proof obtains its normal basis from the earlier triangular-decomposition supplier and then constructs its Verma quotient. It does not use the exercise’s reverse Verma-to-PBW proof route. Owner excludes that alternate proof route without excluding the locally retained nonnegative Verma computation or weakening the current PBW result.'}]
    patches.append({'prior_decline_id':old_dec['decline_id'],'path':f'research/{RUN}-batch-{n}.coverage.json','original_json_pointer':f'/pages/{pi}/sources/{si}/contents/{ci}','selector':{'page':p['page'],'source_url':s['url'],'name':old['name']},'operation':'replace_exact_array_member_with_rows','before':copy.deepcopy(old),'after_rows':copy.deepcopy(replacements),'before_decision':copy.deepcopy(old_dec),'evidence':E[prefix]})
    for r in replacements: evidence_by_key[(p['page'],s['url'],r['name'])]=E[prefix]+' Source passages and input snapshots are in '+str(B)+'.'
# Apply by original-name lookup, rather than shifted pointers.
for patch in patches:
 C=Cs[int(patch['before_decision']['batch'])]
 for p in C['pages']:
  for s in p['sources']:
   if p['page']==patch['selector']['page'] and s['url']==patch['selector']['source_url']:
    at=next(i for i,c in enumerate(s['contents']) if c==patch['before']);s['contents'][at:at+1]=patch['after_rows']
for n,C in Cs.items():write(B/'proposed'/f'{RUN}-batch-{n}.coverage.json',C)
# Private shadow only: use the native exact identity/hash generator and structural checker.
for p in R.joinpath('research').glob(f'{RUN}-batch-*.coverage.json'):shutil.copy2(p,B/'shadow/research'/p.name)
for p in ['research/plan-spec.json',f'research/{RUN}-alpha-groups.json',paths[0]]:shutil.copy2(p,B/'shadow/research'/pathlib.Path(p).name)
for n,C in Cs.items():write(B/'shadow/research'/f'{RUN}-batch-{n}.coverage.json',C)
cmd=['node','tools/scope-decisions.mjs','refresh','--run',RUN,'--group','f','--root',str(B/'shadow')];r=subprocess.run(cmd,capture_output=True,text=True);assert r.returncode==0,r.stderr
PD=json.load(open(B/'shadow/research'/pathlib.Path(paths[0]).name))
for d in PD['decisions']:
 key=(d['page'],d['source_url'],d['name'])
 if key in evidence_by_key: d['decision']='stands';d['evidence']=evidence_by_key[key]
 assert d['decision']=='stands',d
write(B/'proposed'/pathlib.Path(paths[0]).name,PD);write(B/'shadow/research'/pathlib.Path(paths[0]).name,PD)
for patch in patches:
 patch['after_decisions']=[d for d in PD['decisions'] if d['page']==patch['selector']['page'] and d['source_url']==patch['selector']['source_url'] and d['name'] in [r['name'] for r in patch['after_rows']]]
 patch['retired_decline_ids']=[patch['prior_decline_id']] if patch['prior_decline_id'] not in [d['decline_id'] for d in patch['after_decisions']] else []
check=['node','tools/scope-decisions.mjs','check','--run',RUN,'--group','f','--root',str(B/'shadow')];r=subprocess.run(check,capture_output=True,text=True);assert r.returncode==0,r.stderr
write(B/'structural-check.json',{'command':check,'exit_code':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'qualification':'Native scope structural check against private proposed metadata; this is not a native run gate or independent mathematical audit.'})
write(B/'proposal.json',{'version':1,'run':RUN,'group':'f','status':'private-proposal-only-no-canonical-writes','reviewer':'step8_scope_owner_f','input_guards':guards,'scope':'Only exact coverage metadata and group-f decline decisions. No canonical item/page/manifest/proof edits, no engine controls, no approved claim changes.','owner_row_count':len(originals),'additional_prior_owner_rows':['a0787ad864941a01f3079e5b44c0fb67989c5a1de4e69ef5baaf0886a3988e19'],'source_reads':source_reads,'coverage_patches':patches,'proposed_files':[str(B/'proposed'/f'{RUN}-batch-{n}.coverage.json') for n in [6,7]]+[str(B/'proposed'/pathlib.Path(paths[0]).name)],'integration':'Verify input guards and exact before rows. Replace each selected array member by after_rows using selector, not shifted original_json_pointer. Install proposed group-f register only after checking native-derived row/context hashes against current plan. Retire replaced decline identities exactly as listed. Root owns serial integration and gates.'})
print('Built',len(patches),'guarded coverage changes;',len(PD['decisions']),'current proposed group-f declines, all stands.');print(r.stdout)
