import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const run='frontier-43-complex-representation-15', base=`research/${run}-step8-owner-b-proposal`;
const canonical=x=>Array.isArray(x)?`[${x.map(canonical).join(',')}]`:x&&typeof x==='object'?`{${Object.keys(x).sort().map(k=>`${JSON.stringify(k)}:${canonical(x[k])}`).join(',')}}`:JSON.stringify(x);
const hash=x=>createHash('sha256').update(x).digest('hex');
const read=p=>JSON.parse(readFileSync(p,'utf8'));
const write=(p,x)=>writeFileSync(p,JSON.stringify(x,null,2)+'\n');
const plan=read('research/plan-spec.json'), byPage=new Map(plan.pages.map(p=>[String(p.id),p]));
function closureIds(id){const seen=new Set(); const visit=id=>{if(!id||seen.has(id))return;seen.add(id);for(const x of byPage.get(id)?.requires??[])visit(String(x));};visit(id);return [...seen].sort();}
function destinationState(id){if(!id)return {kind:'none'};if(id==='owner-decision')return {kind:'owner-decision'};if(byPage.has(id)){const p=byPage.get(id);return {kind:'page',id,order:p.order,category:p.category,title:p.title,requires:[...(p.requires??[])].map(String).sort(),items:(p.items??[]).map(x=>String(typeof x==='string'?x:x?.id??'')).filter(Boolean).sort()};}throw Error('unsupported destination');}
function native(batch,page,kind,url,row){const p=byPage.get(page);const context={page:{id:page,order:p.order,kind:p.kind,category:p.category,title:p.title,requires:[...(p.requires??[])].map(String).sort(),closure:closureIds(page).filter(x=>x!==page).map(id=>{const d=byPage.get(id);return {id,order:d?.order,kind:d?.kind,category:d?.category,title:d?.title,requires:[...(d?.requires??[])].map(String).sort(),items:(d?.items??[]).map(x=>String(typeof x==='string'?x:x?.id??'')).filter(Boolean).sort()};})}};const identity={batch,page,source_kind:kind,source_url:url,name:row.name};const destination=typeof row.destination==='string'?row.destination:null;return {decline_id:hash(canonical(identity)),group:'b',...identity,disposition:row.disposition,destination,reason:row.reason??'',row_sha256:hash(canonical(row)),context_sha256:hash(canonical({...context,destination:destinationState(destination)}))};}
const paths=[`${run}-alpha-b-scope-decisions.json`,`${run}-batch-2.coverage.json`,`${run}-batch-4.coverage.json`];
const guards=paths.map(name=>{const raw=readFileSync(`research/${name}`);writeFileSync(`${base}/before/${name}`,raw);return {path:`research/${name}`,raw_sha256:hash(raw),canonical_sha256:hash(canonical(JSON.parse(raw)))};});
const original=read(`research/${paths[0]}`), coverage2=read(`research/${paths[1]}`),coverage4=read(`research/${paths[2]}`), proposed=structuredClone(original), deltas=[], resolutions=[];
const growthReason='The published prerequisite amenable-groups-and-folner-criteria already contains thm-subexponential-growth-implies-amenability: under the ultrafilter lemma every finitely generated group of subexponential growth is amenable. This component is not duplicated here. Garrido §§4.1–4.2.1 separately constructs the first Grigorchuk group and states its amenability but non-elementary-amenability; the published discrete page and the approved 15 pairs do not supply that example or its torsion/tree-growth inputs. That stronger example is explicitly deferred outside this run, with no currently commissioned page home; no Grigorchuk delivery is claimed.';
const breuillardReason='The invariant-mean and Følner material of Lecture1 §§I/III is delivered on the earlier in-run amenability-reiter-nets-and-folner-conditions page, together with locally proved Reiter and Hulanicki criteria. Its Hulanicki supplier thm-hulanicki-weak-containment-criterion-for-amenability is draft, and thm-an-amenable-property-t-locally-compact-group-is-compact uses it at F1/Proof1.1. Lecture1 §IV is different: symmetric finitely supported generating random walks on finitely generated groups, their Markov operator/return-probability spectral radius, and Kesten\'s amenability criterion. The approved 15 pairs do not commission that random-walk/Kesten block. It remains explicitly deferred outside this run with no currently commissioned page home; owner-decision denotes that unassigned future home, not missing approval for the present exclusion.';
const phantomReason='The free-subgroup embedding into SL2(R) and Banach–Tarski applications are outside this pair and are explicitly deferred outside the approved 15-pair run, with no currently commissioned page home. They are not results of Thomas Lecture19: its complete text develops invariant means, Reiter and Følner conditions; Banach–Tarski occurs in the course title. The current SL2 representation pages do not promise these results. The separate F2 nonamenability counterexample is already delivered by cex-the-free-group-on-two-generators-is-not-amenable, Proof1.1–3.1, using the direct reduced-word mean contradiction and BHV G.2.4(ii), without a matrix embedding or Banach–Tarski theorem.';
function delta(file,pointer,before,after,action){deltas.push({path:`research/${file}`,pointer,action,before:structuredClone(before),before_canonical_sha256:hash(canonical(before)),after:after===undefined?null:structuredClone(after),after_canonical_sha256:after===undefined?null:hash(canonical(after))});}
function resolve(old,newNative,reason,evidence){const r={...newNative,decision:'stands',evidence};const at=proposed.decisions.findIndex(x=>x.decline_id===old.decline_id);proposed.decisions[at]=r;resolutions.push({original_native_decision:structuredClone(old),proposed_native_decision:structuredClone(r),owner_resolution:{decision:'retain exact approved scope; correct coverage/source metadata; explicitly defer undelivered outside-run components',reason,evidence,reviewer:'step8_scope_owner_b',item_proof_changes:[],new_items:[],new_pages:[],reading_order_changes:[],missing_result_for_approved_scope:null}});}
for(let pi=0;pi<coverage2.pages.length;pi++){const pg=coverage2.pages[pi];for(let si=0;si<pg.sources.length;si++){const src=pg.sources[si];if(src.url.includes('garrido')){const ri=src.contents.findIndex(x=>x.name==='Groups of subexponential growth and the Grigorchuk group');if(ri>=0){const oldLocator=src.locator;src.locator='17-page note: §3.1 for the discrete Følner criterion and Namioka separation; §3.2 Theorem3.8 and proof, printed pp.10–11, for growth-implies-amenability; §§4.1–4.2.1, printed pp.12–16, for the distinct Grigorchuk construction/growth example, with Proposition4.7 explicitly omitting its torsion proof.';delta(paths[1],`/pages/${pi}/sources/${si}/locator`,oldLocator,src.locator,'replace');const oldRow=structuredClone(src.contents[ri]);src.contents[ri]={...oldRow,reason:growthReason};delta(paths[1],`/pages/${pi}/sources/${si}/contents/${ri}`,oldRow,src.contents[ri],'replace');const old=original.decisions.find(x=>x.decline_id.startsWith('383225f5'));resolve(old,native('2',pg.page,'source',src.url,src.contents[ri]),growthReason,'Owner resolution by step8_scope_owner_b: independently read Garrido §3.2 Theorem3.8 and full proof, §§4.1–4.2.1 through Theorem4.9 (printed pp.10–16); Proposition4.7 explicitly omits its torsion proof. Read the published discrete-page/main-companion inventories and complete current growth item. The growth component is already delivered with its stated ultrafilter hypothesis; no Grigorchuk example appears on those pages or this pair. Retain the outside-scope exclusion while recording the stronger example as an uncommissioned future obligation. Original reviewer attribution and hashes remain in resolutions.json; no new item or proof is claimed.');}}
if(src.url.includes('Lecture19')){const oldRows=structuredClone(src.contents);const absent=src.contents.find(x=>x.name==='The free group on two generators embeds in SL_2(R); applications to Banach-Tarski');if(absent){const ci=(pg.canonical??[]).length;pg.canonical??=[];pg.canonical.push({...absent,reason:phantomReason});delta(paths[1],`/pages/${pi}/canonical/${ci}`,null,pg.canonical[ci],'append');const old=original.decisions.find(x=>x.page===pg.page&&x.name===absent.name);resolve(old,native('2',pg.page,'canonical',null,pg.canonical[ci]),phantomReason,'Owner resolution by step8_scope_owner_b: independently read all 19 PDF pages of Thomas Lecture19, whose final page ends the Reiter-to-Følner extraction; no F2 embedding, Banach–Tarski claim, or A,bA,b²A nonamenability proof occurs. Read current cex-the-free-group-on-two-generators-is-not-amenable Statement/F1–F3/Proof1.1–3.1 and its BHV/Thomas3/Thomas23 source list. Remove phantom Lecture19 attribution; retain the same excluded broader subject as a canonical coverage exclusion with honest uncommissioned future placement. Original 8c303538/3f730a52 source-native rows/hashes and all earlier evidence remain in resolutions.json.');}
src.contents=src.contents.filter(x=>x.name!=='The free group on two generators embeds in SL_2(R); applications to Banach-Tarski'&&x.name!=='Nonamenability of F_2 via the disjoint sets A, bA, b^2A');if(canonical(src.contents)!==canonical(oldRows))delta(paths[1],`/pages/${pi}/sources/${si}/contents`,oldRows,src.contents,'replace');}}
}
for(let pi=0;pi<coverage4.pages.length;pi++){const pg=coverage4.pages[pi];for(let si=0;si<pg.sources.length;si++){const src=pg.sources[si];const ri=src.contents.findIndex(x=>x.name.startsWith('Lecture 1 §§I-IV:'));if(ri>=0){const oldRow=structuredClone(src.contents[ri]);src.contents[ri]={...oldRow,destination:'owner-decision',reason:breuillardReason};delta(paths[2],`/pages/${pi}/sources/${si}/contents/${ri}`,oldRow,src.contents[ri],'replace');const old=original.decisions.find(x=>x.decline_id.startsWith('41b7f511'));resolve(old,native('4',pg.page,'source',src.url,src.contents[ri]),breuillardReason,'Owner resolution by step8_scope_owner_b: independently read complete Breuillard Lecture1 §§I–IV (printed pp.1–6), including Theorem1.8 and its following spectral/isoperimetric argument. Read current amenability page inventory, complete thm-hulanicki-weak-containment-criterion-for-amenability (status draft; Proof1.1–3.1), and compactness consumer F1/Proof1.1–3.1. The delivered mean/Følner/Reiter/Hulanicki block is distinguished from the uncommissioned Markov/random-walk/Kesten block. Retain an explicit future deferral with sentinel destination rather than claiming Kesten delivery on the means page. Original review evidence and hashes remain in resolutions.json.');}}}
proposed.decisions.sort((a,b)=>a.decline_id.localeCompare(b.decline_id));
write(`${base}/proposed/${paths[0]}`,proposed);write(`${base}/proposed/${paths[1]}`,coverage2);write(`${base}/proposed/${paths[2]}`,coverage4);
write(`${base}/resolutions.json`,{version:1,run,group:'b',private_proposal:true,guards,rows:resolutions,coverage_harvest_deltas:deltas,unchanged_native_decisions:original.decisions.filter(x=>!resolutions.some(r=>r.original_native_decision.decline_id===x.decline_id)).map(x=>({decline_id:x.decline_id,row_sha256:x.row_sha256,context_sha256:x.context_sha256,decision:x.decision,evidence:x.evidence})),notes:['coverage.sources[].contents is the owning harvest inventory (tools/coverage-checklist.mjs harvestOf); no separate current run harvest carrier with these claims exists.','Apply row deltas serially on their guarded exact before rows; do not overwrite whole files if other group edits exist.','Final native hashes must be recomputed after all writers drain. Context hashes here bind the current canonical plan; the plan itself is not edited.']});
console.log(JSON.stringify({resolutions:resolutions.length,deltas:deltas.length,remaining_owner_decisions:proposed.decisions.filter(x=>x.decision==='owner-decision').length,guards}));
