from pathlib import Path
import json,hashlib,re
p=Path(__file__).parent;root=Path.cwd();d=json.loads((p/'inventory.json').read_text());records=[]
qs='physics/research/extended-frameworks-2026-10-03/quantum-statistical-mechanics/workers/finite-states/'
cs='physics/research/extended-frameworks-2026-10-03/classical-statistical-mechanics/workers/gibbs-limits/'
qs_map={'lem-qsm-matrix-state-calculus':('q0','Finite Hermitian spectral/functional/trace/state calculus; positive quadratic CS; finite dimensions only'),'lem-qsm-matrix-exponential-response':('q2','Finite Hermitian Duhamel/trace derivative; Kubo–Mori convexity; dimensionless logTr exp norm-Lipschitz'),'thm-qsm-finite-gibbs-variational':('q3','Finite density support-aware Klein and Gibbs variational identity; finite entropy concavity/product additivity'),'thm-qsm-finite-entropy-composition':('q3','Finite bipartite support inclusion and subadditivity via Klein; no strong subadditivity imported'),'lem-qsm-finite-gibbs-kms':('q6','Finite Hermitian unitary Heisenberg group and finite Gibbs bounded analytic strip boundary relation, width beta*hbar seconds')}
cs_map={'def-csm-lattice-gibbs-specification':('g3','Finite-alphabet bounded finite-range proper conditional kernels and full DLR conditional identities'),'lem-csm-lattice-product-and-measure-compactness':('g2','Countable finite-alphabet cylinder premeasure/Caratheodory with inherited CC, local probability compactness and continuous/local function equivalence'),'lem-csm-lattice-specification-consistency':('g3','Conditional Gibbs decomposition and gamma_Lambda gamma_Delta=gamma_Lambda, not free-marginal consistency'),'thm-csm-ising-high-temperature-state':('g4','Half-TV influence row sum bounded by sum_j tanh(beta|Jij|)<1, uniform finite-range assumption; any bounded site field'),'thm-csm-chain-dlr-uniqueness':('g9a','Finite positive transfer matrix Markov bridge; homogeneous nearest-neighbor1D finite beta,J,h; uniform endpoint convergence'),'thm-csm-ising-low-temperature-coexistence':('g6','2D nearest-neighborJ>0,h=0,betaJ>=2; parity Peierls proof; distinct stationary +/- magnetization states, no extremality claim'),'thm-csm-ising-coexistence-pressure-cusp':('g6','Same lowT class; DLR lattice variational identity yields nonzero opposite subgradient slopes at h0')}
root_scopes={'def-c-star-algebra':'Possibly nonunital complex complete submultiplicative *-algebra with C*-identity; our completion supplies nonzero unit explicitly','def-countable-choice':'Axiom Countable Choice; inherited countable density/cylinder extensions use it, never presented as arbitrary AC','thm-hadamard-three-lines':'Bounded continuous closed vertical strip function, holomorphic inside; finite boundary suprema including zero; strictly interior exponents positive so M0=0 uniqueness applies after rotation/rescaling','thm-weierstrass-convergence-holomorphic-functions':'Holomorphic functions on open C domain, locally uniform convergence =>holomorphic limit and locally uniform derivative convergence','thm-goursat-triangle-theorem':'Holomorphic scalar function on open domain; filled triangle contained there has zero contour integral incl degenerate vertices','thm-morera-triangle-theorem':'Continuous scalar function on open domain with zero integrals on all contained filled triangles =>holomorphic; used after explicit seam splitting','thm-liouville-bounded-entire-function':'Scalar entire function bounded on all C =>constant; periodic KMS strip extension proved locally entire before use'}
for i in d['external_supplier_ids']:
 cons=[r['id'] for r in d['items'] if i in r['deps']]
 if i in qs_map or i in cs_map:
  table,base,file=(qs_map,qs,'state-proofs.md') if i in qs_map else (cs_map,cs,'proof-modules.md')
  anchor,scope=table[i];path=base+file;prior=json.loads((root/(base+'inventory.json')).read_text());lookup={r['id']:r for r in prior['items']};assert i in lookup
  rec=dict(id=i,path=path,proof_module=path+'#'+anchor,domain=lookup[i]['domain'],statement_hypotheses=scope,status=lookup[i].get('status','complete scoped research module; not production acceptance'),actual_reading='Complete actual module text inspected this session; argument scope independently checked, no production publication presumed',consumer_uses=cons,raw_sha256=hashlib.sha256((root/path).read_bytes()).hexdigest())
 else:
  path='items/'+i+'.md';f=root/path;assert f.exists();s=f.read_text();status=re.search(r'^status: (.+)$',s,re.M)[1]
  rec=dict(id=i,path=path,domain='mathematics',statement_hypotheses=root_scopes[i],status=status,actual_reading='Full exact current Definition/Statement and proof/remarks read; root publication/verification status inherited, not upgraded',consumer_uses=cons,raw_sha256=hashlib.sha256(f.read_bytes()).hexdigest())
 records.append(rec)
(p/'supplier-map.json').write_text(json.dumps({'version':1,'suppliers':records,'nonloadbearing_readings':[{'path':'physics/research/first-principles-2026-10-03/thermodynamics/scaffold/completed-developments.md','sections':['M17','M18','M27','M28','M29','M33'],'use':'Exact old finite/trace models and boundary/secant architecture read; classical M28/M29 support count/concentration argument repeated locally for quantum matrices, not imported as a quantum theorem.'},{'path':'physics/research/extended-frameworks-2026-10-03/quantum-statistical-mechanics/ensemble-bridge.md','sections':['Q0','Q1','Q2','Q3','Q4','Q5'],'use':'Full independent finite-level shell bridge and diagonal embedding actually read; no generic interacting equivalence inferred.'}]},indent=2)+'\n')
raw=[{'path':str(f.relative_to(p)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()} for f in (p/'raw').glob('*')]
(p/'source-manifest.json').write_text(json.dumps({'retrievals':[{'title':'Nachtergaele and Sims, Lieb-Robinson Bounds in Quantum Many-Body Physics','requested_url':'https://arxiv.org/pdf/1004.2086','retrieved':'2026-10-04 session','pdf_pages':36,'visible_source_version':'arXiv1004.2086v1 header; author Date Version November26,2024 appears on retrieved firstpage; not silently assigned 2010-only revision','reading_record':'source-reading.md'}],'artifacts':raw,'failed_retrievals':[]},indent=2)+'\n')
