from pathlib import Path
import json,re,hashlib
out=Path(__file__).resolve().parent;root=out.parents[2]
p=out/'packet.json'; data=json.loads(p.read_text())
extra=['thm-blowup-projective','thm-affine-blowup-standard-charts','thm-blowup-universal-property','lem-affine-blowup-algebra-properties','thm-projective-morphism-proper','lem-local-fibre-dimension-bound-via-polynomial-quasifiniteness','lem-nonempty-smooth-scheme-finite-separable-point','thm-etale-formally-etale-finite-presentation','thm-smooth-local-standard-form','thm-jacobian-criterion-smooth-morphism','lem-generic-freeness-finite-type-algebra-module','lem-ag-geometric-regularity-field-tests','thm-ag-separating-transcendence-basis-perfect-field','thm-ag-field-differentials-separable-rank','lem-nonaffine-connected-group-geometrically-connected','thm-serre-criterion-ampleness','lem-fpqc-cover-submersive','lem-fpqc-descent-properness-components','thm-faithfully-flat-descent-of-flatness','thm-faithfully-flat-descent-vanishing','thm-prime-filtration-of-a-finite-module','lem-constructible-dense-contains-open']
existing={x['id'] for x in data['published_suppliers']}
for id in extra:
 if id in existing: continue
 f=root/'items'/f'{id}.md';s=f.read_text();m=re.search(r'## (?:Statement|Definition)\n(.*?)(?=\n## |\Z)',s,re.S)
 data['published_suppliers'].append(dict(id=id,path=str(f.relative_to(root)),raw_sha256=hashlib.sha256(f.read_bytes()).hexdigest(),exact_statement=m.group(1).strip(),status_line=re.search(r'^status:.*$',s,re.M).group(0),proof_read=False,reading_note='Exact Statement examined for supplier interface; whole item proof not independently audited here.'))
for n in data['nodes']:
 n['status']='source-proof-and-local-prerequisite-arguments-supplied-await-parent-review'
 n['closure_evidence']='research/frontier-40-geometry-braids-rep-27-owner-arithmetic-models/neron-source/closure-supplement.md'
data['source']['additional_reading']='BLR2.2/8–16,2.3/5–10,2.5/1–6,4.2/1–3,6.4/4 fully read. Source references to further EGA facts were replaced by exact published suppliers or explicit local proofs in closure-supplement.md.'
data['local_closure_status']='Necessary local prerequisite arguments supplied; parent mathematical review pending, no ready stamp.'
data['irreducible_current_gap']=None
data['remaining_review_obligations']=['Parent checks all local arguments, actual helper Statements and acyclic dependency placement.','Parent validates published supplier ordinary acceptance metadata; published label is not an independent audit.','Authoring must include the explicit finite-stage affine-neighbourhood, universal density, divisor square and ample descent arguments, not merely refer to packet labels.']
rows=[('N01','P01,P02','Dilatations and defect computation',[]),('N02','P03,P04','Defect decrease and finite smoothening',['N01']),('N03','P05,P06','Projective weak models and rational mapping',['N02']),('N04','P07,P08,P09','Invariant volume and finite minimal classes',['N03']),('N05','P10','Separated minimal union and translations',['N04']),('N06','P11','Birational group law',['N05']),('N07','P12','Strictification',['N06']),('N08','P13','Strict law graph calculus',['N07']),('N09','P14','Separated translate gluing',['N08']),('N10','P15,P16','Finite translate completion and uniqueness',['N09']),('N11','F10,F14','Affine codimension-one neighbourhoods and divisors',['N04']),('N12','P17,P18,F15','Cube-derived square over DVR',['N10']),('N13','P19,F11','Divisor ampleness',['N11','N12']),('N14','P20,P21,F12','Effective ample pair and group descent',['N10','N11','N13']),('N15','P22','Weil extension',['N04']),('N16','P23','Full minimal model embedding',['N14','N15']),('original','P24,P25','General Neron existence',['N05','N15','N16'])]
data['reduced_authoring_packets']=[dict(label=l,includes=inc.split(','),title=t,earlier_labels=deps,new_helper=l!='original',label_is_item_id=False) for l,inc,t,deps in rows]
data['initial_count']=data['count'];data['count']=dict(parent_reported_original_A_items=28,new_Neron_helpers=16,original_exists_theorem_reused=True,dual_helpers_parent_estimate=10,etale_helpers_parent_estimate=9,integrated_A_arithmetic=63,remaining_A_slots_to_100=37,mathematical_review_complete=False,note='16 is a concrete grouping of claims with inline foundation proofs, not 16 independently certified item carriers. Parent inventory and review must confirm actual IDs/count.')
p.write_text(json.dumps(data,indent=2)+'\n')
md=out/'packet.md';s=md.read_text();start=s.index('**Status:');end=s.index('\n\n',start);s=s[:start]+'**Status: source proofs and local prerequisite arguments supplied in [closure-supplement.md](closure-supplement.md); parent mathematical review pending. Do not mark ready.**'+s[end:];s=s.replace('## Reading and counts','## Initial reconstruction (superseded counts)');s+='\n\n## Current closure and packaging\n\nThe closure supplement supersedes the initial unclosed-foundation status and forty-packet addition arithmetic. It supplies the required local arguments and groups the construction into sixteen new helpers plus the existing promised theorem. `packet.json` has exact additional supplier Statements and the current grouping. Parent mathematical review remains required; no ready stamp was made.\n';md.write_text(s)
